### ISSUE TITLE
Complete QA on new ContentType Impl

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#10167]
- [ ] SQL needs to be tested in all 5 DBs.   
- [ ] Edit Field Action needs to be tested
- [ ] Insure that logic and validations are intact from the Struts Action
