### ISSUE TITLE
Regression tests for Content Types in MSSQL

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#10180]
Description by Shay:
Using a MSSQL DB, confirm that you are able to accomplish below tasks through the UI:
- [x] You can navigate to Content Types portlet
- [x] Content types dropdown is functional
- [x] "Search" and "Reset" buttons are functional
- [x] "Show System" checkbox is functional
- [x] Sort by columns works
- [x] You can create/modify a new content type
- [x] You can view Entries and Relationships
- [x] You can relate content to the new content type (i.e.: if you have a new content type which type is "page", make sure that you can create a page and use this new content type)

**Comment by shaydotcms** [comment]
Failed QA. Unable to:
- [ ] Create/modify a new content type: waiting for fix on #10282 
- [ ] View Entries: waiting for fix on #10281
- [ ] Relate content to the new content type: waiting for fix on #10282

**Comment by shaydotcms** [comment]
Waiting for **new** fix on #10282
