### ISSUE TITLE
Verify new functionality of Content Types after dotcms upgrade

### ISSUE THREAD

**Issue by shaydotcms** [dotCMS/core#10216]
Need to upgrade from previous dotcms release in different DBs and test new functionality of Content Types
Some of the verifications may include the following:
 - [x] Make sure that content types dropdown is functional
 - [x] "Search" and "Reset" buttons are functional
 - [x] "Show System" checkbox is functional
 - [x] You can sort by columns
 - [x] You can create/modify a new content type
 - [x] You can click on view Entries and view Relationships
 - [x] You can relate content to the new content type (i.e.: if you have a new content type which type is "page", make sure that you can create a page and use this new content type)

**Comment by erickgonzalez** [comment]
Related to https://github.com/dotCMS/core/issues/10203

**Comment by nollymar** [comment]
"View Entries" is not working as expected. Nothing is displayed after clicking on it. 

On the other hand, the error below is displayed when trying to view entries for **Tour RSVP**:
An unexpected system error occurred.
limit param must be more than 0

Tested on Postgres with a client DB

**Comment by nollymar** [comment]
This exception is thrown when I add a new field to a new content type:

~~~
[23/01/17 09:40:30:003 EST] ERROR util.ContentTypeUtil: null
java.lang.NullPointerException
	at com.dotmarketing.business.LayoutAPIImpl.loadLayoutsForUser(LayoutAPIImpl.java:77) ~[dotcms_4.1_90db46f.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:93) ~[dotcms_4.1_90db46f.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:84) ~[dotcms_4.1_90db46f.jar:?]
	at com.dotcms.util.ContentTypeUtil.getActionUrl(ContentTypeUtil.java:69) ~[dotcms_4.1_90db46f.jar:?]
	at com.dotmarketing.portlets.structure.factories.StructureFactory.lambda$pushSaveUpdateEvent$0(StructureFactory.java:434) ~[dotcms_4.1_90db46f.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
~~~

**Comment by nollymar** [comment]
It is not possible to add/edit content with relationships. This error is displayed: "Ooops, sorry. This has caused a problem. Try again."

and this exception is thrown: https://gist.github.com/nollymar/0e4f827c12b74f4701d962c560717337

**Comment by dsilvam** [comment]
Issue with types with "File" field: https://github.com/dotCMS/core/issues/10500

**Comment by dsilvam** [comment]
Note to QA: new issues are being created. This issue can be moved to Done when those are fixed.

**Comment by dsilvam** [comment]
Issue with content with rels: https://github.com/dotCMS/core/issues/10501

**Comment by dsilvam** [comment]
Issue with view entries in content types screen: https://github.com/dotCMS/core/issues/10503

**Comment by dsilvam** [comment]
Another issue with view entries: https://github.com/dotCMS/core/issues/10502

**Comment by shaydotcms** [comment]
All checkboxes mentioned in the Description passed QA.

View entries are displaying properly including  Tour RSVP
#10502 Passed QA

No error in logs when new field is added to Content Types
#10505 passed QA

Add/edit content with relationships passed QA
#10501

Tested on upgrade using 3.6 client db to latest master-4.1
Mac OS 10.10 / Postgres 9.3.5
