### ISSUE TITLE
New build system

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#11078]
## In general this is what we need to do:

1. Use latest version for webpack
2. ```dev mode``` should watch, compile and update files in ```/tomcat8/dotAdmin```
3. ```build mode``` should set ```env``` variable to ```production``` and make sure everything it's build for production.
4. We should have a ```watch mode``` for tests, so people can do ```TDD```
5. Make sure it works in ```dev``` mode and in ```/dotAdmin``` check the ```<base href="/build/">``` tag.
6. Create ```README.md```

## Tasks

- [x] Update angular
- [x] Rules
    - [x] Update rules components to new angular version
    - [x] Include or import semantic code and assets only for rules components
- [x] Fix SCSS/CSS assets
- [x] Set dev environment with proxy to dotcms
    - [x] Add rules for background image and logo
    - [x] iframe it's loading localhost:8080 in the whole window
    - [x] Proxy the websocket
- [x] Fix all TS errors
- [x] Fix all TSLint issues
    - [x] Review the rules in the ```tsconfig.json```
- [x] Make sure production build works
- [x] Make primeng.min.css global to the main.css file
- [x] Fix ```Cannot read property 'classList' of null``` in the loading indicator.
- [x] Make font-awesome local.
- [x] Create all the icons for the meta information
- [x] Create manifest.json
- [x] Fix logout, it's showing an empty alert.
- [x] Unit test and e2e test are running.
- [x] Make coverage works.
- [x] Center loading indicator
- [x] Update README
