### ISSUE TITLE
Read only dotCMS Deployment

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#11407]
Before we release 4.1 we need to create a read only dotCMS deployment.  This read-only deployment should:

- [x] be configured only via environmental variables
- [x] have the `/assets`, `/dotsecure`, `WEB-INF/felix` and `/velocity` folders externalized from the read only path
- [x] pick up an enterprise license from a licence pack with no user intervention
- [x] be able to use osgi plugins, including velocity portlets

**Comment by dsilvam** [comment]
Felix : https://github.com/dotCMS/core/issues/10370
Velocity: https://github.com/dotCMS/core/issues/11303
