### ISSUE TITLE
Contentlet : don't inherit from WebAsset

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#18727]
We have a legacy data model that needs to be updated and improved to streamline operations.  Additionally, we have a number of classes that still rely on Hibernate which we need to get rid of.  Hibernate causes us a number of issues that are hard to debug.  Here is the main challenge - how to do this work without breaking existing customers implementations.

- [x]  Get rid of the Fat Contentlet, e.g. `contentlet.business.Contentlet`
- [x]  Add an owner field to the `identifier` table (this is the owner field for the contentlet, the user.id who initially created it)
- [x]  Add a `create_date` to the `identifier` table (this is the iDate of the Inode)
- [x]  Add an `asset_subtype` to the identifier table (this will store the contentType.variable)
- [x]  We need to create a `ContentletDbTransformer`
- [x]  Replace HibernateUtil with DotConnect
- [ ]  Update import/export format to be json
- [ ]  make sure Import/Export work
- [ ]  Make sure ContentHandlers use json rather than XML
