### ISSUE TITLE
New Favorites Pages Portlet

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22343]
## Problem:

With all the improvements in edit mode, managing pages in dotCMS should be easy.  But forcing content editors to dig through dotCMS’s file browser to find the right “index” page and then having to double click on it can be daunting for non technical editors.  We need to get rid of the "index file" experience. 

Content editors need a quick way to pop open a site or subpage in edit mode, and use the site to browse to the page they want to edit and get busy.  And it would be nice if content editors could bookmark pages for quick, 1 click access to manage them.

## Solution: Start Pages & Favorites

We need to create a portlet that shows a user card views of “start pages”.  A “Start Page” is just a saved url for a page that can be clicked on and the user be instantly taken to the given page in edit mode, including the selections for device, persona and language that were set when the start page was created.

<p></p>

(Internal doc)

<https://docs.google.com/document/d/1yRX50V5rbFE3u1BEtOAnTcH9VjuQSDepljlpYDSm3sA/edit>

<p></p>

Figma Wireframe (still in development) :  
<https://www.figma.com/file/aL0kTopu5OJ96S166GRyxC/Channel-%2F-Page-Manager>

<p></p>

## Portlet Card View (Default View)

The cards should be shown in alphabetical order.

<p></p>

## Adding a Start Page

From edit mode, start pages can be added by any user for themselves. If a start page is added by a CMS_Admin, they can choose to share it with one or more roles.

<p></p>

When saving an edit mode view as a start page, we should the whole page url with the page’s parameters like `host_id`, `language`, `persona` and `device` that has been selected for viewing.  Additionally, we should take a screenshot of the page at the time of the save using something like `html2canvas`, save it as a dotAsset and show this screenshot when displaying the card.

<p></p>

If the page is being viewed as a device, the screenshot should be taken using the width/height that is set in the device.

<p></p>

Start pages can be added by users for themselves and/or by admins to share with users.  In card view, should these lists of start pages (“my start pages” and “shared with me”)  be shown together or should they be separated visually?

<p></p>

## Removing a Start Page

If a user has added a start page for themselves, they can click on a pencil box on the card's top right corner and edit or delete it (after confirmation) - normal users can only remove start pages they have added themselves.  If the user is a CMS_ADMIN, they can click on the pencil of a shared start page card and delete them from everyone’s view.

dotStartPage Content Type

To persist start pages we should create a system content type called `dotStartPage`.  This type would consist of a 

- title, 

- a binary field for the screencap 

- a url (textarea)

- an sortOrder integer field that will be used to sort the start pages. 

We will need an upgrade task that creates the dotStartPage content type on startup.  The dotStartPage content type should be marked as a “system” content type.

## Sub-tasks

```[tasklist]
- [ ] #24174
- [ ] https://github.com/dotCMS/core/issues/24173
- [ ] https://github.com/dotCMS/core/issues/24162
- [ ] https://github.com/dotCMS/core/issues/24161
- [ ] https://github.com/dotCMS/core/issues/23061
- [ ] https://github.com/dotCMS/core/issues/23060
- [ ] https://github.com/dotCMS/core/issues/22965
- [ ] https://github.com/dotCMS/core/issues/24172
- [ ] https://github.com/dotCMS/core/issues/24221
- [ ] https://github.com/dotCMS/core/issues/22964
- [ ] https://github.com/dotCMS/core/issues/24219
- [ ] https://github.com/dotCMS/core/issues/24220
- [ ] https://github.com/dotCMS/core/issues/23058
- [ ] https://github.com/dotCMS/core/issues/23792
- [ ] https://github.com/dotCMS/core/issues/24418
- [ ] https://github.com/dotCMS/core/issues/24925
```

**Comment by wezell** [comment]
Link to feature: https://dotcms.productboard.com/feature-board/planning/features/12213979
