### ISSUE TITLE
Update CLI to pull / push content types

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#22365]
**Parent issue:** 
#22540 

Using the Quarkus example supplied by Steve, we should begin the process of building out a CLI that can "sync" e.g. pull and push content types to dotCMS.

Questions:
- Hostname vs. hostId
- Deterministic Ids?
- Use content type var everywhere
- hide default fields
  - e.g. don't show props that have false/0/empty string
- How to handle content type updates / deletes

**Acceptance Criteria:** 
~~#23240 Remove unneeded IDs from response and make sure they are not required when adding/updating~~ see https://github.com/dotCMS/core/issues/23950
- [x] #23239 send and accept hostname/folderpath for host/folder attributes
- [x] #23241 hide fields when values not set/set to default
- [x] #23242 ensure we have not broken layout support

**Comment by fabrizzio-dotCMS** [comment]
PR  https://github.com/dotCMS/core/pull/23791

**Comment by damen-dotcms** [comment]
Some functionality moved to https://github.com/dotcms/core/issues/23950

**Comment by damen-dotcms** [comment]
@fabrizzio-dotCMS please make sure we have all the tasks documented; if not in this issue let's create some new ones. Thanks!

https://github.com/dotCMS/core/tree/master/tools/cli/commands

**Comment by nollymar** [comment]
**Internal QA:** Needs work

`ct find` fails when pulling all content types using full starter data. It fails to deserialized relationships and categories. Log details: https://gist.github.com/nollymar/94dcb4a58b9ef29c554160b73444eea3.

**Comment by fabrizzio-dotCMS** [comment]
PR: https://github.com/dotCMS/core/pull/24512

**Comment by nollymar** [comment]
**Internal QA:** Passed
