### ISSUE TITLE
Updates to Command Line Interface Tools (Gen 2 CLI)

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#22540]
### User Story

dotCMS has a CLI that can be used in CI/CD platforms, but it can only handle pushing

- sites
- content types
- files \(meaning, templates and containers too\)

It would be nice if the CLI could "pull" from an existing dotCMS install into a folder

### Acceptance Criteria

We need to start by recreating the legacy CLI functionality.

https://github.com/dotCMS/core/tree/master/tools/cli/commands

- content-type
- push-bundle
- push-content-types
- push-files
- push-lang
- push-site-contents
- push-sites
- site

### CLI commands should look like:

```bash
dotcli site --help

# Pull all site s(should default to all)
dotcli site pull

## writes file to demo.dotcms.com.site.json
dotcli site pull demo.dotcms.com

## push from demo.dotcms.com.site.json
dotcli site push demo.dotcms.com
```

Likely there will be some additional tweaks.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

*No response*

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

*No response*

### Assumptions & Initiation Needs

*No response*

### Sub-Tasks & Estimates

\`\``[tasklist]
- [ ] Need to document goals and requirements for "starting point", as well as outline what won't be included in first phase. @spbolton
- [ ] What Goes into CLI? Site Bootstrap? Export / Import of Site? @spbolton
- [ ] What Data Cleanup is Needed to Make the CLI Work? @spbolton
- [ ] https://github.com/dotCMS/core/issues/22672
- [ ] https://github.com/dotCMS/core/issues/22365
- [ ] https://github.com/dotCMS/core/issues/24042
- [ ] https://github.com/dotCMS/core/issues/24168
- [ ] https://github.com/dotCMS/core/issues/22545
`\`\`

**Comment by damen-dotcms** [comment]
Hey @fabrizzio-dotCMS & @wezell, I've updated this issue based on the conversation we just had. 

Next up I'll work with Fabrizzio to add some tasks with more details based on the legacy CLI features, and then we can discuss this more on the Wednesday call and call out any tweaks that need to be made as we're rebuilding this functionality with the new Java libraries.

Thanks!

**Comment by damen-dotcms** [comment]
Legacy CLI - https://www.dotcms.com/docs/latest/bash-cli

**Comment by damen-dotcms** [comment]
Hey @spbolton, 

Any update on this one?
