### ISSUE TITLE
Incorporate Swagger annotations to remaining endpoints

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#22659]
Extra Swagger annotations need to be added to a list of most-used endpoints.

Most-used endpoints: 

- [x] * Workflow fires (completed)
- [ ] * Rest of Workflow API endpoints (new card)
- [ ] * Page API (new card)
- [ ] * Content types (new card)
- [ ] * Content API querying / searching (new card)
- [ ] * Navigation API (new card)
- [ ] * Push publishing Bundles (new card)
