### ISSUE TITLE
Zapier Integration

### ISSUE THREAD

**Issue by jdotcms** [dotCMS/core#23301]
As an user in dotCMS I want to be able to integrate some events on the CMS to fire actions on other apps.

For instance when someone publish a contentlet we would like to notify the information in a slack channel.

Full Spec Sheet found [in google docs]( https://docs.google.com/document/d/1bUX9YYzmqNJc58x71jq4VuvKW7k8EoEKNgNk-rF3Aus/edit):

Also, we would like to have actions on Slack that perform on dotCMS 

Also, we would like to import/export contentlets from google sheets to dotCMS, etc

To achieve the goal we need to create on dotCMS a plugin that contains:

1. An actionlet that fires a generic event with the contentlet information + the user will be able to set a type flag to tell trigger what to do.

2. An endpoint that receives the events from the actions (from thirdparties) and perform things on dotCMS.

## Integrations Tested
- [x] Google Sheets  ---> Content
- [x] Content ---> Google Sheets
- [x] Google Docs ---> Content
- [x] Content ---> Google Docs
- [x] Content ---> Slack
- [x] Slack ---> Content
- [x] Content ---> Salesforce
- [x] Content ---> Hubspot

**Comment by jdotcms** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Lunik-61780f8ea7866b001141b588/issues/dotCMS/core/23301?planning-poker) with Zenhub @hmoreras @jcastro-dotcms @rjvelazco @fmontes

**Comment by wezell** [comment]
- [ ] Google Sheets  ---> Content
- [ ] Content ---> Google Sheets
- [ ] Google Docs ---> Content
- [ ] Content ---> Google Docs
- [ ] Content ---> Slack
- [ ] Slack ---> Content
- [ ] Content ---> Salesforce
- [ ] Content ---> Hubspot

**Comment by jdotcms** [comment]
All of those are done!

**Comment by fmontes** [comment]
5m video setting up one of the integrations
