### ISSUE TITLE
Unify dotCMS generated contentlet system-wide for efficient thumbnail generation

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23600]
### Parent Issue

#23599 

### Task

As a stakeholder, I want to unify the thumbnail generation process across the system to optimize server performance and prevent the generation of multiple images for different pages.

We are using the [RESTful Image Processing API](https://www.dotcms.com/codeshare/restful-image-processing) to generate the thumbnails. And this is good, but the issue is that there are varying thumbnail URLs used across different sections of the system. **This results in the generation of multiple thumbnails for the same image**, which can put a significant load on the server when there are many contentlets.

What we need to do is make sure that everywhere in the system that has a contentlet thumbnail, we use the same image URL for that to prevent the system from generating new images for different pages.

#### Web Component
We already have a [web component to render](https://github.com/dotCMS/core/blob/master/core-web/libs/dotcms-webcomponents/src/elements/dot-contentlet-thumbnail/dot-contentlet-thumbnail.tsx) the thumbnail image, we are just not using it everywhere.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria
Use the `dot-contentlet-thumbnail` in all the sections of the system where we need to render a contentlet thumbnail.

### Use the thumbnail web component in the following sections

- [x] Content search card view
- [x] Content search list view
- [x] Relationship field
- [x] Content palette
- [ ] Edit page > Adds contentlet
- [ ] Block editor (I think this is done, double check)
- [ ] WYSIWYG image search
- [ ] Add images field

**Comment by fmontes** [comment]
https://github.com/dotCMS/core/pull/25405/files

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
* Docker Image: `dotcms/dotcms:master_8d344c7_SNAPSHOT`

Thumbnails show up just like in the PR's description: https://github.com/dotCMS/core/pull/25405 , and the tests explained in there were verified in the Docker image as well.
