### ISSUE TITLE
Redesign the Author to Blog Post Relationship Builder

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#23690]
[![Screenshot_2022-12-28_17-09-38.png](https://mrkr.io/s/63ac7852d0e6d3b4ab948faf/2)](https://mrkr.io/s/63ac7852d0e6d3b4ab948faf/0)

1- "Title" is not necessary
2-"Relate" button should be placed on the right side
3- Too much padding for the "erase icon"
4- Add the last name
5-Is the language necessary in this table?

```[tasklist]
### Tasks
- [ ] Make the trash can cell `40px`
- [ ] Remove the bottom shadow in the table
```

---

**Reported by:** Melissa Rojas Rodríguez (melissa.rojas@dotcms.com)

**Source URL:** [https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries](https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/63ac7852d0e6d3b4ab948fb2_cc570da67a264055?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 108.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1440 x 821</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
Also the trash icon should be on the right side. (=

**Comment by fmontes** [comment]
We need to do this in the new edit contentlet.

**Comment by fmontes** [comment]
- [ ] Make the trash can cell `40px`
- [ ] Remove the bottom shadow in the table
