### ISSUE TITLE
Additional Text Formatting Options for the Block Editor 

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#23790]
### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### User Story

Customers need the ability to do additional in-line text formatting in the text block.

The clearest use case is the use of copyright and registered trademark characters, which are expected to be shown as superscript.  An alternative would be to show them in a smaller font.  But the text block doesn't allow either of these right now.

In addition, customers will need the ability to control which formatting options are available for a text block - in the same way they can control this for WYSIWYG fields now.

These limitations will force some customers to use the WYSIWYG field instead of the block editor field.  This, in turn, will make the content editing experience more difficult for non-technical users.

### Acceptance Criteria

* Enable content editors to format text as subscript and superscript inline.
* Enable content editors to increase and decrease font size inline.
* Enable content editors to use "justify" alignment for text lines.
* Enable content architects to enable and disable all text formatting options.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.slack.com/archives/C028Z3R2D/p1673464393091019?thread_ts=1673464258.008669&cid=C028Z3R2D

### Assumptions & Initiation Needs

The ability to customize what text formatting options are allowed in the WYSIWYG field is one of the features that new customers both use and appreciate when we provide training.

The lack of similar capabilities in the block editor means that customers have to choose between the easier-to-use interface of the block editor, vs. being able to control what types of formatting they allow their editors to be able to use in the field.

### Sub-Tasks

Add the following in-line text formatting options to the text block editor:
- [ ]     * Subscript
- [ ]     * Superscript
- [ ]     * Increase Font Size
- [ ]     * Decrease Font Size

- [ ] Add the "Justify" alignment option to the text block editor.

- [ ] Add a field variable

**Comment by damen-dotcms** [comment]
Closed in favor of #22171
