### ISSUE TITLE
Remove Experemient from LocalStorage when the lookBackWindows expires

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#23822]
### Proposed Objective

Core Improvement (Features)

### Proposed Priority

Priority 2 - Important

### User Story

When a User is into any Experiments we storage the Experiments's data  in the Browser Local Storage, we need to remove this data from the localStorage when the lookBackWindows is Expired and then the user is going to be able to get into a new Experiment.

Also we need change then isUserIncluded end point to include into the response the lookBackWindows Expire date

The LookBackWindows expire time is a attribute into the Experiment, for now we are not going to use a DEFAULT value and set it by hitting the End point directly.

### Acceptance Criteria

- The localStorage must be remove after the lookBackWindows Expire.
- Send the lookBackWindows expire date into the isUserInclude end point.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

We need to change this end point to include the lookBackWindow expire date:

https://github.com/dotCMS/core/blob/8020d73a157b521793c3e4b690f0132f3631a75b/dotCMS/src/main/java/com/dotcms/rest/api/v1/experiments/ExperimentsResource.java#L417

### Sub-Tasks

- [ ] Change the isUserInclude end point to add the lookBackWindow Expire date into the Reponse 

https://github.com/dotCMS/core/blob/8020d73a157b521793c3e4b690f0132f3631a75b/dotCMS/src/main/java/com/dotcms/rest/api/v1/experiments/ExperimentsResource.java#L417

- [ ] Change the Experiment JS Injected code to  clean the localStorage object when the lookBackWindow expire, also we need to change the object structure to include the Expire date.

https://github.com/dotCMS/core/blob/161cc995faa192a0104ba57f8e7c11272be1f18d/dotCMS/src/main/resources/experiment/js/init_script.js#L16-L15

- [] Maybe change the Experiment model to include a Default value to the lookBackWindow expire time.

**Comment by freddyucv** [comment]
**Passed Internal QA:**  it was tested with the follow steps:

1. dotCMS was started up with the full starter.
2. A Experiment was created in the blog/index page with a traffic location of 100%
3. The newly Experiment was started.
4. I used the Experimt ViewTool to Inject the Experiment code into the theme using: $!dotExperiment.code()
5. I Logged out and went to the Front end, check into the browser application tab if the experiment_date Object was created into the local Storage.
6. Set you local time 40 minutes foward and refresh the page, the exriment_data is removed because the lookBackWindows expire after 30 minutos.
7. Refresh the page again and the Experiement_data is created but now with a different lookBackWindow.

Right now we have a little bug here because we are skipping one session, just after the lookBackWindow is expire we are going to create a new issue for that

**Comment by bryanboza** [comment]
Fixed, tested on releaes-23.05 // Docker // FF
