### ISSUE TITLE
Research: Import remote blocks 

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#23856]
### Parent Issue

#21988 

### Task

- [x] Clone tiptap repo
- [x] Build a tiptap block
- [x] Upload the JavaScript for the block
- [x] Try to dynamic import into our block editor

### Proposed Objective

Core Features

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

Write a comment in the issues detailing:

1. Problems
2. Solutions if any
3. Conclusions on the approach
