### ISSUE TITLE
dotCMS Technical Audit

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24021]
### Parent Issue

NA

### Task

Thorough Code Audit to Document Technical Debt

Goal is to document known technical debt, and start making a plan to reduce problematic areas, including estimates.

- Sounds like Will and Steve have a really good understanding of what they would like to update. 
- Need to document issues and come up with an order of operations plan for what we’re going to try and address and what we’re going to put off until later.
- Good to identify what needs to be updated – things that are past end of life, or make our code hard to maintain.
- Also good to communicate what things will NOT be updated.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://docs.google.com/presentation/d/1gxAamjkPBKDk1bjcH3iR5TEikodhuWDjtBmmtmYojCo/edit#slide=id.g1e90581f500_0_132

### Sub-Tasks & Estimates

- [ ] Audit Front-end
- [ ] Audit Back-end
- [ ] Update Architecture Diagrams
- [ ] Provide List of all Languages, Frameworks, Libraries, and Plug-ins Used by dotCMS, along with version numbers and licenses
- [ ] Call out any that are past end of support
- [ ] Call out any that have unacceptable licensing
- [ ] Call out any that our team knows to be tedious, or difficult to work with.

**Comment by fmontes** [comment]
Some works had been done in this area:

1. Frontend DXP: https://docs.google.com/spreadsheets/d/14uQmN0Fu6cjWtgW7N5IcjtU5SAkIkrEGmdSMQYl4Vf4/edit#gid=0
2. Dojo to Angular: https://docs.google.com/spreadsheets/d/1V4oc6BL_lOKoJ1ptdgAPQ6zg6qpRlu4xNRzi4FBKvAA/edit#gid=1982117285
3. JavaScript SDK: https://docs.google.com/spreadsheets/d/1FfPZTYlz2r-d88Om8fv1RQrm6pcmQaL4ZLtmfaKRu3c/edit#gid=0

**Comment by damen-dotcms** [comment]
Hey @spbolton, We had this for Q1 2023... still on track?
