### ISSUE TITLE
Create a video's thumbnail component

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#24040]
### User Story

As a user, I want to be able to preview video thumbnails, so I can see what video I'm going to choose.

### Acceptance Criteria

- [x] Create a component (in the web-component library) that allows you to display the video's thumbnail.
- [x] Make sure the component is responsive.
- [x] Allow users to disable the video thumbnails with a `SHOW_VIDEO_THUMBNAIL=false` dotmatketing property.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

We have to make sure that the component accepts the width and height as parameters.

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by fmontes** [comment]
Vertical videos do a bad resize for the card.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/751424/218569138-da8bd0f3-99f8-4b65-94aa-59937b17589e.png">

**Comment by rjvelazco** [comment]
PR: https://github.com/dotCMS/core/pull/24097

**Comment by fmontes** [comment]
Let's add this behind in a dotmarketing property.

**Comment by jcastro-dotcms** [comment]
### INTERNAL QA: PASSED
By default, video thumbnails are being generated now. The steps to reproduce are the following:

1. Do a simple screen recording. In Mac, just hit CMD + shift + 5 to record your screen or parts of it.
2. Go to the **Content Search** portlet, and upload the video as a File Asset.
3. Go back to the **Content Search**, and change the view from `List` to `Grid` -- top-left corner of the portlet.
4. Your video's thumbnail must show up.

**Comment by josemejias07** [comment]
**Approved QA** - Tested on **23.03_5108019d_SNAPSHOT** // Docker // macOS 13.0 // FF v110.0
