### ISSUE TITLE
In-Context Links to Product Documentation

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24078]
### User Story

As a user of dotCMS, I want to be able to find relevant documentation so I can get more use out of the platform.

Could take a variety of shapes... from help baked into drop-downs, or info buttons, to Pendo, to Intercom.

Here's an example from GitHub. I think this is really smart. https://github.com/dotCMS/core/issues

<img width="322" alt="Screenshot_2023-02-09_at_4_09_06_PM" src="https://user-images.githubusercontent.com/114953617/217953740-4aafad7d-3fb4-4c8c-936b-fa3cc0e342d7.png">

### Acceptance Criteria

* Need to think about what would be the easiest way to add support links, and where to add them.
* I suspect starting with just some links will be good.
* Need to allow admins to disable this feature.
* Need to disable itself if dotCMS content is blocked by customer.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Or maybe it's little cards that pop up when you get to certain pages that have links to support... until you check the, "I'm tired of seeing this" box and then the cards go away until the next release. https://primeng.org/card

Just for brainstorming... I know we had talked about a few tools in the past as well. Pendo has some great in-app training, but it was expensive and seemed like a fairly heavy lift to get it added (and get that service white labeled across all customers instances).

https://www.pendo.io/product/in-app-guides/

https://www.intercom.com/

### Sub-Tasks & Estimates

```[tasklist]
### Tasks
- [ ] Identify UX Components we could use to insert documentation and support content; goal is do do this with minimal design changes. 
- [ ] Identify existing content we want to include & where to include it.
- [ ] Identify places where content needs to be created.
```

**Comment by damen-dotcms** [comment]
Hey @jdcmsd , can you think of any places where you would like to have some in-context links to the documentation? Love your input here.
