### ISSUE TITLE
In-Applicaiton Update Notifications

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24080]
### User Story

As a user, I want to know what new features dotCMS has build so I can get more excited about the upgrade process.

### Acceptance Criteria

- Thinking something sort of like how the browsers, or Slack / Discord, or Spotify, or a ton of other applications use where we show a notification "present" indicating that a new update is available.
- A list of content would be ideal, we could show links to the marketing articles about new features, or simply updates to existing features that we wanted to promote.
- Would have to be aware of "New" relative the version of dotCMS the user was on, and also "New" relative to the last time the user logged in.
- Maybe it's persistent... and lasts until a user "dismisses" the notifications. Need UX Input.
- Ideally it would also show after an upgrade, to let a user know about all the things they got with the upgrade.
- Would need to disable itself if the customer had blocked external content from dotCMS.
- Would need to be able to be disabled by the admins / users.

<img width="434" alt="Screenshot 2023-02-09 at 5 32 29 PM" src="https://user-images.githubusercontent.com/114953617/217962806-6a3c1180-73fb-4b4e-9ca4-efac5a811ed3.png">

### Proposed Objective

Marketing

### Proposed Priority

Priority 3 - Average

```[tasklist]
### Tasks
- [ ] Need to come up with UX Design; likely need some sort of persistent notification spot with some sort of badge or color dot indicating when something new was new for the user.
- [ ] Need to create a place to store that content, and serve it out from a feed.
- [ ] Need to create the logic for when to show based on when the user last logged in, and how to show content after an upgrade.
```
