### ISSUE TITLE
Research Angular Gridstack library for layout editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24095]
### Parent Issue

N/A

### Task

We need to find out if the library [Angular Gridster 2](https://github.com/tiberiuzuld/angular-gridster2) will work with our layout editor.

We need to create a POC with:

- [x] User can create rows
- [x] User can add boxes to the rows
- [x] Boxes can be resized
- [x] Boxes can be resized, but it should not push other boxes
- [x] Allow user to add offset between boxes
- [x] User can move boxes from one to another
- [x] When user move boxes from row to row, it should autoscroll
- [x] User should move rows up and down

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [x] Test the library
- [x] Do a POC
- [x] Create a report with:
    - Can work?
    - Trade off
    - Implementation effort

**Comment by fmontes** [comment]
# Report

1. Gridster 2 library didn't work (no nested grids for rows)
2. We use "gridstack"

## GridStack
Is a JavaScript library, it does have some Angular component but we might want to create our own angular elements, maybe directive.

1. Is more configurable and extensible
2. It has nested grids for rows
3. The repo seems [active](https://github.com/gridstack/gridstack.js/commits/master)
4. Altho, the maintainer said it don't have much time
5. [MIT license](https://github.com/gridstack/gridstack.js/blob/master/LICENSE)

## Conclusion

1. Is safe to use
2. I recommend do our own angular implementation because our use case is very specific
3. We need to tests performance with a lot of content


## Demo code


```TypeScript
import { GridStack, GridStackOptions, GridStackWidget } from 'gridstack';
import './style.css';
import 'gridstack/dist/gridstack.min.css';

let sub1: GridStackWidget[] = [
  { x: 0, y: 0, w: 6 },
  { x: 6, y: 0, w: 6 },
  
];

let sub2: GridStackWidget[] = [
  { x: 0, y: 0, w: 4 },
  { x: 4, y: 0, w: 4 },
  { x: 8, y: 0, w: 4 },
];

let sub3: GridStackWidget[] = [
];

let subOptions: GridStackOptions = {
  cellHeight: 85,
  column: 'auto', // size to match container. make sure to include gridstack-extra.min.css
  itemClass: 'sub', // style sub items differently and use to prevent dragging in/out
  acceptWidgets: '.grid-stack-item.sub', // only pink sub items can be inserted
  margin: 2,
  minRow: 1, // don't collapse when empty
  maxRow: 1,
};
let options: GridStackOptions = {
  // main grid options
  cellHeight: 100,
  margin: 5,
  minRow: 1, // don't collapse when empty
  id: 'main',
  children: [
    { x: 1, w: 12, h: 1, subGrid: { children: sub1, class: 'sub1', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 1, subGrid: { children: sub2, class: 'sub2', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
    { x: 1, w: 12, h: 1, y: 2, subGrid: { children: sub3, class: 'sub3', ...subOptions } },
  ],
};


GridStack.addGrid(document.querySelector('#builder') as HTMLElement, options);
```
