### ISSUE TITLE
Implement Redisson Session sharing

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24294]
### Parent Issue

CI/CD

### Task

In order to be able to transparently scale our dotCMS installations up and down, we need to implement Session Replication in our Tomcat instance.  To do this, we need to do a few things:
- [x] Decide whether to use Redisson or implement our own solution.
- [x] Add library library to our tomcat install
- [x] Add library conf to our tomcat install (we should be able to use ENV variables to set values here)
- [x] #24291

Redis Session Management plugin: https://github.com/dotCMS/tomcat-redis-session-manager

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by bryanboza** [comment]
Fixed tested starting dotCMS using redis as a session storage and now it is working as expected. Tested using the provided example.
