### ISSUE TITLE
UX Alignment : Data Tables

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24312]
### Task

Now that we have a new Data Tables Component Design, we need to make sure it's applied consistently inside of dotCMS. Let's start with just the "Top Level" pages from the left-hand navigation.

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Here's a partial list of places that use the data table component.

Using the demo site... it's basically every "top level" page in the left nav bar that has a data table. Note... some are defaulted to "grid" view but still have data table options.

- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Activities
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Banners
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Blog-Entries
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Call-To-Action
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Destinations
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Events
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Products
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Rich-Text
- [ ] https://demo.dotcms.com/dotAdmin/#/c/content
- [ ] https://demo.dotcms.com/dotAdmin/#/c/site-browser
- [ ] https://demo.dotcms.com/dotAdmin/#/templates
- [ ] https://demo.dotcms.com/dotAdmin/#/c/containers
- [ ] https://demo.dotcms.com/dotAdmin/#/c/publishing-queue
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Images 
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Videos
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_PDFs
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Files
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Personas
- [ ] https://demo.dotcms.com/dotAdmin/#/forms
- [ ] https://demo.dotcms.com/dotAdmin/#/c/c_Landing-Pages
- [ ] https://demo.dotcms.com/dotAdmin/#/c/vanity-urls
- [ ] https://demo.dotcms.com/dotAdmin/#/content-types-angular
- [ ] https://demo.dotcms.com/dotAdmin/#/c/tags
- [ ] https://demo.dotcms.com/dotAdmin/#/c/categories
- [ ] https://demo.dotcms.com/dotAdmin/#/c/languages
- [ ] https://demo.dotcms.com/dotAdmin/#/c/site-search
- [ ] https://demo.dotcms.com/dotAdmin/#/c/dynamic-plugins
- [ ] https://demo.dotcms.com/dotAdmin/#/c/users
- [ ] https://demo.dotcms.com/dotAdmin/#/c/sites
- [ ] https://demo.dotcms.com/dotAdmin/#/c/roles
- [ ] https://demo.dotcms.com/dotAdmin/#/c/configuration (Licensing Tab)
- [ ] https://demo.dotcms.com/dotAdmin/#/c/maintenance (Various)

I'm sure this is not a complete list, but even having these cleaned up with consistent fonts and spacing would be huge!

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Quite a few varieties of data tables!

![image](https://user-images.githubusercontent.com/114953617/223587997-9449209b-375f-455b-98bf-5e8641d56581.png)

![image](https://user-images.githubusercontent.com/114953617/223588036-37697a6d-33fb-41c5-bcbe-dd97f2f6c3dd.png)

![image](https://user-images.githubusercontent.com/114953617/223588118-610139bd-2c40-4e8a-8687-411b4196fd9e.png)

![image](https://user-images.githubusercontent.com/114953617/223588168-61462e86-6f09-4124-b0dc-e4183a210d1f.png)

![image](https://user-images.githubusercontent.com/114953617/223588770-3792ffa0-2f96-4d42-b632-ca02b160e5d6.png)

### Sub-Tasks & Estimates

Likely these other issues are duplicates of this task, but let's track them to make sure.

```[tasklist]
### Tasks
- [ ] Provide Consistent Design for Data Tables @Melissa-dotCMS 
- [ ] Sanity Check Table List in Acceptance Criteria; Likely we can Programmatically Search for Data Tables @fmontes 
- [ ] https://github.com/dotCMS/core/issues/24129
- [ ] https://github.com/dotCMS/core/issues/24130
- [ ] https://github.com/dotCMS/core/issues/24131
- [ ] https://github.com/dotCMS/core/issues/23966
- [ ] https://github.com/dotCMS/core/issues/24058
- [ ] https://github.com/dotCMS/core/issues/24060
- [ ] https://github.com/dotCMS/core/issues/23832
- [ ] https://github.com/dotCMS/core/issues/23831
- [ ] https://github.com/dotCMS/core/issues/23772
- [ ] https://github.com/dotCMS/core/issues/23829
```

**Comment by damen-dotcms** [comment]
Hey @Melissa-dotCMS ,

We will need to make sure we have a grid view vs. a list view for this component.

An example. https://demo.dotcms.com/dotAdmin/#/c/c_Call-To-Action

![image](https://user-images.githubusercontent.com/114953617/223592299-d8b9bc45-20d0-44c2-b8ca-06197fae3a05.png)

![image](https://user-images.githubusercontent.com/114953617/223592358-a4fbf782-7dd9-4bf6-bb34-32c1b04bc663.png)

**Comment by damen-dotcms** [comment]
Hey @Melissa-dotCMS ,

We also need to make sure we have a "Right Click Menu" for items in the table. Currently we have few to choose from.

Suggest making sure the menu is the same between List View and Grid View.

I don't love "Right Click" on the web, but we use it a lot of places... the trouble is we don't use it consistently a lot of places either. There's no "standard" between our data tables... I'd say 50% don't use it at all.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/114953617/223592448-4a693333-403e-4fed-a77e-ad05a6a851f2.png">

<img width="139" alt="image" src="https://user-images.githubusercontent.com/114953617/223592484-a2d5a8ce-63f0-41f4-a365-fb7064d576a7.png">

<img width="150" alt="image" src="https://user-images.githubusercontent.com/114953617/223592590-0fd187a8-b217-4812-9171-d29746e47791.png">

<img width="236" alt="image" src="https://user-images.githubusercontent.com/114953617/223592642-bc934a72-5773-44eb-aefb-cd517355b9f6.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/114953617/223592911-7e373276-4915-4cad-9b14-16dc804e5109.png">

**Comment by Melissa-dotCMS** [comment]
**You can see the re-design here:**
https://www.figma.com/file/1pZBoBlMAI8xYFFIbbj5Mg/Components-Library?node-id=1602%3A7447&t=E2KhluDIS6YeuA3J-1
