### ISSUE TITLE
UX Alignment : Modals

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24319]
### Task

We need to makes sure we're using Modals consistently throughout dotCMS.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

```[tasklist]
### Tasks
- [ ] Create Consistent Design for Modals
- [ ] Create Usage Guidelines for Modals
- [ ] Generate List of Places in dotCMS that use Modals
- [ ] https://github.com/dotCMS/core/issues/23711
- [ ] https://github.com/dotCMS/core/issues/23941
- [ ] https://github.com/dotCMS/core/issues/24110
- [ ] https://github.com/dotCMS/core/issues/24121
- [ ] https://github.com/dotCMS/core/issues/24108
```
