### ISSUE TITLE
UX Alignment : Forms

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24318]
### Task

We need to start making sure that all Forms in dotCMS match UX guidelines.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Forms Labels, Form Fields, Form Notifications (Error & Success Messages), Helper Text, and Buttons all need to be consistent throughout the application.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Related : https://github.com/dotCMS/core/issues/24320

### Sub-Tasks & Estimates

There may be other tasks here; this was just what I could find in GitHub for now.

We'll also still need to identify all the places that need the the new designs applied.

```[tasklist]
### Forms Fields
- [ ] Create Consistent Design for Forms
- [ ] Create Usage Style Guidelines for Forms
- [ ] Generate List of Places in dotCMS that use Forms
- [ ] https://github.com/dotCMS/core/issues/23634
- [ ] https://github.com/dotCMS/core/issues/23680
- [ ] https://github.com/dotCMS/core/issues/23635
- [ ] https://github.com/dotCMS/core/issues/23642
- [ ] https://github.com/dotCMS/core/issues/23677
- [ ] https://github.com/dotCMS/core/issues/23690
- [ ] https://github.com/dotCMS/core/issues/23711
- [ ] https://github.com/dotCMS/core/issues/24069
- [ ] https://github.com/dotCMS/core/issues/24128
- [ ] https://github.com/dotCMS/core/issues/24129
- [ ] https://github.com/dotCMS/core/issues/23836
- [ ] https://github.com/dotCMS/core/issues/23828
- [ ] https://github.com/dotCMS/core/issues/23827
- [ ] https://github.com/dotCMS/core/issues/23826
```

```[tasklist]
### Buttons
- [ ] https://github.com/dotCMS/core/issues/23639
- [ ] https://github.com/dotCMS/core/issues/23676
- [ ] https://github.com/dotCMS/core/issues/23715
- [ ] https://github.com/dotCMS/core/issues/24090
- [ ] https://github.com/dotCMS/core/issues/23715
```

```[tasklist]
### Form Responses (Error & Success Messages)
- [ ] https://github.com/dotCMS/core/issues/24127
- [ ] https://github.com/dotCMS/core/issues/24127
- [ ] https://github.com/dotCMS/core/issues/24100
- [ ] https://github.com/dotCMS/core/issues/24108
- [ ] https://github.com/dotCMS/core/issues/24066
```

```[tasklist]
### Helper Text
- [ ] Generate List of Places in dotCMS that use Helper Helper Text	
```

```[tasklist]
### Chips
- [ ] Generate List of Places in dotCMS that use Chips
```
