### ISSUE TITLE
UX Alignment : File Browse / Upload Interface

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24320]
### Task

Need to make sure we have consistent "Upload a File" functionality.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

```[tasklist]
### Tasks
- [ ] Create Consistent Design for File Browse / Upload Interface
- [ ] Generate List of Places in dotCMS that use File Browse / Upload Interface
- [ ] https://github.com/dotCMS/core/issues/23713
- [ ] https://github.com/dotCMS/core/issues/23712
```
