### ISSUE TITLE
Favorite Pages Portlet Punchlist

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24326]
### Parent Issue

#22343

### Task

Punchlist for Pages Portlet / Favorites

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates
- [x] Listing Page - Language dropdown should have a min-width of 175px so it does not jump in most cases.
- [x] Adding a Favorite - the url should be editable (maybe we update the thumbnail when changed?)
- [x] Listing Page - When editing a content from the listing page and then closing it, we should not leave the pages portlet.
- [x] Listing Page - remove the skeletons in the empty favorite window, it looks too busy  **(design needed)**
- [x] Listing Page - If there are no favorites, the favorites accordion should default to closed.
- [x] Listing Page - Clicking anywhere on the favorites accordion bar should open the favorites accordion.
- [x] Listing Page - Search box should be ~ 250px (bigger than the language drop down by default).
- [x] Add/Edit Favorites - Center screenshot spinner vertically and make the background of the image box a super light gray, e.g. `#f1f1f1`.
- [x] Listing Page - listing needs to refresh when any content action is performed.  If I publish/unpublish content I do not see it reflected. 
- [x] The empty favorites listing is not centered:
![Screen Shot 2023-03-09 at 1 37 00 PM](https://user-images.githubusercontent.com/934364/224123120-2a1a6273-0988-4375-ad85-4755108b4925.png)
- [x] #24438
- [x] Show archived not working - at least when I archive a blog and check "show archived", nothing shows up. https://github.com/dotCMS/core/issues/24561
- [x] Adding a Favorite - We should allow a user to save a favorite without a thumbnail.  Otherwise it impossible to save a favorite if the thumbnail can't be generated.  Maybe the save button activates after 5 seconds no matter what. **(design needed)** related to task: 24496
    - [x] #24496
- [x] #24442
- [x] [Listing Page - When you click a page to preview, we are going to need a spinner (or spinning cursor, something) or something that shows things are "happening". We do this on the browser when you double click on a page to go to edit mode. **(design needed)**](https://github.com/dotCMS/core/issues/24578)
- [x] #24604
- [x] #24887
- [x] #24911
- [x] #24767
