### ISSUE TITLE
Improve Authenticaiton Security

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#24329]
### User Story

As someone who cares about security, I want dotCMs to support 2FA so I can sleep at night.

### Acceptance Criteria

From Mehdi's security presentation.

- [ ] Need Support for 2FA
- [ ] Password Length Check
- [ ] Password "Strength" Check (Note, "Strong" does not mean silly complicated. No need for capital letters or funny characters, a long pass phrase is better. Will suggested using a bloom filter to check against common passwords, but also Mehdi said we would need to not allow passwords a user used in the past.)
- [ ] Ensure Log In Throttling is Setup Correctly; suggest after 3 attempts (Fibonacci Sequence 1,1,2,3,5,8,13,21... of minutes seems to work)
- [ ] Ability to set password expiration time for organization.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Complete Java lib to implement TOTP, from the QR code to auth to the recovery codes:
https://github.com/samdjstevens/java-totp#generating-a-qr-code

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/114953617/224104331-bf689643-f24f-4dec-b319-4b94d6d63b50.png">

### Sub-Tasks & Estimates

```[tasklist]
### Tasks
- [ ] Finish Gathering Requirements @damen-dotcms
- [ ] Need designs for screens to add 2FA.
- [ ] Need designs for screens to enable / require 2FA in the organization.
```
