### ISSUE TITLE
[UI] Improving Experiments Configuration UI/UX

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24343]
### Parent Issue

https://github.com/dotCMS/core/issues/22455

### User Story

Not apply.

### Acceptance Criteria

Not apply.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

- [x] #24430
- [x] #24431
- [x] #24419
- [x] #24447
- [x] #24456
- [x] #24457
- [x] #24541
- [x] #24546
- [x] #24583
- [x] #24585
- [x] #24651
- [x] #24670
- [x] #24748
- [x] Remove scrolls from List Experiments tables
- [x] Handle errors in Experiment Reports of the result endpoint (stuck in loading state).
- [x] #24752
- [x] In the experiment listing, go straight to the Experiment Reports when the status is running or ended, and add a cog icon to go to the configuration
- [x] #24948
- [x] #24940
- [x] #24971
- [x] #25000
- [x] #25092 
- [x] #25108
- [x] #25053
- [x] #25122
- [x] #25130

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/25239
- [ ] https://github.com/dotCMS/core/issues/25692
- [ ] https://github.com/dotCMS/core/issues/25693
- [ ] #25623
- [ ] #25627
- [ ] #25637
- [ ] #25688
- [ ] #25689
- [ ] https://github.com/dotCMS/core/issues/25645
- [ ] https://github.com/dotCMS/core/issues/25722
- [ ] https://github.com/dotCMS/core/issues/25771
- [ ] https://github.com/dotCMS/core/issues/25764
- [ ] https://github.com/dotCMS/core/issues/25766
- [ ] https://github.com/dotCMS/core/issues/25769
- [ ] https://github.com/dotCMS/core/issues/25772
- [ ] https://github.com/dotCMS/core/issues/25773
- [ ] https://github.com/dotCMS/core/issues/25774
- [ ] https://github.com/dotCMS/core/issues/25876
- [ ] https://github.com/dotCMS/core/issues/25894
- [ ] https://github.com/dotCMS/core/issues/26022
```
