### ISSUE TITLE
Implement the UI for create files using code

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24362]
### Parent Issue

#23603

### User Story

As a user, I want to be able to create code file easily.

VTL files are widely used in dotCMS and the only way to create one is to create one with a code editor and then upload it.

### Acceptance Criteria

- [ ] Implement the design provided

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

The "backend" of this was done in this issue #23603 and in this PR: #24267  

- [Figma file](https://www.figma.com/file/mFPPOVeafZ931xjbXiZHCA/Issues-re-designs?node-id=459%3A3929&t=Qs28cx5PbKKdp5LG-1)
- [Figma Prototype](https://www.figma.com/file/mFPPOVeafZ931xjbXiZHCA/Issues-re-designs?node-id=459%3A3929&t=Qs28cx5PbKKdp5LG-1)

https://user-images.githubusercontent.com/751424/225710514-f34529a1-a309-4b9d-8312-a6044be69632.mp4

### Assumptions & Initiation Needs

1. This is a "Binary" field, so it should work in all content types with a Binary Field
2. We already have a Web Component that does drag and drop [here](https://github.com/dotCMS/core/tree/master/core-web/libs/dotcms-webcomponents/src/components/dot-asset-drop-zone). Let's see how much we can reuse for this.
3. We are using that web component in the content search screen, you can try by drag and drop a file in the content search screen

### Sub-Tasks & Estimates

- [ ] https://github.com/dotCMS/core/issues/25781
- [ ] https://github.com/dotCMS/core/issues/25782

**Comment by fmontes** [comment]
In the freezer until we figure it out web component for binary and file field.

**Comment by fmontes** [comment]
We are doing this with this: https://github.com/dotCMS/core/issues/25434

**Comment by rjvelazco** [comment]
To achieve this, we are going to create a library called `dotcms-fields` and a `dotcms-fields-builder` app. The implementation of this approach was thoroughly investigated and documented in this ticket https://github.com/dotCMS/core/issues/25434 and PR: https://github.com/dotCMS/core/pull/25581

**Comment by rjvelazco** [comment]
This ticket was moved to this one: https://github.com/dotCMS/core/issues/26045 and fixed in this PR: https://github.com/dotCMS/core/pull/26433
