### ISSUE TITLE
Research: Create Angular standalone components as web components

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24407]
### Task

- [ ] Generate at least two web components out of Angular Standalone Components
- [ ] Use Nx apps
- [ ] Check if we can build the web components in separate files
- [ ] Check the file size

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### Why?

Currently, we need UI components that can be used in `.jsp` files but that can also be ported to Angular when the time comes, and we don't lose that work.

The only way the Web Platform allows you to use UI components within different JavaScript frameworks is by using web components.

To create Web Components we use a library named Stencil, which is ok, but it will be way better if we can use Angular Components, so we can use PrimeNG components, and we don't have to learn, code and maintain another library.

There is an Angular library `@angular/elements` that allows you to create Web Components out of Angular Components, them problem is that the result code it was too big.

I think that with the introduction of Angular Standalone Components, we can generate smaller Web Components, so let's try that.

**Comment by fmontes** [comment]
Angular still not there.
