### ISSUE TITLE
chore(core): Unify all the upload file services

### ISSUE THREAD

**Issue by rjvelazco** [dotCMS/core#24428]
### Task

We have multiple `dot-upload-file` services. All those services have the same purpose and repeat the same logic. We need to create a single service to upload files/assets to dotCMS and it can be used in the different libraries we have.

- [ ] Delete [field elements dot-upload.service.ts ](https://github.com/dotCMS/core/blob/710604731c8a836564962d696cfbf43c06e88157/core-web/libs/dotcms-field-elements/src/components/dot-form/services/dot-upload.service.ts)
- [ ] Delete [web-componentes dot-upload.service.ts ](https://github.com/dotCMS/core/blob/710604731c8a836564962d696cfbf43c06e88157/core-web/libs/dotcms-webcomponents/src/components/contenttypes-fields/dot-form/services/dot-upload.service.ts)
- [ ] Create a high-level `dot-upload.service.ts` that can be shared over the libs.

### Proposed Objective

Application Performance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The new service must be able to be used both in `dotcms-ui` and in libraries that do not use `Angular`.
