### ISSUE TITLE
[UI] Limit variant to 2 & remove description if empty  & pre-fill goal name

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24456]
### Parent Issue

#24343

### User Story

- [x] Limit the MAX_VARIANTS_ALLOWED to 2
- [x] Remove description if empty
- [x] Pre-fill Goal name with `Primary Goal`
 
### Acceptance Criteria

- Experiments should support only one variant. 
- If the description is empty the container should be hidden and don't show an empty container.
- When creating a Goal, the name should be pre-filled with `Primary Goal`

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

**Comment by dsilvam** [comment]
Needs work: Pre-filling the Goal name should be based on the selection: Bounce Rate vs Reach Page

**Comment by dsilvam** [comment]
Passed Internal QA: Pre filling goal name based on selected Goal

**Comment by bryanboza** [comment]
Fixed, tested on release-23.06 // Docker // FF
