### ISSUE TITLE
Add OpenRewrite

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#24574]
### Parent Issue

None.

### User Story

Openrewrite lets us make cross codebase rule based changes to safety update our codebase and also allow for structured updates and patches of downstream projects like plugins. 

### Proposed Objective

Technical Debt

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* Introduction to OpenRewrite - OpenRewrite | https://docs.openrewrite.org/

### Sub-Tasks & Estimates

```[tasklist]
### Tasks
- [ ] Figure out what OpenRewrite recipes to include
- [ ] Run OpenRewrite on some portion of our Java code, then merge it in to see if it breaks any tests or if we can identify any issues
- [ ] Resolve issues with OpenRewrite; document fixes as part of best practices
- [ ] Update Development Team Documentation
- [ ] Roll OpenRewrite out to Java Devs
```
