### ISSUE TITLE
dotCMS CLI: Implement files command 

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24732]
### Parent Issue

#24753

### User Story

As a user, I want to be able to use a command called "files" with several operations: pull, push, ls, and tree. This will allow me to easily manage files and folders from the command line.

When I enter the "files" command followed by an operation, I expect to be prompted for any necessary input, such as the source and destination of the files to be pulled or pushed.

The "pull" operation should allow me to download a file or folder from a remote server to my local machine. I should be able to specify the location of the remote file or folder, as well as the location on my local machine where it should be saved.

The "push" operation should allow me to upload a file or folder from my local machine to a remote server. I should be able to specify the location of the local file or folder, as well as the location on the remote server where it should be saved.

The "ls" operation should allow me to list the files and folders within a specified directory, similar to the "ls" command in a terminal.

The "tree" operation should allow me to display the directory structure of a specified directory in a tree-like format, similar to the "tree" command in a terminal.

Overall, my goal is to be able to easily manage files and folders from the command line using a single, convenient "files" command with multiple operations.

### Acceptance Criteria

- [ ] The "files" command should be available in the command line interface.
- [ ] The "files" command should accept one of four operations: "pull", "push", "ls", or "tree".
- [ ] All the operations should get the info from the endpoint implemented [here](https://github.com/dotCMS/core/issues/24730) 

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Sub-Tasks & Estimates

- #24731
- #24733
- #24737
