### ISSUE TITLE
Prep Favorite Pages for release

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#24754]
### Parent
#22343 

### Task

We need to prep the pages/favorites portlet for release.  To do this, we need to 

- [ ] Add the pages portlet to the portlet.xml
- [ ] Set the feature flag to true
- [ ] Add pages to the starter, the blank starter and the minimal starter ABOVE the browser portlet.

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important
