### ISSUE TITLE
[UI] Connect the Summary component with the correct Winner and User Sessions value

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#24815]
### Parent Issue
#23625

### User Story
As a user, I want to see the winner of an Experiment and the number of experiment sessions.

### Acceptance Criteria
- Show, depending on the result of the Bayesian transform, a user-friendly status
- show the number of sessions of the experiment

### dotCMS Version
master

### Sub-Tasks & Estimates
- [x] Show the number of user sessions
- [x] Show the status of the winner (Bayesian)
- [x] Remove the component from Experiment Configuration

**Comment by dsilvam** [comment]
For now this only contemplates the session to date, since the UI for the winner/winning variant will change.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
