### ISSUE TITLE
Template builder: Research on Angular + GridStack integration

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#24820]
### Parent Issue

#24535 

### Task

Do some POC and research on how to implement GridStack with Angular for our use case.

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- [ ] We need grids (for rows) and subgrids (for boxes)
- [ ] We need to be able to add an Angular component to the subgrid. This component will give us the containers id and classes
- [ ] We need to find a way to get the combined data from gridstack and our custom components to send to the server
- [ ] We need to be able to get the data from the server and render gridstack and the custom comppnent
- [ ] We need to implement state management here
- [ ] Code should be testable, stable and robust

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

GridStack provides integration Angular examples in [their repo](https://github.com/gridstack/gridstack.js/tree/master/demo/angular), different ways to implement it.

Here is the POC we implemented with vanilla JavaScript: https://github.com/dotCMS/core/files/11128214/template-builder.zip
