### ISSUE TITLE
CLI: Create a GHA to build and release the cli

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#24968]
### Parent Issue

#24753

### User Story

As a user \(java and js developer\), I'd like to have an easy way to install/update the latest version of dotCMS CLI. Ideally, it should be a one-step command.

To accomplish it, we might want to check out how Quarkus releases its cli versions https://quarkus.io/guides/cli-tooling \(JBang, Homebrew, etc\). [This repo](https://github.com/quarkusio/quarkus/tree/main/devtools/cli/distribution) contains the scripts used by Quarkus and [this](https://github.com/quarkusio/quarkus/blob/main/devtools/cli/distribution/release-cli.sh) is the release script.

JReleaser could help us to accomplish it. These are some links that might be helpful:
- JReleaser site: https://jreleaser.org/
- Quarkus CLI assembled with JLink and distributed with JRelease: https://jreleaser.org/guide/latest/examples/jlink/quarkus-cli-app-jlink.html
- Quarkus CLI assembled using a quarkus native image and released with JRelease: https://jreleaser.org/guide/latest/examples/native-image/quarkus-cli-app.html

### Acceptance Criteria

Install dotCMS CLI with one-step command line

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

*No response*

### Assumptions & Initiation Needs

*No response*

### Quality Assurance Notes & Workarounds

*No response*

### Sub-Tasks & Estimates

*No response*
\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/25950
- [ ] https://github.com/dotCMS/core/issues/25951
- [ ] https://github.com/dotCMS/core/issues/26189
- [ ] https://github.com/dotCMS/core/issues/26279
- [ ] https://github.com/dotCMS/core/issues/26500
- [ ] https://github.com/dotCMS/core/issues/26917
- [ ] https://github.com/dotCMS/core/issues/26918
`\`\`
