### ISSUE TITLE
[UI] Move Experiments to a Lib at the Monorepo

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#25027]
### User Story

As a Developer, I want to centralize all Experiment Portlet to an Angular Lib at Nx Workspace, so I can separate all the functionalities from the main application. This helps us to migrate from Karma to Jest Unit Test task runner.

### Acceptance Criteria

Up and running without problem:
- Lint task
- Test task
- Build task

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### Sub-Tasks & Estimates

- [x] Move the portlet to a lib
- [ ] Migrate all the tests to Jest.
- [ ] Set the reporters
- [ ] Verify the pipelines
