### ISSUE TITLE
Move to Maven Epic

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#25089]
### Move to Maven Epic Task to track progress

- [x] Unify dependency management #25030 
- [x] Build Tika Plugins in mvn #25030 
- [x] local test and build running in mvn
- [x] #25459
- [x] Mvn github action for build and integration test 
- [x] Remove gradle unit and integration test reporting
- [x] Test Publish maven artifacts
- [x] #26049
- [x] Postman Tests against docker build
- [x] Disable Gradle Github Actions
- [x] Developer maven workshop
- [x] Ensure validation processes enabled, OpenRewrite, source cleanup
- [x] Maven Release Process and Release Numbering in Trunk-Based Development Model
- [x] Plugin migration example
- [x] Plugin migration ( could be an as-needed process )
- [x] Maven build documentation and information for customers
- [x] Switch over review and sign off
- [x] Cleanup : Code relocation ( move sources to maven module e.g. integration test sources)
- [x] Cleanup : Remove any old files/folders that are no longer used

### Proposed Objective

Application Performance

### Proposed Priority

Priority 2 - Important

**Comment by wezell** [comment]
done and done!
