### ISSUE TITLE
Build New Custom Tab Navigation Button & Menu

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25281]
### Task

Need to build a new custom tab navigation drop-down component, and menu.

See designs under "External Links."

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- [x] Behavior notes… if there are “User Defined” Devices, we’ll show 3 columns. If there are no "User Defined" Devices, we'll just show 2.

 - [ ] If the user has the ability to add content, we’ll also show them the “Add Device” link that will take them to the Content Search view for "Device".

<img width="623" alt="image" src="https://github.com/dotCMS/core/assets/114953617/a19d5c7c-2a6d-4350-8e81-2bcf0c12e635">

- [ ] Remove Legacy “Device” Preview Menu. We’re merging that functionality into the Preview Tab.

<img width="614" alt="image" src="https://github.com/dotCMS/core/assets/114953617/92221681-115f-48c4-ab44-8018b8a89a7e">

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Demo - https://www.figma.com/proto/jyu7b1wgL16iV7yOoNdgu9/SEO?page-id=1%3A65&type=design&node-id=372-9191&viewport=-1440%2C-118%2C0.37&scaling=scale-down&starting-point-node-id=372%3A9190

Menu - https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=428-13077&t=9Qcws8is2LP5BkgC-0

**Comment by nollymar** [comment]
**New update and Note to QA:** The `+` icon in the device modal should be available for users with CMS admin role only

**Comment by nollymar** [comment]
**Internal QA:** Needs work

The plus `+` icon is shown when I log in with a non-CMS admin user. Even when I can't add a new device with that user, I can see and click on the plus icon. I followed these steps:

- Add Edit Permissions to Daniel Publisher over any page
- Log in as Daniel Publisher and open Edit Mode over the page permissions were granted.
- Expand the Preview modal and you will see the plus icon

**Comment by nollymar** [comment]
**Internal QA:** Passed

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_dcc1a28**, Docker, macOS 13.0, FF v113.0
