### ISSUE TITLE
Build New Social Media Tile Preview Tool for Facebook

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25287]
### Task

Build New Social Media Tile Preview Tool for Facebook

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

### Acceptance Criteria

See notes here:

* Social Media Tile & Search Engine Results Page Preview Tool Messages | dotCMS - Google Docs || https://docs.google.com/document/d/1O8PMni7FzD9YmIHdz-De43MnHpO--0_W49ZwYxLt9DM/edit

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

Demo - https://www.figma.com/proto/jyu7b1wgL16iV7yOoNdgu9/SEO?page-id=1%3A65&type=design&node-id=298-6800&viewport=-1440%2C-118%2C0.37&scaling=scale-down&starting-point-node-id=372%3A9190 

Design - https://www.figma.com/file/jyu7b1wgL16iV7yOoNdgu9/SEO?type=design&node-id=298-6800&t=kzAG714FzCpMdHYC-0

Sanity Check Requirements - https://socialsharepreview.com/?url=https://dotcms.com

**Comment by nollymar** [comment]
**Internal QA:** needs work

My findings: 

- [ ] A favicon validation is made but for Facebook it isn't required
- [ ] There is a typo in "Fav**I**con found". It won't affect Facebook preview but it will for the other social network previews

![Image](https://github.com/dotCMS/core/assets/8741395/6f510eda-bfa9-4e37-adf4-810d1cc1ded0)

- [ ] og:image, og:title and og:description sections are displayed empty but green 

![Image](https://github.com/dotCMS/core/assets/8741395/7e7c572e-4257-409d-b26a-19ae060933d4)


- [ ] The description size limit is not being validated correctly. For example: I defined just 2 letters and the validation passed


![Image](https://github.com/dotCMS/core/assets/8741395/b5da666a-8e64-46d3-80fd-e50c9e1703e0)

- [ ] We are not validating tag duplicates (for example: og:description, og:image, etc)

**Comment by dcolina** [comment]
Internal QA: Needs work.

**og:title**

*Case 1:*

When the tag is missing.

The expected message `og:title meta tag not found, and HTML Title not found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/f66f0418-bf4f-4881-80e8-a49970a745dc)

*Case 2:*

When the tag exists but is empty.

`<meta property="og:title"  />` or `<meta property="og:title"  content="" />`

The expected message `og:title meta tag found, but is empty!`is not shown.

![Image](https://github.com/dotCMS/core/assets/29883881/c0d7421e-5362-4660-a36d-d6775f0b5269)

*Case 3:*

When the tag exists, but it has more than 160 characters of content.

`<meta property="og:title" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." />`

The expected message `og:title meta tag found, but has more than 160 characters.` is ok, but It must only show the first 60 Characters in the Preview.

![Image](https://github.com/dotCMS/core/assets/29883881/da4e2f15-ae0a-468c-9b7e-fd2e28f33592)

*Case 4:*

When the tag exists, but has fewer than 30 characters of content.

The expected message `og:title meta tag found, but has fewer than 30 characters of content.` does not match, there is a typo.

![Image](https://github.com/dotCMS/core/assets/29883881/6fceec53-a355-4627-b44c-f8dd224523ba)

**Comment by dcolina** [comment]
Internal QA: Needs work.

**og:title**

*Case 1:*

When `og:title` is found, but is empty.

The expected message `og:title meta tag found, but is empty!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/4f977c72-82b0-40d4-bebf-ef421c3445b8)

**og:description**

*Case 1:*

When `og:description` and `meta tag description` not found.

The expected message `og:description meta tag, and Meta Description not found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/74ea2c88-56b7-4753-9afe-276712a79f59)

*Case 2:*

When `og:description` is found, but is empty.

`<meta property="og:description" >`

The expected message `og:description meta tag, and Meta Description not found!` does not match.

![Image](https://github.com/dotCMS/core/assets/29883881/874f56af-3882-404d-b2a5-21c0e8da738d)

*Case 3:*

When `og:description` is found, but is empty.

`<meta property="og:description" > content=""`

![Image](https://github.com/dotCMS/core/assets/29883881/115d1c4e-a023-412a-ac72-980b2978ab9d)

Is it necessary to show all of the validation messages?

**Comment by dcolina** [comment]
Internal QA: Needs work.

**og:title**

*Case 1:*

When `og:title` has 60 characters.

`<meta property="og:title" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit.****" />`

The expected message `og:title meta tag with valid content found!` does not found.

![Image](https://github.com/dotCMS/core/assets/29883881/5158e421-cbcf-445a-b040-d69d9fe1b547)

*Case 2:*

When `og:title` has 30 characters.

`<meta property="og:title" content="Lorem ipsum dolor sit amet****" />`

The expected message `og:title meta tag with valid content found!` does not found.

![Image](https://github.com/dotCMS/core/assets/29883881/b6347d73-088b-4699-8ca7-500948f3d3cc)

**og:description**

*Case 1:*

When `og:description` has 55 characters.

`<meta property="og:description" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit"/>`

The expected message `og:description meta tag found, but it has fewer than 55 characters of content.` does not found.

![Image](https://github.com/dotCMS/core/assets/29883881/da8b796c-22a8-4480-b8f0-9c07bc55cc8d)


*Case 2:*

When `og:description` has 150 characters.

`<meta property="og:description" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ante metus, posuere quis posuere eu, varius nec ante. Aenean nec dictum purus.**********"/>`

The expected message `og:description meta tag found, but it has more than 150 characters.` does not found.

![Image](https://github.com/dotCMS/core/assets/29883881/b7e2e290-94cb-48f5-9c77-464bb36faa5d)

**Comment by dcolina** [comment]
Internal QA: PASSED.

**Comment by bryanboza** [comment]
We need some work here: 

- Seems this preview is generated just for the default language, when you have a multi language page, we still showing the same image for the different languages 

https://github.com/dotCMS/core/assets/2641437/b80302cc-ffc7-49cc-8641-516df836cd1b

**Comment by nollymar** [comment]
It is a problem with the starter data, not related with the seo implementation

**Comment by bryanboza** [comment]
After the discussion this is a know issue, we can pass this card.
