### ISSUE TITLE
Create a Running Experiment ID

### ISSUE THREAD

**Issue by freddyucv** [dotCMS/core#25300]
### Parent Issue

https://github.com/dotCMS/core/issues/22222

### User Story

We need to create a new ID for each time the Experiment turn into the Running Status, so we are going to be able to run the Experiment multiple times segmenting the data for each Running ID.

### Acceptance Criteria

Include the Running Experiment ID and filter the result by this new ID

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Sub-Tasks & Estimates

- [ ] Generate a new Running ID when the Experiment turn into RUNNING STATE.
- [ ] Send this ID to the browser inside the Response when a User is included inside an Experiment.
- [ ] Include this new ID inside the Events's attributes 
- [ ] When we are going to analyze the Events to calculate the Experiments's results we need to filter by this Running ID.

Restart an Experiment is out of the scope of this issue

**Comment by oidacra** [comment]
IQA Passed: 

-- Generate a new Running ID when the Experiment turn into RUNNING STATE. 

![Image](https://github.com/dotCMS/core/assets/1909643/9aa6c5c4-955e-41c6-afdb-fc253d8a218b)


- Send this ID to the browser inside the Response when a User is included inside an Experiment.

![Image](https://github.com/dotCMS/core/assets/1909643/eee22a33-f9fc-4b49-a4d0-29a82eb91d41)


- Include this new ID inside the Events's attributes 

![Image](https://github.com/dotCMS/core/assets/1909643/67a3d9b2-d1c2-4e6c-8f52-7051fdb0bf49)


- When we are going to analyze the Events to calculate the Experiments's results we need to filter by this Running ID.

![Image](https://github.com/dotCMS/core/assets/1909643/2faacaac-0337-4c34-aff2-47ed72a7c707)

**Comment by bryanboza** [comment]
Now we are generating a new running ID when you run the experiment, but we need to add postman test to the endpoint, in order to make sure this Id is coming in the response.

**Comment by dsilvam** [comment]
@bryanboza postman tests included. Please retest.

**Comment by bryanboza** [comment]
Fixed, tested on master // Docker // FF
