### ISSUE TITLE
Design System: Apply new theme

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25355]
### Parent Issue

*No response*

### User Story

Epic to track the implementation for the new design system in the primeng and dojo components.

### Acceptance Criteria

\`\``[tasklist]
### Tasks
- [ ] #25356
- [ ] https://github.com/dotCMS/core/issues/25759
- [ ] https://github.com/dotCMS/core/issues/25790
- [ ] https://github.com/dotCMS/core/issues/25897
- [ ] https://github.com/dotCMS/core/issues/26057
- [ ] https://github.com/dotCMS/core/issues/26063
- [ ] https://github.com/dotCMS/core/issues/26303
- [ ] https://github.com/dotCMS/core/issues/26370
- [ ] https://github.com/dotCMS/core/issues/26409
- [ ] https://github.com/dotCMS/core/issues/26566
- [ ] #26603
- [ ] #26621
`\`\`

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

*No response*

### Assumptions & Initiation Needs

*No response*

### Quality Assurance Notes & Workarounds

*No response*

### Sub-Tasks & Estimates

*No response*

\`\``[tasklist]
### Tasks
`\`\`
