### ISSUE TITLE
[EPIC] Edit Contentlet Implementation

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25445]
### Feature

- Authoring Content - We need a way to maximize the actual content editing experience to be central.  As we have it now, no content contributor wants to author content in dotCMS.  
- Save Unsaved Content changes to local storage under the contenttype var name as key (meaning, you can come back to the screen and not lose your changes).  Github does this and it is nice.
- Allow multiple content editing screens open simultaneously (tabs?)
- URL Friendly endpoints when adding/editing content, e.g.
    - #/content/blog  ← new blog
    - #/content/{inode} ← content version
- As we need the content editing screen to show up in various places, is there a more router friendly (permalink) way of showing it? There are going to be editors that don’t have specific portlets and 
- Keyboard shortcuts and keyboard navigation.

### Pain Points

1. The forms are inaccessible,
2. It can't be navigated with keyboard
3. Design looks outdated
4. Slow to load and to use
5. Is not URL accessible
6. In general, it is a bad experience for content authors.

### Acceptance Criteria

```[tasklist]
### Tasks
- [ ] #25434
- [ ] #25441
- [ ] #25448
- [ ] #25781
- [ ] #25782
- [ ] https://github.com/dotCMS/core/issues/25946
- [ ] https://github.com/dotCMS/core/issues/26045
- [ ] https://github.com/dotCMS/core/issues/26047
- [ ] https://github.com/dotCMS/core/issues/26048
- [ ] https://github.com/dotCMS/core/issues/26053
- [ ] https://github.com/dotCMS/core/issues/26105
- [ ] #26163
- [ ] https://github.com/dotCMS/core/issues/26219
- [ ] https://github.com/dotCMS/core/issues/26330
- [ ] https://github.com/dotCMS/core/issues/26340
- [ ] #26389
- [ ] https://github.com/dotCMS/core/issues/26440
- [ ] #26442
- [ ] #26491
- [ ] #26512
- [ ] #26526
- [ ] https://github.com/dotCMS/core/issues/26559
- [ ] #26573
- [ ] #26448
- [ ] #26577
- [ ] #26579
- [ ] https://github.com/dotCMS/core/issues/26628
- [ ] https://github.com/dotCMS/core/issues/26634
- [ ] https://github.com/dotCMS/core/issues/26649
- [ ] #26698
- [ ] #26696
- [ ] https://github.com/dotCMS/core/issues/26837
- [ ] https://github.com/dotCMS/core/issues/26838
- [ ] https://github.com/dotCMS/core/issues/26907
- [ ] https://github.com/dotCMS/core/issues/26842
- [ ] https://github.com/dotCMS/core/issues/26902
- [ ] https://github.com/dotCMS/core/issues/26969
- [ ] https://github.com/dotCMS/core/issues/26910
- [ ] https://github.com/dotCMS/core/issues/26839
- [ ] https://github.com/dotCMS/core/issues/26901
- [ ] https://github.com/dotCMS/core/issues/26080
- [ ] https://github.com/dotCMS/core/issues/27068
- [ ] https://github.com/dotCMS/core/issues/26900
- [ ] https://github.com/dotCMS/core/issues/26884
- [ ] https://github.com/dotCMS/core/issues/26082
- [ ] https://github.com/dotCMS/core/issues/26906
- [ ] https://github.com/dotCMS/core/issues/26904
- [ ] https://github.com/dotCMS/core/issues/27522
- [ ] https://github.com/dotCMS/core/issues/26656
- [ ] https://github.com/dotCMS/core/issues/27289
- [ ] https://github.com/dotCMS/core/issues/27661
- [ ] https://github.com/dotCMS/core/issues/27519
- [ ] https://github.com/dotCMS/core/issues/27969
- [ ] https://github.com/dotCMS/core/issues/27908
- [ ] https://github.com/dotCMS/core/issues/27947
- [ ] https://github.com/dotCMS/core/issues/28094
- [ ] https://github.com/dotCMS/core/issues/28200
- [ ] https://github.com/dotCMS/core/issues/28097
- [ ] https://github.com/dotCMS/core/issues/27943
- [ ] https://github.com/dotCMS/core/issues/27944
- [ ] https://github.com/dotCMS/core/issues/26903
- [ ] https://github.com/dotCMS/core/issues/28011
- [ ] https://github.com/dotCMS/core/issues/27945
- [ ] https://github.com/dotCMS/core/issues/28156
- [ ] https://github.com/dotCMS/core/issues/28186
- [ ] https://github.com/dotCMS/core/issues/28183
- [ ] https://github.com/dotCMS/core/issues/28302
- [ ] https://github.com/dotCMS/core/issues/28338
- [ ] https://github.com/dotCMS/core/issues/28494
- [ ] https://github.com/dotCMS/core/issues/28493
- [ ] https://github.com/dotCMS/core/issues/29691
- [ ] https://github.com/dotCMS/core/issues/29692
- [ ] https://github.com/dotCMS/core/issues/31066
- [ ] https://github.com/dotCMS/core/issues/31069
- [ ] https://github.com/dotCMS/core/issues/30371
- [ ] https://github.com/dotCMS/core/issues/30012
- [ ] https://github.com/dotCMS/core/issues/30795
- [ ] https://github.com/dotCMS/core/issues/31288
```

### Proposed Objective

Please Select

### Proposed Priority

Please Select

**Comment by erickgonzalez** [comment]
@fmontes when doing the Relationship field please take into consideration this https://github.com/dotCMS/core/issues/22884

**Comment by erickgonzalez** [comment]
@fmontes please take this into consideration https://github.com/dotCMS/core/issues/26814

**Comment by fmontes** [comment]
@erickgonzalez yes, @Neehakethi ping me in slack and this is coming in the new version, the current issue is due dojo.
