### ISSUE TITLE
Localization Improvements - Phase 1

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25603]
### User Story

Currently dotCMS supports multilingual sites, however we’re fairly loose out of the box and some of the things we do don’t follow modern best practices. As a result users can do multilingual correctly if they invest time into config, or they can do them less-correctly if they don’t. We need to make a few tweaks to ensure that dotCMS is easy to use correctly right out of the box, and shore up our default install to align with modern standards for SEO and localization conventions.

There will be an estimated 2-3 phases to this project.

Loosely planned...

1. Phase 1 - Adding Locales
2. Phase 2 - Adding Reports & Tools to Help Find Content Missing Translations & Beef Up Localization SEO
3. Phase 3 - Adding Support for Translation Management Services

## Phase 1

- Create Upgrade Script to Convert Language Variables to Content Items
- Create New PrimeNG Datatable Component
- Rebuild List Languages Page
- Rebuild Add New Language Workflow
- Rebuild Edit Language Page
- Rebuild Edit Default Language Variables Page, using Content Items
- Update Starter Site to Use Locale for URL Path
- Update Starter to Have Sitemap for Each Locale
- Update Starter to Use HREFLANG Blocks
- Update Default Locale to be Work by Site
- Re-Translate Admin Tools

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* Localization Improvements - Phase 1 | dotCMS Internal Documentation - Google Docs || https://docs.google.com/document/d/1bjEM89vkt8TUcKiNgbCY8BPYfpTg_AX3Sb-Brxvy5AA/edit

**Legacy Files, no longer source of truth.**

* Multilingual Improvements | dotCMS Product Ideation - Google Docs | https://docs.google.com/document/d/1mf1hS-VrRuqZzboCPQTH_7hSW3iU5J5sRhPwP-t4M7k/edit
* Design Notes for Localization Improvements (Phase 1) | Product Ideation - Google Docs | https://docs.google.com/document/d/1pcZeqJyDrouHNXSE6ahv2v2WTYEasS9So2Iu1APlxqM/edit

### Sub-Tasks & Estimates
- [ ] https://github.com/dotCMS/core/issues/27703
- [ ] https://github.com/dotCMS/core/issues/27702
- [ ] https://github.com/dotCMS/core/issues/27594
- [ ] https://github.com/dotCMS/core/issues/25604
- [ ] https://github.com/dotCMS/core/issues/25605
- [ ] https://github.com/dotCMS/core/issues/25606
- [ ] https://github.com/dotCMS/core/issues/27978
- [ ] https://github.com/dotCMS/core/issues/27979
- [ ] https://github.com/dotCMS/core/issues/28251
- [ ] https://github.com/dotCMS/core/issues/28397
- [ ] https://github.com/dotCMS/core/issues/28396
- [ ] https://github.com/dotCMS/core/issues/28395
- [ ] https://github.com/dotCMS/core/issues/25607
- [ ] https://github.com/dotCMS/core/issues/25891
- [ ] https://github.com/dotCMS/core/issues/25608

**Comment by wezell** [comment]
@damen-dotcms we need to add - make the PageAPI respect the new localized urls, e.g. 

- `/api/v1/page/json/en-us/destinations/costa-rica`
- `/api/v1/page/json/en/destinations/costa-rica`
- `/api/v1/page/json/destinations/costa-rica`
- `/api/v1/page/json/es/destinations/costa-rica`

**Comment by john-thomas-dotcms** [comment]
Some of the issues included in the original epic were later determined to not be required for phase 1.  These have been moved to other epics.

All issues for this issue are now complete.
