### ISSUE TITLE
Update Screens for Add Language to Bundle Workflow

### ISSUE THREAD

**Issue by damen-dotcms** [dotCMS/core#25608]
### Parent Issue

https://github.com/dotCMS/core/issues/25603

### Task

We need to update the way a User can Add a Language to a Push Publishing Bundle (found here https://demo.dotcms.com/dotAdmin/#/c/languages > right click on a Language and hit "Add to Bundle").

### Proposed Objective

Core Features

### Proposed Priority

Same as Parent

### Acceptance Criteria

- Update Designs for Add Language to Bundle Workflow
- Update Application API for Add Language to Bundle Workflow
- Update Add Language to Bundle Workflow

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

* Design Notes for Localization Improvements (Phase 1) | Product Ideation - Google Docs | https://docs.google.com/document/d/1pcZeqJyDrouHNXSE6ahv2v2WTYEasS9So2Iu1APlxqM/edit

### Sub-Tasks & Estimates

```[tasklist]
### Tasks
- [ ] Update Designs for Add Language to Bundle Workflow
- [ ] Update Application API for Add Language to Bundle Workflow
- [ ] Update Add Language to Bundle Workflow
```

**Comment by damen-dotcms** [comment]
Not doing this. Removing this feature in the re-design.
