### ISSUE TITLE
Change to use JWT scopes instead of custom claims for customer and cluster id to support Cognito in cloud analytics

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#25777]
### Task

Currently we have created a custom JWT claim to provide the customer id an cluster id in the analytics api auth token.  Claims are the individual key value pairs in the JWT token body.   Custom claims are intended to provide additional identifying information and are normally name-spaced to prevent conflicts.

Authorization information is usually held in the scopes claim.  This is a space separated list of strings that could be anything defined for the app but often provide information on a permission and a level of permission e.g.  read:user, admin:user

In Keycloak we have the ability to custom define both scopes and claims any way we want.

In Amazon AWS Cognito a pre token generation lambda function can be created to add an modify scopes.  Unfortunately this only runs when a token is created that represent a particular user.

We do not have any user information and are using the Oauth2 client_credentials claim ( a machine to machine token).  On Cognito we have a separate cognito "App Client" per customer providing a client id and client secret allowing for a request for the auth token.    Cognito does not run any pre token generation lambda functions for these tokens and so we cannot use this mechanism to add or modify custom claims.

We are able to define a list of available custom scopes for the "App Client".   Custom scopes need to be requested by the client when making the client credentials for it to be included in the token.   Keycloak and other providers may allow you to always include some scopes without request but Cognito needs it to be requested.

We can  create 2 custom scopes for each "App Client". that is of the format  customerid:customer1 clusterid:cluster1.  scopes are returned in the scopes claim as a space separated string.    We could also provide oher scopes that provide more info on the level of security.   One way that may provide us flexibility here is to add a label that defines whether the data should be filtered at a customer level allowing all clusters to be returned or at a cluster level only allowing query of data for the single cluster,  further restrictions of security levels can be added later,   e.g. admin,  read only,  individual service levels if needed.

"scope":"customerid:customer1 clusterid:cluster1",

Here is an example of a client_credentials request to cognito including scopes
One of the benefits of the scopes needing to be requested is that there can be lots of scopes/permissions available but the client can request a token with the minimum permissions required for its use.

```
POST <https://mydomain.auth.us-east-1.amazoncognito.com/oauth2/token> >
                            Content-Type='application/x-www-form-urlencoded'&
                            Authorization=Basic ZGpjOTh1M2ppZWRtaTI4M2V1OTI4OmFiY2RlZjAxMjM0NTY3ODkw

                            grant_type=client_credentials&
                            client_id=1example23456789&
                            scope=resourceServerIdentifier1/scope1 resourceServerIdentifier2/scope2

```

For support of both cognito and stil use Keycloak for local developement we can progressively update the solution.

- [ ]  Add custom scopes to Keycloak used for docker-compose. Custom claim can still remains for existing dotcms during development.
- [ ]  Update configurator and cube.js config to find customer id in scopes, can fall back to claim if found for compatibility.
- [ ]  Update dotcms to use claims with Keycloak. Only real change will be that we need to include the customer1 and clusterid scope names in the client_credentials grant request. We may need to line up and make available the actual customerid in the analytics configuration, but we can rely upon and filter just on clusterid which we have until we do this possible ui change.
- [ ]  Test changed configuration to point at Cognito for test customer

This will allow for us to use Cognito entirely in production but also we can use Keycloak in development and any other Oauth2 provider in the future.

Note that as well as scopes the JWT is validated based upon the other standard claims to confirm the token is valid by time, is created from the expected source and is valid for the destination api.    At this time e are using one client to create access tokens that are valid for both the jitsu configurator and the cubejs server.

Existing keycloak JWT with custom claim

```
{
   "exp":1691964554,
   "iat":1691964254,
   "jti":"d345191f-83f5-430c-ab85-1ffa898a816a",
   "iss":"<http://localhost:8080/realms/dotcms>",
   "aud":"api-dotcms-analytics-audience",
   "sub":"6440a66e-b9da-4818-a8e5-7c443b6ce86a",
   "typ":"Bearer",
   "azp":"analytics-customer-customer1",
   "scope":"",
   "<https://dotcms.com/analytics/roles>":[
      "customer"
   ],
   "clientId":"analytics-customer-customer1",
   "clientHost":"127.0.0.1",
   "<https://dotcms.com/analytics>":{
      "customerId":"customer1",
      "clusterId":"cluster1"
   },
   "clientAddress":"127.0.0.1"
}

```

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

**Comment by john-thomas-dotcms** [comment]
Completed.  @spbolton will file a new card to improve the (currently manual) process to sync up the analytics infrastructure from a separate repo into master.
