### ISSUE TITLE
[Containers] : Fix UI Issues in the Portlet

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25808]
### Parent
#23140

### Problem Statement
The UI for containers portlets in dotCMS is not properly displaying in some cases. The portlet displays as a blank box, and the content stored in the container is not visible or accessible. 

```[tasklist]
### Tasks
- [x] Prevent the jump when click the "Pre post loop" button, [see video](https://github.com/dotCMS/core/assets/751424/79743a40-e060-4ae2-93f9-3964405fb63c)
- [ ] Prevent the jump to edit the title, [see image](https://github.com/dotCMS/core/assets/751424/f9b3a354-82c5-4285-981f-a81c179c4de6)
- [x] Make the content type selector wider to avoid some of the ellipsis, [see image](https://github.com/dotCMS/core/assets/751424/1bd4a0b3-0d32-40c1-a927-b331147e7e35)
- [x] Fix the buttons size and position, [see image](https://github.com/dotCMS/core/assets/751424/4384333a-a613-4da8-a8b4-843e33dca1c4)
- [x] Make the add container button primary, [see image](https://github.com/dotCMS/core/assets/751424/bb3e5ba1-dd94-4595-bd18-bbcb1ae12662)
- [x] Fix "Add variables" buttons, [see image](https://github.com/dotCMS/core/assets/751424/29d66caf-e70e-4244-aa80-b575a0a4d209)
- [x] Fix scrolling tabs, [see images](https://github.com/dotCMS/core/assets/751424/84337a1a-8390-4ecd-a5d7-13486c9224ed)
- [x] Avoid the jump in the tabs from loading to loaded, [see video](https://github.com/dotCMS/core/assets/751424/735ec4d7-af10-4872-83c4-0246f51f4605)
```

### Acceptance Criteria
- All UI issues attached to this ticket should be fixed
- The content stored in the containers portlets should be visible and accessible

### External Links
N/A

### Assumptions & Initiation Needs
- The developer should have knowledge of dotCMS and the DotCMS UI
- The developer should have access to the existing codebase and the support ticket

### Quality Assurance Notes & Workarounds
- The QA team should test the changes to ensure that all UI issues are fixed and the content is visible and accessible
- As a workaround, the content in the containers portlets can be manually accessed by the developer in the meantime

**Comment by fmontes** [comment]
https://demo.dotcms.com/dotAdmin/#/containers

**Comment by zJaaal** [comment]
## Falied IQA 

We just need to add this message to the `Language.properties` file

<img width="595" alt="Screenshot 2023-09-15 at 10 53 03 AM" src="https://github.com/dotCMS/core/assets/63567962/ea2f5ec7-7dc8-416b-b68e-eb736c5fc3bd">

**Comment by fmontes** [comment]
Needs work... the filter selector should not jump

**Comment by josemejias11** [comment]
![Screenshot 2023-09-18 at 9 47 37 AM](https://github.com/dotCMS/core/assets/129882031/e6a8aba2-69e2-4873-b864-bc04c1a6e91e)

Icons and texts overlapping

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1d55008**, Docker, macOS 13.0, FF v113.0
