### ISSUE TITLE
Fix UI Issues After TextFields and Dropdown Changes

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#25862]
### User Story
As a developer, I want to fix UI issues after CSS changes, so I can ensure a consistent user experience across the platform.

```[tasklist]
### Acceptance Criteria
- [x] Fix the site selector when have long texts - [see image](https://github.com/dotCMS/core/assets/751424/15609c50-f84e-47ae-a8f7-533e36c18989)
- [x] FIx the create page modal size - [see image](https://github.com/dotCMS/core/assets/751424/721f4e57-cdd4-4068-9c69-790a29501a6a)
- [x] Fix the add thumbnail to template field, [see image](https://github.com/dotCMS/core/assets/751424/2aec8916-3a69-4101-9c22-a91bcabd1b4a)
- [x] Fix the dropdown in permissions tab, [see image](https://github.com/dotCMS/core/assets/751424/468f3b43-9ddb-4ba4-830e-931e299511c2)
- [x] Fix the toolbar in the language - [see image](https://github.com/dotCMS/core/assets/751424/cd0eb51c-d6de-4df9-a986-96b1f710dd35)
- [x] Fix Tags and Text Areas font size - [see image](https://github.com/dotCMS/core/assets/63567962/cd7004f3-1d6a-4527-a19b-26a8b3aed5ea)
- [x] Fix Page Scroll Bars Appear with some Large Dropdowns - [see image](https://github.com/dotCMS/core/assets/63567962/876a66b3-17a8-4e3d-8884-744520be049d)
- [x] Fix Next Month / Back Month arrows missing from date fields - [see image](https://github.com/dotCMS/core/assets/63567962/dac278c2-563c-49f5-aa7b-d01fc89c19e5)
- [x] Fix Dojo add to bundle dialog wraps - [see image](https://github.com/dotCMS/core/assets/63567962/2eb509a1-77b1-4498-8bcb-286f666ae58a)
```

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- All changes to the CSS are up to date
- All UI issues caused by the CSS changes are identified

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Identify issues: 2 hours
- List out issues to be fixed: 1 hour
- Fix all identified UI issues: 4 hours

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1e74186_SNAPSHOT Docker, macOS 13.0, FF v113.0
