### ISSUE TITLE
Metrics: Add snapshot metrics for Custom Workflows

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#25889]
### Parent Issue

https://github.com/dotCMS/core/issues/25883

Add snapshot metrics to the Experience plugin to collect data on the use of Workflows in the system.

"Snapshot" in this case means information that we can collect as a point-in-time reading, where periodically taking a single reading will provide useful information.  \(As opposed to metrics which determine the rates or times when changes or events happen\).

### Implementation Methods

Snapshot metrics can usually be implemented with any of the following:

* A query against the DB
* A query against the index
* A Java API call
* A read of the file system

Of these, we should prefer direct DB calls when possible.  For metrics which depend on a deeper understanding of the DB structure, we should prefer a call to a Java API which has the appropriate business logic built-in.

### Metrics to Implement

The following static metrics should be implemented for Workflows, as part of this card:

* Count of workflow schemes
* Count content types assigned schemes other than System Workflow
* Count of steps in all schemes
* Count of workflow actions in all schemes
* Count of workflow subactions in all Workflow actions
* Count of unique workflow subactions in all Workflow actions
    * If this can't be performed easily with a single query \(or maybe two\), then we can move this to another card for more complex metrics.

\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/26783
- [ ] https://github.com/dotCMS/core/issues/26804
- [ ] https://github.com/dotCMS/core/issues/26813
- [ ] https://github.com/dotCMS/core/issues/26827
- [ ] https://github.com/dotCMS/core/issues/26857
- [ ] https://github.com/dotCMS/core/issues/25888
- [ ] https://github.com/dotCMS/core/issues/26921
`\`\`
