### ISSUE TITLE
Implement GHA to generate a CLI release

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#25951]
### Parent Issue
[24968](https://github.com/dotCMS/core/issues/24968)

### Task
As a developer working on the project, I want to create an automated GitHub Actions workflow that facilitates the seamless creation and launch of new releases for **dotcms-cli** project using the JReleaser plugin. The key requirement is to ensure that the release version aligns with the CORE project version.

Proposed Objective
CLI Features

Proposed Priority
Priority 3 - Average

### Acceptance Criteria
- [ ] The GitHub Actions workflow should be triggered by specific events, such as new commits to designated branches or tag.
- [ ] The workflow will utilize the JReleaser plugin and Maven to manage the release process.
- [ ] The release version must be obtained from the CORE project version.
- [ ] The workflow should automatically set up a suitable Java runtime (Java 11+) for JReleaser.
- [ ] The released artifacts should be published to a remote repo (e.g. Maven Central, Artifactory, etc.).
- [ ] Relevant release documentation should be generated and associated with the release.
- [ ] The workflow should ensure that the CORE project version and the released version are consistent.
- [ ] In case of any issues during the release process, appropriate notifications or alerts should be sent to the development team.

External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
No response

Assumptions & Initiation Needs
No response

Quality Assurance Notes & Workarounds
No response

Sub-Tasks & Estimates
No response
