### ISSUE TITLE
Design System: UI tweaks

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26063]
### Parent Issue

#25355 

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

```[tasklist]
### Tasks
- [ ] Update the font size in the labels of dojo forms, make it 1rem
- [x] Bump the sm font size to `0.8125rem` (13px) to see how it looks like
- [x] Make the "Actions" buttons in template list default size (is small)
- [x] Update text un template and container search field to from "Global Search" to "Type to filter"
- [x] Center the lock icon in the edit page switch
- [x] Remove `capitalize` from buttons text because some canses we don't want that
```

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_1d55008**, Docker, macOS 13.0, FF v113.0

![Screenshot 2023-09-27 at 2 08 49 PM](https://github.com/dotCMS/core/assets/129882031/b4cde97a-c4ba-499e-a6b2-044181825299)

Please align. (Firefox use)

**Comment by fmontes** [comment]
Create a new ticket, is not related with this changes.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d0f3abe_SNAPSHOT**, Docker, macOS 13.0, FF v113.0


Issue will be work on card https://github.com/dotCMS/core/issues/26327
