### ISSUE TITLE
CLI: Create a short video explaining how to use the dotcms-cli

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#26190]
### Task

As a user I'd like to have a video explaining how the new dotcms cli works. The video should: 

- [ ] Be 2-3 min long
- [ ] Provide a basic explanation of the most important highlights. It should include how to pull/push files from the command line and how to push changes from a GH repo to a dotcms target.
- [ ] Be targeted to any user who wants to use the cli. Not just for internal use.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

**Comment by nollymar** [comment]
Consider these videos as references: 

https://www.youtube.com/watch?v=vxVphAjeEH0&t=3s
https://www.youtube.com/watch?v=AJ43Onb5wJU&t=130s
