### ISSUE TITLE
[UI] Block editor -  AI block integration

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26495]
### User Story

As a user, I want to generate content using OpenAI

### Acceptance Criteria

- Plugin to get content/images from OpenAi
- A new block to add Text using AI
- A new block to add Images using AI

### Proposed Objective

User Experience

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- [Prototype of new Block](https://www.figma.com/proto/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?page-id=1047%3A13823&type=design&node-id=1047-18970&viewport=1115%2C968%2C0.05&t=jWTXxCzFmqhm7WSa-1&scaling=scale-down&starting-point-node-id=1047%3A18970&show-proto-sidebar=1&mode=design)
- [Figma File](https://www.figma.com/file/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?type=design&node-id=1176%3A19690&mode=design&t=5l16VYTzDnyHq9l8-1)
- [AI Plugin Base Repo
](https://github.com/dotCMS/com.dotcms.ai/tree/main)

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/26521
- [ ] https://github.com/dotCMS/core/issues/26657
- [ ] https://github.com/dotCMS/core/issues/26664
- [ ] https://github.com/dotCMS/core/issues/26506
- [ ] https://github.com/dotCMS/core/issues/26504
- [ ] https://github.com/dotCMS/core/issues/26505
- [ ] https://github.com/dotCMS/core/issues/26556
- [ ] https://github.com/dotCMS/core/issues/26520
- [ ] [UI] Handle the `ESC` in both plugins, trigger close the creation of the post/blog
- [ ] https://github.com/dotCMS/core/issues/26895
- [ ] https://github.com/dotCMS/core/issues/26912
- [ ] https://github.com/dotCMS/core/issues/27051
- [ ] https://github.com/dotCMS/core/issues/26853
- [ ] https://github.com/dotCMS/core/issues/26854
```

**Comment by hmoreras** [comment]
QA Notes: 
 
Steps for the AI plugin to work: 


1. Add the package com.barchart.udt in the Exported Packages button in the plugin portlet.
2. Install the last version of the AI plugin.
3. Add the token key in the apps configuration portlet.
4. Postgres version should be 15 or up.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1894351**, Docker, macOS 13.0, FF v121.0.1
