### ISSUE TITLE
[BE] Make AI plugin Production-ready

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#26506]
Consume as a proxy the OpenAI Endpoint

 Repo of the plugin: https://github.com/dotCMS/com.dotcms.ai
```[tasklist]
### Tasks
- [x] [BE] - Review Build and Run the plugin
- [ ] https://github.com/dotCMS/core/issues/26723
- [ ] https://github.com/dotCMS/core/issues/26852
- [ ] https://github.com/dotCMS/core/issues/27124
```

**Comment by oidacra** [comment]
Check if we will use the mechanism of check heath to not load the AI Nodes to block editor @danielmdob @john-thomas-dotcms

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1894351**, Docker, macOS 13.0, FF v121.0.1
