### ISSUE TITLE
Edit Content: Update the tags endpoint

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26573]
### Parent
[#25445](https://github.com/dotCMS/core/issues/25445)

### User Story
As a dotCMS user, I want to have an updated tags endpoint using the latest format, so I can access the correct data. 

```[tasklist]
### Tasks
- [x] We have `/api/v1/tags` we need to create `/api/v2/tags`
- [x] New endpoint should have latest format
- [x] Make sure we can use all methods
- [x] We need to be able to create a tag
- [x] We need to be able to edit a tag
- [x] We need to be able to delete a tag
- [x] We need to be able get sugesstiong based on a string, filtering
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_846bb3d**, Docker, macOS 13.0, FF v113.0
