### ISSUE TITLE
Edit Content: Implement Control Value Accessor in the Binary Field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26579]
### Parent
#25445

### User Story
As an editor, I want to be able to use the binary field component with the Angular forms as a field.

```[tasklist]
### Tasks
- [ ] The binary field must be able to be use in an Angular form
- [ ] Add the binary field field to the edit content form
- [ ] Binary field should send data to be saved
- [ ] Binary field should receive data and set the value
- [ ] [Field variables](https://www.dotcms.com/docs/latest/field-variables#BinaryField) should work as expected
```

### Proposed Objective
Static Content: "Core Features"

### Proposed Priority
Static Content: "Priority 3 - Average"

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
- Component is here: `core-web/libs/contenttype-fields/src/lib/fields/binary-field/binary-field.component.ts`

### Assumptions & Initiation Needs
- The Binary field field must be a component

### Quality Assurance Notes & Workarounds
N/A
