### ISSUE TITLE
Show System Table Variables in the System Info Page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26622]
### User Story
As a dotCMS user, I want to be able to view system table variables in the System Info page, so I can troubleshoot any issues that may arise.

```[tasklist]
### Acceptance Criteria
- [ ] The system variables should be visible in the system info page.
- [ ] The system variables should be retrieved from the system table.
- [ ] The system variables should have the info of where is coming from.
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- System table variables must exist in the system.
- System info page must be set up to view the system variables.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A
