### ISSUE TITLE
Edit EMA Page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26644]
### Due Date

1/22/2024

### Parent Issue

*No response*

### User Story

As a developer, I want to be able to edit the pages of my nextjs app with the dotCMS page builder.

### Acceptance Criteria

1. The user should be able to add content
2. The user should be able to edit content
3. The user should be able to move content from one container to another by drag and drop
4. The user should be able to update the page properties
5. The user should be able to publish the page

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

N/A

### Assumptions & Initiation Needs

Even tho we have edit mode right now, the approach wasn't designed to edit pages created with modern JavaScript frameworks.

Our current approach is too intrusive because we inject HTML, CSS, and JavaScript to the pages to get the tools \(buttons\) and drag and drop functionality.

Injecting code into a page managed by a JavaScript framework can cause conflicts. HTML injections can disrupt the virtual DOM, leading to render issues, CSS injections may break styles and layouts, and JavaScript injections can interfere with event handling and component lifecycle, potentially breaking page functionality. This leads to compatibility problems with the framework's expected operations.

This is why we need to work on a solution that is less intrusive and that doesn't require injecting code on runtime.

------------------------

⚠️ **Important**
We are not redoing edit mode from the ground up, we are creating a new version by reusing as much all the components and services of the current version.

------------------------

### Quality Assurance Notes & Workarounds

N/A

### Sub-Tasks & Estimates

N/A

\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/26648
- [ ] https://github.com/dotCMS/core/issues/26687
- [ ] https://github.com/dotCMS/core/issues/26725
- [ ] https://github.com/dotCMS/core/issues/26702
- [ ] https://github.com/dotCMS/core/issues/26769
- [ ] https://github.com/dotCMS/core/issues/26789
- [ ] https://github.com/dotCMS/core/issues/26809
- [ ] https://github.com/dotCMS/core/issues/26820
- [ ] https://github.com/dotCMS/core/issues/26821
- [ ] https://github.com/dotCMS/core/issues/26846
- [ ] https://github.com/dotCMS/core/issues/26845
- [ ] https://github.com/dotCMS/core/issues/26909
- [ ] https://github.com/dotCMS/core/issues/26966
- [ ] https://github.com/dotCMS/core/issues/26916
- [ ] https://github.com/dotCMS/core/issues/26965
- [ ] https://github.com/dotCMS/core/issues/27001
- [ ] https://github.com/dotCMS/core/issues/26988
- [ ] https://github.com/dotCMS/core/issues/27075
- [ ] https://github.com/dotCMS/core/issues/27000
- [ ] https://github.com/dotCMS/core/issues/26998
- [ ] https://github.com/dotCMS/core/issues/27076
- [ ] https://github.com/dotCMS/core/issues/26997
- [ ] https://github.com/dotCMS/core/issues/27077
- [ ] https://github.com/dotCMS/core/issues/27115
- [ ] https://github.com/dotCMS/core/issues/27061
- [ ] https://github.com/dotCMS/core/issues/27112
- [ ] https://github.com/dotCMS/core/issues/26914
- [ ] https://github.com/dotCMS/core/issues/27106
- [ ] https://github.com/dotCMS/core/issues/26911
- [ ] https://github.com/dotCMS/core/issues/26986
- [ ] https://github.com/dotCMS/core/issues/27296
- [ ] https://github.com/dotCMS/core/issues/27278
- [ ] https://github.com/dotCMS/core/issues/27135
- [ ] https://github.com/dotCMS/core/issues/27154
- [ ] https://github.com/dotCMS/core/issues/27284
- [ ] https://github.com/dotCMS/core/issues/27308
- [ ] https://github.com/dotCMS/core/issues/27283
- [ ] https://github.com/dotCMS/core/issues/27305
- [ ] https://github.com/dotCMS/core/issues/27301
- [ ] https://github.com/dotCMS/core/issues/27335
- [ ] https://github.com/dotCMS/core/issues/27302
- [ ] https://github.com/dotCMS/core/issues/26958
- [ ] https://github.com/dotCMS/core/issues/27310
- [ ] https://github.com/dotCMS/core/issues/27173
- [ ] https://github.com/dotCMS/core/issues/27373
- [ ] https://github.com/dotCMS/core/issues/27372
- [ ] https://github.com/dotCMS/core/issues/27159
- [ ] https://github.com/dotCMS/core/issues/27306
- [ ] https://github.com/dotCMS/core/issues/27348
- [ ] https://github.com/dotCMS/core/issues/26713
- [ ] https://github.com/dotCMS/core/issues/26823
- [ ] https://github.com/dotCMS/core/issues/26847
- [ ] https://github.com/dotCMS/core/issues/26908
- [ ] https://github.com/dotCMS/core/issues/26960
- [ ] https://github.com/dotCMS/core/issues/27406
- [ ] https://github.com/dotCMS/core/issues/27483
- [ ] https://github.com/dotCMS/core/issues/27425
`\`\`

**Comment by fmontes** [comment]
# Edit mode for external pages

Author(s): @fmontes

Status: [Draft]

Last Updated: 2023-11-09

## Contents
- Goals
- Non-Goals
- Background
- Overview
- Detailed Design
  - Solution 1
    - Frontend
    - Backend
  - Solution 2
    - Frontend
    - Backend
- Considerations
- Metrics

## Links
- [A link](#)
- [Another link](#)

## Objective
dotCMS edit mode works very good with pages rendered by dotCMS but when the page is rendered headlessly with a modern frontend framework is hard for the developer to make it work and hard for the page editor because the edit experience is just bad.

## Goals
- Bring developers a better and simpler solution to implement edit mode with modern JavaScript frameworks
- Provide a better UX for marketers and content creator when editing this kind of pages

## Non-Goals
- Non-Goals

## Background
When we developed edit mode headless CMS and JamStack was not a big thing and dotCMS was focused in rendering the pages using VTL and containers, so the edit mode was designed to work with this type of pages.

Couple of years later JamStack exploded, we saw our curstomers want to use dotCMS as a data source and use NextJS, Angular, and other to docuple the page rendering out of dotCMS, headless was here.

We did some work and allowed developers to bring external pages to dotCMS edit mode, but the approach is hard to implement, prune to issues and the developer (and page editor) experience is just bad.

- https://www.dotcms.com/docs/latest/headless-in-context-editing
- https://github.com/dotCMS/dotcms-nextjs-starter

## Overview
_High-level overview of your proposal._

_This section should be understandable by new employees on your team that is not related to the project._

_Put details in the next section._

## Detailed Design
_Use diagrams where necessary._

_Tools like [Excalidraw](https://excalidraw.com) are good resources for this._

_Cover major changes:_

 _- What are the new functions that you will write?_

 _- Why do you need new components?_

 _- Is there any code that can be reusable?_

_Don’t elaborate deeply on the implementation details._

## Solution 1
### Frontend
_Frontend…_
### Backend
_Backend…_

## Solution 2
### Frontend
_Frontend…_
### Backend
_Backend…_

## Considerations
_Concerns / trade-offs / tech debt_

## Metrics
_What data do you need to validate before launching this feature?_

**Comment by fmontes** [comment]
Closing and we starting next: https://github.com/dotCMS/core/issues/27546
