### ISSUE TITLE
Fix ignored Postman tests

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#26676]
### Task

There are a number of Postman tests currently failing and excluded from the runs. 
They need to be fixed ASAP since we are loosing test coverage and regression. 

- [x] GraphQL/PageAPI/GivenRequestByURI_ContainersFieldContainsContainerContentlets
- [x] Push Publish from sender / Push Publish Old Way / Happy path / PPOW - HP - check success status
- [x] Page API / GetAvailableActionsPerPage / GetAvailableActions
- [x] Maintenance Resource / Download DB Dump

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

100% of all Postman tests need to pass.

**Comment by john-thomas-dotcms** [comment]
Let's break this up into smaller cards that we can pull in when we have small blocks of time
