### ISSUE TITLE
Edit Content: Create a Component to Render Custom Field (Legacy)

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26698]
### Parent
https://github.com/dotCMS/core/issues/25445

### User Story
As a dotCMS user, I want to be able to create a component to render a custom field (legacy), so I can easily and quickly access and edit content.

>  🚨 This issue depends on #26696

```[tasklist]
### Acceptance Criteria
- [x] Render the iframe with `src` to the new iframe we created in the issue #26696
- [x] Pass the content type and field variable to the `src` as query params
- [x] Set the width and height to the iframe from the field variables
- [x] Inject the Angular form group to the iframe window
```

- The Angular component should render an iframe and pass the content type and field variable as queryParams in the src attribute.
- The component should inject the form to the window as a global variable.

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
@KevinDavilaDotCMS have a demo

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by rjvelazco** [comment]
#### Passed Internal QA

- Tested on `master`

https://github.com/dotCMS/core/assets/72418962/1c20574a-5ce3-4d8c-b79c-2b1ffaacd59c
