### ISSUE TITLE
Edit Content: Expose Workflow Information Through Rest APIs

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26839]
### Parent
#25445 

### User Story
As a dotCMS user, I want to be able to view the workflow information and step a piece of content is currently in, so I can better understand the content lifecycle.

```[tasklist]
### Acceptance Criteria
- [x] Create a REST endpoint to return the workflow information for a piece of content.
- [x] Ensure the endpoint is secured and only accessible to authenticated users.
- [x] Add documentation on how the API works in the ticket so it can be documentaed by @jdcmsd
```

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- The API endpoint should be able to handle requests from any authenticated user.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
- Create a REST endpoint to return the workflow information for a piece of content: 5 hours 
- Ensure the endpoint is secured and only accessible to authenticated users: 2 hours

**Comment by fmontes** [comment]
![Image](https://github.com/dotCMS/core/assets/751424/efe69904-4387-49bd-82dc-eb9217d0dc3d)

**Comment by jcastro-dotcms** [comment]
### NOTE TO DOC:
This new Endpoint method returns the status of a specific piece of Content in the Workflow it is assigned to. In summary:

* The Workflow Scheme that the Contentlet is in.
* The Step that the Contentlet is in.
* The User assigned to such a Step

Here's an example of how to use this endpoint. You just need to pass down the Contentlet's Inode:
```
http://localhost:8080/api/v1/workflow/status/{contentletInode}
```
And you'll get a JSON response similar to the following:
```json
{
    "entity": {
        "scheme": {
            "archived": false,
            "creationDate": 1701967102513,
            "defaultScheme": false,
            "description": "",
            "entryActionId": null,
            "id": "d61a59e1-a49c-46f2-a929-db2b4bfa88b2",
            "mandatory": false,
            "modDate": 1701726850881,
            "name": "System Workflow",
            "system": true
        },
        "step": {
            "creationDate": 1701967102517,
            "enableEscalation": false,
            "escalationAction": null,
            "escalationTime": 0,
            "id": "ee24a4cb-2d15-4c98-b1bd-6327126451f3",
            "myOrder": 1,
            "name": "Draft",
            "resolved": false,
            "schemeId": "d61a59e1-a49c-46f2-a929-db2b4bfa88b2"
        },
        "task": {
            "assignedTo": "Admin User",
            "belongsTo": null,
            "createdBy": "e7d4e34e-5127-45fc-8123-d48b62d510e3",
            "creationDate": 1701964977839,
            "description": null,
            "dueDate": null,
            "id": "6793781b-be15-4c2b-8d13-313cc2802b16",
            "inode": "6793781b-be15-4c2b-8d13-313cc2802b16",
            "languageId": 1,
            "modDate": 1701964977840,
            "new": false,
            "status": "ee24a4cb-2d15-4c98-b1bd-6327126451f3",
            "title": "Test contentlet Workflow Status",
            "webasset": "b1956f0de7753de2ae281d9d4f117d28"
        }
    },
    "errors": [],
    "i18nMessagesMap": {},
    "messages": [],
    "pagination": null,
    "permissions": []
}
```

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_cf9b773**, Docker, macOS 13.0, FF v113.0
<img width="1134" alt="Screenshot 2024-01-10 at 2 55 07 PM" src="https://github.com/dotCMS/core/assets/129882031/c66fc5dc-70a4-4b06-bbca-6dbc13f74292">
