### ISSUE TITLE
Edit Content: Render Contentlet Information in Sidebar

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26838]
### Parent
#25445 

### User Story
As a dotCMS user, I want to be able to render the contentlet information in the sidebar of the new edit contentlet, so I can easily view and edit the information associated with the contentlet.

```[tasklist]
### Tasks
- [x] Create the sidebar and render the content as per the screenshot provided.
- [ ] If creating a new piece of content, render empty values.
- [ ] The sidebar should be sticky an only the long forms should scroll
```

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
<img width="865" alt="image" src="https://github.com/dotCMS/core/assets/751424/b8dc3f7f-92e4-4541-adc1-8ab6466d08e7">

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A
