### ISSUE TITLE
Edit Content: Test Run Custom Field

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26843]
### User Story 
As a developer, I want to be able to test run the custom field to prove our idea, so that I can develop the feature further. 

```[tasklist]
### Acceptance Criteria
- [x] Test all the custom field in the starter, [here is the list](https://github.com/dotCMS/core/assets/751424/f12a7ec3-f85b-4310-a842-3764f4023e1b)
- [x] Document the changes that were required to make them work
- [x] Document the ones that we couldn't make it work so we can find a fix or workaround
```

### Proposed Objective 
Core Features

### Proposed Priority 
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc. 
N/A

### Assumptions & Initiation Needs
- All the custom fields are properly configured. 

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by KevinDavilaDotCMS** [comment]
All fields, excep og-preview, were tested.
Og-Preview werent because needs a File Field, and we dont have it yet (But the logic is so similar to all tests).

We have three changes to test all other fields.

1. Replace dojo.byId('XXX') form form.get('XX'). Only to form elements from Angular
`      //Replace dojo.byId form form.get(). Only to form elements from Angular
      //   var x = dojo.byId("layout").value;
      var x = form?.get("layout").value ?? "";`
2. If you need to toggle screen to fullscreen, you can open a dialog with dojo as usual, and need to sent a postmessage to parent to turn on fullscreen.
`      dijit.byId("videoResultsDiv").show();
      window.parent.postMessage({ type: "toggleFullscreen" });`
3. If you need to pass a callback on dojo.load, you mus to embed it on settimeout (For now)
`<script type="text/javascript">
  dojo.addOnLoad(function () {
    setTimeout(() => {
      //   var x = dojo.byId("thumbnailLarge").value;
      var x = form?.get("thumbnailLarge").value ?? "";
      if (x != "") {
        //   var y = dojo.byId("url").value;
        var y = form.get("url").value;
        y = y.replace("watch?v=", "embed/");
        y = y.replace("http", "https");
        dijit.byId("thumbnailImage").set(
          "content",
          dojo.create("iframe", {
            src: y + "?rel=0",
            style: "border: 0; width: 100%; height: 100%",
          })
        );
      }
    }, 100);
  });
</script>`
