### ISSUE TITLE
Edit Content: Fix the tests for `dot-edit-content-field.component.spec`

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26884]
### Parent Issue

#25445 

### Task

The tests are not ok:

1. Not validating all the inputs
2. Using real component when we can mock it.
3. Adding a number of unneeded providers

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- [ ] [Mock](https://github.com/ngneat/spectator#mocking-components) all the components fields.
- [ ] Make sure you test all the inputs and not only "contentlets", we also have field
- [ ] Check if there is a way to assert `formControlName`
