### ISSUE TITLE
Edit Content: Implement suggestions in the tag fields

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#26902]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### User Story

As a user, I want to be able to add tags to fields based on the suggestion from the existing tags in the system.

```[tasklist]
### Tasks
- [x] Update the current field to hit the new endpoint
- [x] User should get suggestions from existing tags
- [x] User should be able to select tags using keyboard (up/down/enter) and mouse click
- [x] Suggestions should start showing until there is at least 3 chars in the input
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Assumptions & Initiation Needs

- Endpoint is working

### Sub-Tasks & Estimates

N/A
