### ISSUE TITLE
Edit Content: Thumbnail in the Binary Preview Punchlist

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26907]
### Parent
#25445 

### User Story
As a content creator, I want to be able to render PDF thumbnails in the binary preview, so I can easily identify PDF files.

```[tasklist]
### Tasks
- [x] Use the `/dA/<%=inode%>/<%=field.getVelocityVarName()%>/500mw/20q/<%=fileName%>` URL to render ALL image thumbnails
- [x] The thumbnail should be properly sized and rendered
- [x] The thumbnail should accurately reflect the content of the PDF
- [x] Label to show image width and height as W x H, not W,H
- [x] font size in monaco editor should  compute to 14px, not 12px
- [x] File size (Bytes) should be converted to kb/mb/gb based on the file size (meaning should be human friendly). Also bytes are not working locally for me. Is anyone else seeing this issue? (we can do a pipe)
- [x] To maintain consistency, use the `dot-content let-thumbnail` component in the Binary field
- [x] Enable editing when the user clicks on editable files.
- [x] Close Monaco Editor on `ESC` without closing the entire dialog
- [x] Enable save on Binary Field on the old Edit Content
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- The PDF file must be properly formatted
- Appropriate memory resources should be available

### Quality Assurance Notes & Workarounds
- Thumbnail should be properly rendered on all major browsers

### Sub-Tasks & Estimates
N/A

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_1894351**, Docker, macOS 13.0, FF v121.0.1
