### ISSUE TITLE
Edit EMA: Preview Page in Multiples Devices

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#26911]
### Parent
#26644 

### User Story
As a user, I want to be able to preview my page in different resolutions and also the RRSS cards, so I can get a better understanding of how my page will look when published.

```[tasklist]
### Acceptance Criteria
- [x] When user click the Preview button it should overlay the `dot-device-selector-seo.component` component
- [x] When user select a device it should resize the iframe to that device
- [x] When user click the `Open in New Tab` link it should open the users page in a new tab
```

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
N/A

### Assumptions & Initiation Needs
- This doesn't include the RRSS social media preview, we will create a new task for it.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Implement preview component: Estimate 8 hours
- Set selected sizes: Estimate 2 hours
