### ISSUE TITLE
Edit content: Research about state management strategy

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#27022]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### Task

Research about strategy for the state managment of Edit Content
```[tasklist]
### Tasks
- [ ] Research about state management alternatives (NgRx, Elf, Akita, etc)
- [ ] Implement state management on Edit Content
- [ ] Discuss about this topic with Frontend team
```

### Proposed Objective

Please Select

### Proposed Priority

Please Select
