### ISSUE TITLE
Edit EMA: Create Content Palette

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27061]
### Parent
#26644 

### User Story
As a user, I want to be able to create and reuse content in the new page editor, so I can quickly and easily edit my pages.

```[tasklist]
### Acceptance Criteria
- [ ] User should be able to DnD a content type to create a new content
- [ ] User should be able to DnD a contentlet to reuse a contentlet
- [ ] User should be able to search content types, wildcarded to `*query*`
- [ ] User should be able to search contentlets, wildcarded to `*query*`
- [ ] User should be able to paginate results
- [ ] If the user drop a element in a non-allowed or full container the endpoint return an error, show it in the toast
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
- [Prototype](https://www.figma.com/proto/trbwjLuf5F6KaU1rFucNeg/Edit-Page?page-id=1902%3A6704&type=design&node-id=1909-28315&viewport=-3068%2C392%2C0.74&t=WJcx09TbWAseiTib-1&scaling=scale-down&starting-point-node-id=1909%3A28315&mode=design)
- [Figma](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2286%3A9249&mode=design&t=URwW3xaIGPi02Qoo-1)

https://github.com/dotCMS/core/assets/751424/9bcc1b71-6403-495e-99d7-cf8edcd95fbe

### Assumptions & Initiation Needs
- The DnD behaviour is in place, here: https://github.com/dotCMS/core/blob/master/core-web/libs/portlets/dot-ema/src/lib/edit-ema-editor/edit-ema-editor.component.html#L53:L90
- Just need to provide the view and request the content from the endpoint
- The HTML of the elements needs the `data-attr` and it will work
- We already have a `dot-palette` component that if you think is easier o reuse is fine, but you can create it from scratch in the edit ema, BUT you can check for the endpoints URL there.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
N/A

**Comment by fmontes** [comment]
![Image](https://github.com/dotCMS/core/assets/751424/1ca6a040-b9e7-4890-94d2-533884185544)

When you finish those, please ping Melissa and show her.

**Comment by melissarojas-dotcms** [comment]
Also, please check the icon and text colors, as they are set to "Gray Scale 900"

![image](https://github.com/dotCMS/core/assets/150382008/f4d9e978-482c-48ba-b5c0-7c58b78afb2f)
