### ISSUE TITLE
Edit EMA: Add styling to the contentlet toolbars

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27076]
### Parent
#26644 

### User Story
As a dotCMS user, I want to have the ability to add content, widgets, and forms to a page, so I can have a more streamlined way of managing my content and UI elements.

> [!IMPORTANT]
> Right now we have the "add" button in the container level, we need to move that to the contentlet top and botto, because that will give us the position within the content type to add the new content.

> [!NOTE]
> All the styling should be pure native CSS. Because want to avoid css colission we need to try to move this to the shadow dom, here is a library we can try: https://www.npmjs.com/package/react-shadow.

> [!NOTE]
> Because I want to keep this as native as possible to show the popover menu (add button options), we can try to use the popover API: https://caniuse.com/?search=popover

```[tasklist]
### Acceptance Criteria
- [ ] User should be able to add content top or bottom of another contentlet
- [ ] User should be able to add content, forms and widgets
- [ ] The buttons for code and drag is out of this scope
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
- [Prototype](https://www.figma.com/proto/trbwjLuf5F6KaU1rFucNeg/Edit-Page?page-id=1902%3A6704&type=design&node-id=1909-28315&viewport=-3068%2C392%2C0.74&t=sw2h0huHLCJCUb5D-1&scaling=scale-down&starting-point-node-id=1909%3A28315&mode=design)
- Figma: [One](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2341%3A9115&mode=design&t=OcEBZIlGrr65j4xf-1), [Two](https://www.figma.com/file/trbwjLuf5F6KaU1rFucNeg/Edit-Page?type=design&node-id=2286%3A9249&mode=design&t=OcEBZIlGrr65j4xf-1)

![Contentlet](https://github.com/dotCMS/core/assets/751424/61f3f30b-126b-44da-8438-4b52f70f9010)

### Assumptions & Initiation Needs
We already have an action in place that will add a contentlet in a specific position of a contentlet, here is the interface:

```typescript
export interface ActionPayload {
    container: ContainerPayload;
    contentlet?: ContentletPayload;
    language_id: string;
    pageContainers: PageContainer[];
    pageId: string;
    personaTag?: string;
    position?: 'before' | 'after';
    newContentletId?: string;
}
```

More: `core-web/libs/portlets/dot-ema/src/lib/shared/models.ts`

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Design the dropdown options and popover: 2 hours
- Implement the dropdown

**Comment by fmontes** [comment]
The solution of adding this tooling to the react lib will not work. After testing I realized that we will have css issues and also we will have to redo this lib for each framework.

So instead, I will do the same approach we did in the dropzone, on hover and stuff.
