### ISSUE TITLE
Edit EMA: Share Edit Page URL with Variants

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27077]
### Parent
#26644 

### User Story
As a dotCMS user, I want to be able to share the edit page url with all the variants at all times, so I can easily collaborate with other users.

```[tasklist]
### Acceptance Criteria
- [x] If user goes to `/edit-ema` we should redirect to `/edit-ema?url=index&com.dotmarketing.persona.id=modes.persona.no.persona&language_id=1`
- [x] When user change the language selector the url should reflect
- [x] When user change the persona selector the url should reflect
- [x] When user browse internally in the page the url should reflect
- [x] The iframe should always have the same queryparams as angular one
- [x] If user remove one queryparams, we should try to recover to default
```

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
N/A

### Assumptions & Initiation Needs
- The user should have the necessary permissions to view and edit the page. 

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Ensure the page and url are in sync
- Create a fallback for any missing params
