### ISSUE TITLE
Edit EMA: Allow Users to Add Widgets to Pages

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27112]
### Parent
#26644 

### User Story
As an end user, I want to be able to add widgets to pages so that I can create dynamic content.

```[tasklist]
### Acceptance Criteria
- [ ] User should be able to click `+ > Widget` and search for widgets
- [ ] User should be able to click select in the dialog and insert the widget
- [ ] User should be able to insert the Wiget in any position based on the `+` button clicked
``` 

### Proposed Objective
Core Features

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:

https://github.com/dotCMS/core/assets/751424/9bd2f081-444f-4c9e-999e-1ab7a2fd8471

### Assumptions & Initiation Needs
- Widgets should be added using the same dialog and iframe as contentlets

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Research existing code for widget adding
- Create iframe filtering for widgets
- Test and debug widget adding
