### ISSUE TITLE
Edit EMA: Respect User Permissions

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27135]
### Parent
#26644 

### User Story 
As a dotCMS user, I want to view and edit a page while respecting my user permissions, so I can access the page and its content securely.

```[tasklist]
### Acceptance Criteria 
- [ ] If the user has no permission to view the page, show an error dialog.  (use the error handler service) 
- [ ] If the user has permission to view but not edit the page `canEdit: false`, hide the palette and the contentlets tools on hover, disable layout and rules buttons from the sidenav
- [ ] Show something to tell the user that they have no permission to edit. (Figma coming, add something to the toolbar)
``` 

### Proposed Objective
Core Feature

### Proposed Priority
Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
In the page API response, we have `page.canEdit` we should use that.

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
- Design a way to convey to the user that they have no permission to edit the page. 
- Create an error handler service for when the user has no permission to view the page.
- Hide the palette when the user has permission
