### ISSUE TITLE
Edit Page: Edit Contentlet Dialog Language Support

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27297]
### User Story
As a dotCMS user, I want the edit contentlet dialog to open in the language I am currently editing the page in, so that I can easily add content in the correct language.

```[tasklist]
### Acceptance Criteria
- [ ] When editing a page in X language, opening the edit contentlet dialog should display the dialog in X.
- [ ] When editing a page in X language, opening the add contentlet dialog should display the dialog in X.
- [ ] The language of the edit contentlet dialog should be synchronized with the language of the page being edited
```

### Proposed Objective
Static content: "Core Features"

### Proposed Priority
Static content: "Priority 3 - Average"

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
Static Content: "N/A"

### Assumptions & Initiation Needs
- The user is editing a page and wants to add content in the same language.
- The language settings of the page and the user's preferences are correctly configured.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates:
- Implement language detection in the edit contentlet dialog (2 hours)
- Synchronize the language of the dialog with the

**Comment by hmoreras** [comment]
QA Note: 

The language should be consistent when editing the content, create a new one from the "+" button or doing drag & drop from the content palette. 

https://github.com/dotCMS/core/assets/31667212/29a14919-5671-47db-97bb-3ca4de4df60f

**Comment by dsilvam** [comment]
Passed Internal QA: Keeping the selected language when editing existing content or creating new one from the different locations shown in the video above.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_5973727 **, Docker, macOS 13.0, FF v121.0.1
