### ISSUE TITLE
Edit EMA: Prepare to send to QA

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27310]
### Parent Issue

#26644 

### Task

We need to send edit ema to QA ASAP.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- [ ] Provide a vercel instance to QA
- [ ] Create a ticket explaining what to test and what to expect
- [ ] Deploy the latest master to QA server
- [ ] Make it happen

**Comment by zJaaal** [comment]
Edit EMA is running on production at the moment.
