### ISSUE TITLE
Edit Content: Enable Beta Version per Content Type

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27339]
### Parent
#25445 

### User Story
As an admin user, I want to be able to enable the beta version of the edit content screen on a per content type basis, so that I can test and provide feedback on the new features before they are fully released.

```[tasklist]
### Tasks
- [ ] There should be a checkbox on the edit content types screen to enable or disable the beta version for each content type.
- [ ] The enable or disable status should be stored as a new property for each content type.
- [ ] When the beta version is enabled for a content type, a top bar should be added to the edit content screen to indicate that it is a beta version.
```

### Proposed Objective
Static content: "Core Features"

### Proposed Priority
Static content: "Priority 3 - Average"

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- [Edit Content Type](https://www.figma.com/file/G1iEGWtWpnD2rwDcckJc58/Content-Types?type=design&node-id=1035%3A7574&mode=design&t=UZFVkVpxgyaks83i-1)

![image](https://github.com/dotCMS/core/assets/751424/1b084670-242a-4939-887b-c683f180373c)

- In the new edit content screen it self

![image](https://github.com/dotCMS/core/assets/751424/dbbc2fba-8b29-4e40-979e-f22415c585bc)

### Assumptions & Initiation Needs
- The beta version of the edit content screen has already been developed and tested.
- The designs for the top bar in the edit content screen have been provided.
- Content types now have a new `metadata` property, you can add a key/value pair there to store the beta active flag.
- Features flags from dotCMS properties are in place.

### Quality Assurance Notes & Workarounds
- Check that the checkbox to enable or disable the beta version appears on the edit content types screen.

**Comment by fmontes** [comment]
Needs work: all the checkbox label should be clickable, use label for or something around it.

**Comment by hmoreras** [comment]
Created a new task for the feedback. https://github.com/dotCMS/core/issues/27522

**Comment by bryanboza** [comment]
Fixe, after enable the following feature flag, now we are able to enable the new edit mode beta in the content type 

```
      "DOT_CONTENT_EDITOR2_ENABLED": 'true'

```



![Image](https://github.com/dotCMS/core/assets/2641437/220d9ca0-116f-491a-af0c-1e1bb0f35cb5)
