### ISSUE TITLE
Edit EMA: Add Notification for Duplicate Contentlet Addition

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27335]
### Parent
#26644

### User Story
As a dotCMS user, I want to be notified when I try to add the same contentlet twice to the same container so that I am aware that it is not possible.

```[tasklist]
### Tasks
- [x] When a user tries to add a contentlet that already exists in a container, a toast notification should be displayed.
- [x] The toast notification should inform the user that the contentlet cannot be added again.
- [x] The notification should be visually distinguishable and easily noticeable.
- [x] The notification should disappear automatically after a few seconds.
```

### Proposed Objective
Static content: "Core Features"

### Proposed Priority
Static content: "Priority 3 - Average"

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.:
We already have a `catchError` in the `savePage` request because it is failing silently.

### Assumptions & Initiation Needs
- The user should have appropriate permissions to add contentlets to containers.
- The system should be able to detect duplicate contentlets in a container.

### Quality Assurance Notes & Workarounds
- Verify that the toast notification is displayed when trying to add a duplicate contentlet.
- Confirm that the notification clearly states that the contentlet cannot be added again.
- Ensure that the notification disappears automatically
