### ISSUE TITLE
Edit EMA: QA Tracking

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27350]
### Parent Issue

#26644 

```[tasklist]
### Task
- [ ] This is issue is to track the QA efforts.
- [ ] Anything you find please leave it here as comments
- [ ] Read the "Known issues"
- [ ] Read the "Not doing in this version"
- [ ] Read the "How to run"
```

### Known issues:

1. ~Limited users can't edit the page~
2. ~The Loading indicator gets stuck when try to go to a page that ends in `/index` for example `/members/index`~
3. ~There is a bug when select a contentlet from the add screen, the dialog don't close and there is an error in the console~
4. There is a bug when create a contentlet it changes the window title
5. ~Can't do "Push Publish" from the workflow actions~
6. ~Can't do "Move" from the workflow actions~
7. ~Design of the toast is broken~
8. Right nav bar buttons have no hover state
9. ~When select a persona and navigate internally, we keep the persona selected when the new page might not have a personalized version.~
10. ~Loading indicator stuck when try to edit a `urlContentMap` page~

### Not doing in this version

1. Drag and drop contentlet between containers
2. Drag and drop images from the file system
3. Open Edit contentlet in the selected language
4. Inline editing
5. Edit contentlet for this page or all
6. Bookmarks page thumbnails
7. Add Personas from Persona Selector
8. Navigation reorder
9. Preview Social Media Cards
10. Breadcrumbs in the top bar
11. Keep the sidenav open

### How to run

1. Go to https://dotcms-qa-master.dotcms.site/dotAdmin/
2. Go to Apps > EMA - Edit Mode Anywhere Next
3. Add configurations to the `demo.dotcms.com` site

```
{
  "config": [
    {
      "pattern": ".*",
      "url": "https://nextjs-example-sigma-five.vercel.app"
    }
  ]
}
```

The pattern is a `regex` to match the url of the page, you can do like `"pattern":"/blog/(.*)"` and the new editor will only show to the pages inside `blog` folder.

The url `https://nextjs-example-sigma-five.vercel.app` is the demo app we deployed in vercel, you need to use that so you don't have to build it yourself.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Priority 3 - Average

**Comment by bryanboza** [comment]
Styling problems: https://github.com/dotCMS/core/issues/27684

**Comment by bryanboza** [comment]
EMA - Edit Mode Anywhere Next app needs to have a validation, if you try to save some configuration at apps leve, it should try to ping the server and if don't have response we need to return an error.

**Comment by bryanboza** [comment]
Unable to edit the main content of the index page 
Here is the log: https://gist.github.com/bryanboza/40363c78fb2d276f80437cfff25454c2

![Image](https://github.com/dotCMS/core/assets/2641437/3ac24174-4d6e-4908-9f5d-fc2ea9fd366e)

**Comment by bryanboza** [comment]
We are always showing the live version of the content instead the working version. When you try to edit a page we need to show the last versions of the content. 

https://github.com/dotCMS/core/assets/2641437/48829e82-4f30-4052-9738-603415e7bdde

**Comment by bryanboza** [comment]
We are not rendering new added contents to the page, If I open the page and add a new baner content we should be able to render that pice of content without problems 

https://github.com/dotCMS/core/assets/2641437/0fb09c39-1b85-4a8b-8028-d9530485cf89

**Comment by bryanboza** [comment]
We have problems CSS problems on FF when you configure this server: 



![Image](https://github.com/dotCMS/core/assets/2641437/1ac686a8-6aae-43e8-a2ff-2b41356a270e)

**Comment by fmontes** [comment]
> We have problems CSS problems on FF when you configure this server:
> 
> ![Image](https://private-user-images.githubusercontent.com/2641437/314670965-1ac686a8-6aae-43e8-a2ff-2b41356a270e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDQ3ODksIm5iZiI6MTcxMjg0NDQ4OSwicGF0aCI6Ii8yNjQxNDM3LzMxNDY3MDk2NS0xYWM2ODZhOC02YWFlLTQzZTgtYTJmZi0yYjQxMzU2YTI3MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTQwODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJiOWJkODdjMzczNDMwMTIwYmUzMGIzMGRmZmU1ZWI4ZTY2ODFjNmNkZmVhNmE4YTkzZDcyZmU2NTY2MTE4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f3hug2WDSjt0p1rt_6biBxQjGF4M6qmNhKiwXkuyTxE)

Fixed here: https://github.com/dotCMS/core/issues/28024

**Comment by fmontes** [comment]
> Styling problems: [#27684](https://github.com/dotCMS/core/issues/27684)

Fixed here https://github.com/dotCMS/core/issues/28024

**Comment by fmontes** [comment]
> Unable to remove contents from the page, when I try to remove a pice of content we are not doing anything and we are not. removing the content neither, no errors in the log or in console
> 
>  Screen.Recording.2024-02-21.at.1.09.05.PM.mov

Fixed on the vercel redeploy.

**Comment by fmontes** [comment]
> We are always showing the live version of the content instead the working version. When you try to edit a page we need to show the last versions of the content.
> 
>  Screen.Recording.2024-02-21.at.1.19.55.PM.mov

We talked about this and is because page API have no cache, is a known issue.

**Comment by fmontes** [comment]
> We are not rendering new added contents to the page, If I open the page and add a new baner content we should be able to render that pice of content without problems
> 
>  Screen.Recording.2024-02-22.at.10.25.21.AM.mov

This was due a bad setting, you can't have the vercel deploy pointing to a different environment, vercel deploy will onlt work with QA master env.

**Comment by fmontes** [comment]
> Unable to edit the main content of the index page Here is the log: https://gist.github.com/bryanboza/40363c78fb2d276f80437cfff25454c2
> 
> ![Image](https://private-user-images.githubusercontent.com/2641437/306745944-3ac24174-4d6e-4908-9f5d-fc2ea9fd366e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDQ4ODAsIm5iZiI6MTcxMjg0NDU4MCwicGF0aCI6Ii8yNjQxNDM3LzMwNjc0NTk0NC0zYWMyNDE3NC00ZDZlLTQ5MDgtOWY1ZC1mYzJlYTlmZDM2NmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTQwOTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJlNDA5ODZmMjBlZjhhYzY0YmZkZTQ3Zjg5NWIzMGI4NzA3NWU4YzFjZmQxZWU3NGExZWYyZGNlMzgwZTk1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZWBz9AmXiDG9k0zc_gx2cvTv9tj_f8lkDQ6gyCqu3io)

Probably same thing of pointing vercel to a localhost please confirm.

**Comment by fmontes** [comment]
> EMA - Edit Mode Anywhere Next app needs to have a validation, if you try to save some configuration at apps leve, it should try to ping the server and if don't have response we need to return an error.

Yes, but not in the scope.

**Comment by bryanboza** [comment]
We can close this for now, all the feedback was moved to new cards... 

Last case added for a gardening day here #28793
