### ISSUE TITLE
Create GH User for CI/CD

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27392]
### Task

There's a need for a new GH User to be used to run the different GH actions on the CICD pipeline.
It will need a PAT with limited scope, including pushing to master. This one the `CICD_GITHUB_TOKEN` can go away.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

* New GH User for CICD created
* User has a PAT with the proper limited scope, including pushing to master.
* `CICD_GITHUB_TOKEN` is removed

```[tasklist]
### Tasks
- [ ] Create new secrets in core repo
- [x] Create new github user to be our machine user
- [x] Store credentials for new machine user in password DB
- [ ] Update references in github actions
- [ ] Cleanup: Delete old secrets in core repo
```

**Comment by erickgonzalez** [comment]
Keep in mind that when we remove all existing PAT it will affect LTS as well

**Comment by sfreudenthaler** [comment]
> * [x]  Add the new machine user to our dotCMS github org
> *

Note on this one that I just added to the org.  I did not add to any existing group because none stood out as an obvious fit

**Comment by sfreudenthaler** [comment]
We created new secrets in core repo
* `CI_MACHINE_USER`
* `CI_MACHINE_TOKEN`

![image](https://github.com/dotCMS/core/assets/31257998/ac7c2e59-f0f2-4ac5-b082-b33587218962)

**Comment by sfreudenthaler** [comment]
All set... A few notes here

FYI @cobbg and @mbiuki 

1. Key rotation should be easy (just update the `CI_MACHINE_TOKEN` value and voilà, but it's not automated so rotation will be manual at this point in time
2. The credentials, MFA, and PAT for the github account are stored in Keeper under the `GitHub Machine User` folder.  All of the cloud engineering team has access to it.  You can ask them for help if you need to get into the account for whatever reason.
3. Scope of the PAT was limited to `repo:status`, `repo_deployment`, and `public_repo`
4. We granted the machine user `Writer` role to the core repo.

**Comment by erickgonzalez** [comment]
> > Keep in mind that when we remove all existing PAT it will affect LTS as well
> 
> Oh good point @erickgonzalez . So the existing ones would work till we nuked victors old PATs. But I should add that to the scope of this ticket.
> 
> As for making sure things keep working... What's the playbook to update the LTS pipelines? Are they just more places in the yaml on `master`? Or do I have to go into a specific branch and put up a PR there?

I think @victoralfaro-dotcms is the one can answer this better

**Comment by sfreudenthaler** [comment]
Also added secrets to [plugin-seeds repo](https://github.com/dotCMS/plugin-seeds/settings/secrets/actions) by slack request from @victoralfaro-dotcms and @dsilvam 
* CI_MACHINE_USER
* CI_MACHINE_TOKEN

**Comment by sfreudenthaler** [comment]
Request by @victoralfaro-dotcms to alos add the secret to the [enterprise repo](https://github.com/dotCMS/enterprise)

**Comment by sfreudenthaler** [comment]
> Request by @victoralfaro-dotcms to alos add the secret to the [enterprise repo](https://github.com/dotCMS/enterprise)

✅ Done

**Comment by sfreudenthaler** [comment]
added `workflow` permission to the existing token by @victoralfaro-dotcms's request
