### ISSUE TITLE
Test AI Workflow Actions

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27439]
### Parent Issue

https://github.com/dotCMS/core/issues/27437

### Task

The AI Workflow Actions included as a part of the AI Plugin needs to be tested. These include:

- [x] **OpenAI Embeddings** (`DotEmbeddingsActionlet`) This actionlet uses OpenAI to generate and save (or delete) the embeddings for content. This is used so that an embedding index can be kept up to date as new content is published and/or unpublished from dotCMS.
- [x] **OpenAI Content Prompt** (`OpenAIContentPromptActionlet`). This actionlet can be called to automatically populate/update fields of content as the content is pushed through a workflow. It works by expecting OpenAI to return its data/answer in a json format which will then be used to update the content. The example usage is to post content to OpenAI and have OpenAI automatically write appropriate SEO title and SEO short description for the content.
- [x] **OpenAI Generate Image** (`OpenAIGenerateImageActionlet`). This actionlet can automatically generate an image based on a content prompt. This content prompt is a velocity template and can use the values of the content in it. By default, this actionlet will add this image to the first binary field in the content.
- [x] **OpenAI Auto Tag Content** (`OpenAIAutoTagActionlet`). This actionlet can automatically tag content based on its values.

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

All of the functionality in the task definition needs to be fully tested.

**Comment by hmoreras** [comment]
QA Note: check the videos in the task https://github.com/dotCMS/core/issues/27473 it gives indication of how to test the Embeddings. the other scenarios, are sub-taks in the workflow page that need to be configure as needed, as shown in the screenshot: 
<img width="1353" alt="image" src="https://github.com/dotCMS/core/assets/31667212/84c67260-9f7a-4880-8651-040d7fee5ae6">

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_4c1485a**, Docker, macOS 13.0, FF v121.0.1

https://github.com/dotCMS/core/issues/27511 
https://github.com/dotCMS/core/issues/27508

**Comment by dsilvam** [comment]
@josemejias11 This one is ready to be retested I think.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b4779ec**, Docker, macOS 13.0, FF v121.0.1
