### ISSUE TITLE
Test dotAI Portlet/Tool in LTS

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27438]
### Parent Issue

https://github.com/dotCMS/core/issues/27437

### Task

The dotAPI Portlet/Tool included as a part of the AI Plugin needs to be tested. 

<img width="1438" alt="Screenshot 2024-01-25 at 3 25 02 PM" src="https://github.com/dotCMS/core/assets/1576794/0215131a-10c0-464d-b68d-d9385d5a07e3">

The testing needs to cover: 

- [ ] Search and Chat with Content ("Search and Chat with dotCMS" tab)
- [ ] Generate and Save new AI Images ("Image Playground" tab)
- [ ] View/Update/Delete Content Embedding Indexes  ("Manage Embeddings/Indexes" tab)
- [ ] View AI Plugin configuration values. These are important because they can override and parameterize the prompts that we send to OpenAI. ("Config Values" tab)

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

All of the functionality in the task definition needs to be fully tested.

**Comment by oidacra** [comment]
IQA Passed:
## Search and Chat with dotCMS
    - Semantic Search ✅
 
<img width="2925" alt="Screenshot 2024-01-26 at 11 42 07 AM" src="https://github.com/dotCMS/core/assets/1909643/53d528bd-c8ac-46d5-9b76-25f368a570ab">

    - Streaming Chat ✅
    
<img width="1558" alt="Screenshot 2024-01-26 at 10 53 14 AM" src="https://github.com/dotCMS/core/assets/1909643/9f837e3d-3efe-4b40-a820-6ff35ee183b9">

    - REST/JSON ✅
<img width="1575" alt="Screenshot 2024-01-26 at 10 54 09 AM" src="https://github.com/dotCMS/core/assets/1909643/fe566208-be1e-4a52-96bd-02c22476e446">

## Image Playground
- Square
<img width="1677" alt="Screenshot 2024-01-26 at 10 13 51 AM" src="https://github.com/dotCMS/core/assets/1909643/e0fe35d4-60cf-4ee1-b170-2f79f964a595">

- Vertical
<img width="1622" alt="Screenshot 2024-01-26 at 10 13 16 AM" src="https://github.com/dotCMS/core/assets/1909643/32cf3721-201c-46ce-977d-7ef8798b7fec">

- Horizontal
<img width="1702" alt="Screenshot 2024-01-26 at 10 12 34 AM" src="https://github.com/dotCMS/core/assets/1909643/0d6dd03b-d745-44a8-8e15-b8ebd8a1f192">

## Manage Embeddings/Indexes
Works as expected
<img width="2639" alt="Screenshot 2024-01-26 at 11 46 03 AM" src="https://github.com/dotCMS/core/assets/1909643/1f9c7411-fab3-4f34-b227-382513ed00b9">

## Config Values

Get the config from the APP

<img width="2893" alt="Screenshot 2024-01-26 at 11 38 07 AM" src="https://github.com/dotCMS/core/assets/1909643/86c97e71-60af-47f6-9b61-5c3ac5adfc7f">

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_4c1485a**, Docker, macOS 13.0, FF v121.0.1

Cards added.

https://github.com/dotCMS/core/issues/27507
https://github.com/dotCMS/core/issues/27505
https://github.com/dotCMS/core/issues/27443

**Comment by dsilvam** [comment]
@josemejias11 this one is ready to be tested again.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_b4779ec**, Docker, macOS 13.0, FF v121.0.1

**Comment by oidacra** [comment]
IQA Passed
Work as expected in 23.10 LTS
<img width="1462" alt="Screenshot 2024-02-28 at 12 12 26 PM" src="https://github.com/dotCMS/core/assets/1909643/eb745dfd-18f6-43c5-9a7c-6c2ba0617882">
<img width="1468" alt="Screenshot 2024-02-28 at 12 12 22 PM" src="https://github.com/dotCMS/core/assets/1909643/d0391cfd-01db-4f21-8b66-0c581723b103">

**Comment by josemejias11** [comment]
Added card https://github.com/dotCMS/core/issues/27903

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_439c2a4**, Docker, macOS 13.0, FF v121.0.1
