### ISSUE TITLE
Test AI Velocity Viewtools

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27440]
### Parent Issue

https://github.com/dotCMS/core/issues/27437

### Task

The AI Velocity Viewtools included as a part of the AI Plugin needs to be tested. These include:

- [x] `$ai` can be used to generate content and/or images from a prompt.
- [x] `$ai.embeddings` - list embedding indexes, generate embeddings from a prompt, count the tokens in a prompt.
- [x] `$ai.search` - semantically search an index of embedded content. Also can be used to pull a list of content that is semantically related another piece of content.
- [x] `$ai.completions` - generate completions based on a content query. Can also be used to do a raw OpenAI request.

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

All of the functionality in the task definition needs to be fully tested.

**Comment by dsilvam** [comment]
Passed Internal QA. Went through all viewtools. Had to send some fixes which are now merged.

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_4c1485a**, Docker, macOS 13.0, FF v121.0.1

Added card.

https://github.com/dotCMS/core/issues/27507

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_a38321e**, Docker, macOS 13.0, FF v121.0.1
