### ISSUE TITLE
Implement AI image generation for Binary fields

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#27458]
The AI plugin currently supports generative AI in the block editor, including creation of AI-generated images.

We need to duplicate the image generation capabilities of the AI Image block for the standard Binary field in the content editing screen.

### User Story

As a Content Architect in dotCMS, I want to generate a image with AI in the  Binary Field.

![image](https://github.com/dotCMS/core/assets/7611944/a3191559-a923-4f69-bf74-dfaeeaed04c8)

![Screenshot 2024-06-17 at 11 19 51 AM](https://github.com/dotCMS/core/assets/7611944/75648ff8-870f-43f8-8b53-3e05095de4f6)

### Acceptance Criteria

- If dotAI is not configured, the options should be disabled, and a mouse-over should have a message something like "Please configure dotAI to enable this feature".
- The current option to generate the image from existing content should be disabled.
- Like the Block Editor field, once the image is generated and accepted, it just becomes a normal image.  So, dotAI doesn't come into play when the image is edited.
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/28703
- [ ] https://github.com/dotCMS/core/issues/28953
- [ ] https://github.com/dotCMS/core/issues/28954
- [ ] https://github.com/dotCMS/core/issues/28955
- [ ] https://github.com/dotCMS/core/pull/29145
- [ ] https://github.com/dotCMS/core/pull/29159
```

**Comment by oidacra** [comment]
Waiting for https://github.com/dotCMS/core/issues/28703 Spike

**Comment by hmoreras** [comment]
IQA scenarios tested: 

Based on Nico's comment: 

Case 1, 2 and 3 in the old and new editor: Pass IQA. 
Cases 4 and 5: pass IQA. 

Couple of details notice: 

1. Links and buttons in the binary field should be the same as the others fields . 
<img width="1645" alt="image" src="https://github.com/dotCMS/core/assets/31667212/a834f14f-db62-44d6-8684-887143ce6fc1">

2. There is a small jum when you open the ai image dialog from the binary field, do not happens from the block editor. 

https://github.com/dotCMS/core/assets/31667212/4d27361e-4ed3-4011-a49f-6b55be97e1bc

**Comment by nicobytes** [comment]
Fix the problem with the colors and other bugs, but in this case: **There is a small jump when you open the ai image dialog from the binary field, does not happen from the block editor.** I need to solve this issue in another PR because I need more research about this behavior.

**Comment by hmoreras** [comment]
QA note: feedback #2 in my last comment will be worked here: https://github.com/dotCMS/core/issues/29173
