### ISSUE TITLE
Edit Content: Research on Customizations in dotCMS for TinyMCE Library

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27519]
### Parent
#25445 

### Task Description
As a developer working on implementing a new version of the TinyMCE library in the new edit content, I need to research the existing customizations in dotCMS and ensure that we add the same customizations for retro compatibility.

Our goal is to identify the plugins we currently use and determine if these plugins are compatible with the latest version of TinyMCE. We also want to list and describe any custom modifications we've made. Lastly, we need to confirm if the new version of TinyMCE can support the field variables mentioned in the dotCMS WYSIWYG documentation.

TinyMCE 6 is under MIT license, which means we can use it: https://www.tiny.cloud/get-tiny/#self-hosted

Ask @bryanboza to see if we are not missing anything here.

```[tasklist]
### Acceptance Criteria
- [x] The list of plugins currently being used in dotCMS is documented.
- [x] A thorough check is performed to determine if the plugins used in dotCMS are available for the latest version of TinyMCE.
- [x] Any custom customizations made to the existing TinyMCE implementation in dotCMS are identified and described in detail.
- [x] The compatibility of field variables mentioned in the dotCMS WYSIWYG documentation with the new version of TinyMCE is confirmed.
- [x] A report is generated summarizing the findings of the research, including the plugins used, compatibility status, and custom customizations.
- [x] We need to check image management, add, edit etc... DnD images from file system and custom prefix hosts
- [x] Links to dotCMS pages, and the ability to add prefix host to those links
```

**Comment by fmontes** [comment]
One option:

1. We can update tinymce in the jsp (using CDN)
2. Check if the plugins work with the latest version
3. If it doesn't work, note what we need to take care of.

**Comment by rjvelazco** [comment]
After research, we found that most tinyMCE v4 editor plugins are compatible with tinyMCE v6. Check the following `json`
```json
{
  "supported": ["advlist", "autolink", "lists", "link", "image", "charmap", "preview", "anchor", "pagebreak", "searchreplace", "wordcount", "visualblocks", "visualchars", "code", "fullscreen", "insertdatetime", "media", "nonbreaking", "save", "table", "directionality", "emoticons", "template"],
  "noSupported": ["colorpicker", "contextmenu", "textcolor"], 
  "moveToCore": ["print", "paste", "hr"], 
  "moveToOption": ["textpattern"], 
  "premiunPlugins": ["a11ychecker"],
  "dotCustom": ["dotCustomButtons", "dotimageclipboard"]
}

```

**Comment by rjvelazco** [comment]
## Important

Starting in early 2024, tinyMCE will require a valid API key. Without a valid API key, your editor will transition to read-only mode, limiting your ability to make changes. [docs](https://www.tiny.cloud/docs/tinymce/latest/invalid-api-key/)


### [How can I get an API key?](https://www.tiny.cloud/docs/tinymce/latest/invalid-api-key/#how-can-i-get-an-api-key)
The Admin who owns your TinyMCE implementation will need to log in [here](https://www.tiny.cloud/my-account/integrate/) to get your account’s API key. If you do not have an account yet, you can [sign up for a free API key](https://www.tiny.cloud/pricing/). Paid users can [contact our Technical Support](https://www.tiny.cloud/contact/) team for help.
