### ISSUE TITLE
Epic: Implementation of Experiment Runs within Single Page Application (SPA) Framework

### ISSUE THREAD

**Issue by oidacra** [dotCMS/core#27539]
### User Story

As a product owner, I want the ability to run experiments seamlessly within our Single Page Application (SPA) to improve user experience and facilitate robust A/B testing capabilities.

### Acceptance Criteria

- Integration of SPA experiment tracking with the existing dotCMS experiment
- Seamless tracking of goals and events in the SPA as currently functions in dotCMS.
- Ensure the SPA sends and receives data to and from the dotCMS backend without discrepancies.
- Maintain the integrity and performance of the SPA while implementing advanced tracking features.
- Detailed documentation on the integration process and any new SPA experiment tracking features.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

```[tasklist]
### Sub-Tasks
- [ ] https://github.com/dotCMS/core/issues/27536
- [ ] https://github.com/dotCMS/core/issues/27570
- [ ] https://github.com/dotCMS/core/issues/27603
- [ ] https://github.com/dotCMS/core/issues/27642
- [ ] https://github.com/dotCMS/core/issues/27882
- [ ] https://github.com/dotCMS/core/issues/27890
- [ ] https://github.com/dotCMS/core/issues/27888
- [ ] https://github.com/dotCMS/core/issues/28063
- [ ] https://github.com/dotCMS/core/issues/28228
- [ ] https://github.com/dotCMS/core/issues/27905
- [ ] https://github.com/dotCMS/core/issues/28045
- [ ] https://github.com/dotCMS/core/issues/28215
- [ ] https://github.com/dotCMS/core/issues/28229
```
