### ISSUE TITLE
Edit Page V2: Enable Feature Flag for New Edit Mode

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27547]
### Parent
#27546

### Task description
As a dotCMS user, I want to be able to enable or disable the new edit mode in VTL rendered pages using a feature flag. 
This allows me to test and gradually transition to the new edit mode without affecting the functionality of existing pages.

![Lunik Q1 2024 Frame 1](https://github.com/dotCMS/core/assets/751424/5e370981-a47d-430c-993c-92d217792ac4)

```[tasklist]
### Acceptance Criteria
- [ ] The new edit mode should be able to load VTL pages inside its iframe when the feature flag is ON
- [ ] Load the `page.rendered` code from the page api into the iframe using Blob.
- [ ] All redirects to the edit page should work as intended.
```

```javascript
// Step 1: Create the content
var htmlContent = '<!DOCTYPE html><html><body><h1>Hello, World!</h1></body></html>';

// Step 2: Create a Blob from the content
var blob = new Blob([htmlContent], { type: 'text/html' });

// Step 3: Create a Blob URL
var blobUrl = URL.createObjectURL(blob);

// Step 4: Set the Blob URL as the iframe source
var iframe = document.createElement('iframe');
document.body.appendChild(iframe);
iframe.src = blobUrl;

```

### External Links
None

### Assumptions & Initiation Needs
- The new edit mode has already been implemented and is functional.
- A feature flag system is already in place in dotCMS.
- Editing functionality will not be available at this point.

### Quality Assurance Notes & Workarounds
- The QA team should ensure that the new edit mode correctly loads VTL pages.
- Any issues with redirects to the edit page should be noted and reported for further investigation.

### Sub-Tasks & Estimates
- Implement feature flag system for new edit mode
- Update VTL rendering to work within the new edit mode
- Test and verify correct loading of VTL pages in new edit

**Comment by fmontes** [comment]
The FF is `FEATURE_FLAG_NEW_EDIT_PAGE`

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Tested on Docker: [`dotcms:master_02502b3`]

#### Scenarios

##### FF disabled

https://github.com/dotCMS/core/assets/72418962/da73c05c-7124-40ec-89b2-58a23ad7d34d

##### FF Enabled

https://github.com/dotCMS/core/assets/72418962/ef3fd4e1-4dcd-4826-9bca-4111063f1af2

##### FF Enabled: Headless and VTL Pages

https://github.com/dotCMS/core/assets/72418962/2e4a4499-ac42-44f1-b589-a51ca6122927

**Comment by bryanboza** [comment]
Fixe, after enable the following feature flag, now we are able to enable the new edit mode beta in the content type 

```
      "DOT_CONTENT_EDITOR2_ENABLED": 'true'

```



![Image](https://github.com/dotCMS/core/assets/2641437/220d9ca0-116f-491a-af0c-1e1bb0f35cb5)
