### ISSUE TITLE
Edit Page V2

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27546]
### Parent Issue

#26644

### Task

Last sprint we built a new edit mode for headless rendered pages, now we want to use the new cooler and sleeker version of the editor to edit VTL rendered pages.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Users should be able to edit VTL and headless pages with the new editor.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- [Miro](https://miro.com/welcomeonboard/ckZrYXRxY3NMTnQxR2IwSEE1NjJBYk1manp1Y0Z0Tk5wSkFtNHB5QlVSRkRESVNxQW9ORW9ZOUJwV3l3c3BOSXwzMDc0NDU3MzQ1OTIzMjMxMDI4fDI=?share_link_id=419656242768)

```[tasklist]
### Sub-Tasks & Estimates
- [ ] #27350
- [ ] https://github.com/dotCMS/core/issues/27518
- [ ] https://github.com/dotCMS/core/issues/27596
- [ ] https://github.com/dotCMS/core/issues/27547
- [ ] https://github.com/dotCMS/core/issues/27565
- [ ] https://github.com/dotCMS/core/issues/27592
- [ ] https://github.com/dotCMS/core/issues/27526
- [ ] #27295
- [ ] https://github.com/dotCMS/core/issues/27654
- [ ] https://github.com/dotCMS/core/issues/27564
- [ ] https://github.com/dotCMS/core/issues/27551
- [ ] https://github.com/dotCMS/core/issues/27658
- [ ] https://github.com/dotCMS/core/issues/27561
- [ ] https://github.com/dotCMS/core/issues/27699
- [ ] https://github.com/dotCMS/core/issues/27786
- [ ] https://github.com/dotCMS/core/issues/27598
- [ ] https://github.com/dotCMS/core/issues/27900
- [ ] https://github.com/dotCMS/core/issues/27887
- [ ] https://github.com/dotCMS/core/issues/27896
- [ ] https://github.com/dotCMS/core/issues/27753
- [ ] https://github.com/dotCMS/core/issues/27917
- [ ] https://github.com/dotCMS/core/issues/27977
- [ ] https://github.com/dotCMS/core/issues/27676
- [ ] https://github.com/dotCMS/core/issues/27790
- [ ] https://github.com/dotCMS/core/issues/27700
- [ ] https://github.com/dotCMS/core/issues/27899
- [ ] https://github.com/dotCMS/core/issues/28024
- [ ] https://github.com/dotCMS/core/issues/28076
- [ ] https://github.com/dotCMS/core/issues/27698
- [ ] https://github.com/dotCMS/core/issues/27674
- [ ] https://github.com/dotCMS/core/issues/27901
- [ ] https://github.com/dotCMS/core/issues/28096
- [ ] https://github.com/dotCMS/core/issues/27964
- [ ] https://github.com/dotCMS/core/issues/27931
- [ ] https://github.com/dotCMS/core/issues/27650
- [ ] https://github.com/dotCMS/core/issues/27549
- [ ] https://github.com/dotCMS/core/issues/28041
- [ ] https://github.com/dotCMS/core/issues/27911
- [ ] https://github.com/dotCMS/core/issues/28040
- [ ] https://github.com/dotCMS/core/issues/28155
- [ ] https://github.com/dotCMS/core/issues/28196
- [ ] https://github.com/dotCMS/core/issues/28281
- [ ] https://github.com/dotCMS/core/issues/28220
- [ ] https://github.com/dotCMS/core/issues/27919
- [ ] https://github.com/dotCMS/core/issues/28039
- [ ] https://github.com/dotCMS/core/issues/28372
- [ ] https://github.com/dotCMS/core/issues/28332
- [ ] https://github.com/dotCMS/core/issues/28331
- [ ] https://github.com/dotCMS/core/issues/28004
- [ ] https://github.com/dotCMS/core/issues/28033
- [ ] https://github.com/dotCMS/core/issues/28087
- [ ] https://github.com/dotCMS/core/issues/28259
- [ ] https://github.com/dotCMS/core/issues/28177
- [ ] https://github.com/dotCMS/core/issues/28614
- [ ] https://github.com/dotCMS/core/issues/28198
- [ ] https://github.com/dotCMS/core/issues/28269
- [ ] https://github.com/dotCMS/core/issues/28003
- [ ] https://github.com/dotCMS/core/issues/27880
- [ ] https://github.com/dotCMS/core/issues/28042
- [ ] https://github.com/dotCMS/core/issues/27916
- [ ] https://github.com/dotCMS/core/issues/28357
- [ ] https://github.com/dotCMS/core/issues/28038
- [ ] https://github.com/dotCMS/core/issues/28464
```
