### ISSUE TITLE
Edit Page V2: Research on bringing experiments into the new edit page

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27565]
### Parent
#27546

> [!NOTE]  
> TIMEBOXED to 2 hours, we need to call backups here like @oidacra or @hmoreras to help up setup this and running.

### Task description
As a dotCMS user, I want to be able to run experiments in dev mode and add the experiments tab to the main navigation in the new edit page. Additionally, I need to determine the necessary tasks or steps to bring this functionality back.

```[tasklist]
### Acceptance Criteria
- [ ] The research should provide clear instructions on how to run experiments in dev mode.
- [ ] The research should outline the steps required to add the experiments tab to the main navigation in the new edit page.
- [ ] The research should identify the tasks or steps needed to bring the functionality of running experiments back.
- [ ] The research findings should be documented and shared with the team.
```

### External Links
N/A

### Assumptions & Initiation Needs
- The team has access to the dotCMS platform.
- The team has a development environment set up for testing and experimentation.
- The team has knowledge of the new edit page and its navigation structure.

### Quality Assurance Notes & Workarounds
- This research task does not involve any code development or implementation, so no specific quality assurance notes or workarounds are required.

**Comment by fmontes** [comment]
### @oidacra instructions

Docker file `core/docker/docker-compose-examples/analytics/docker-compose.yml`

When run 

```
Running dotCMS from Docker
clientId: 	analytics-customer-customer1
Secret:	 testsecret
Analytics Config URL: 	http://host.docker.internal:8088/c/customer1/cluster1/keys
Analytics Write URL use: 	http://host.docker.internal:8081/api/v1/event
Analytics Read URL use:	http://host.docker.internal:4001/
```

App settings:

![Image](https://github.com/dotCMS/core/assets/751424/c6cb5114-4d2f-43da-bf58-c09cac209498)

If info above is good, it should auto populate this one in red

![Image](https://github.com/dotCMS/core/assets/751424/44c64fb3-3df0-4de2-b82f-6b86453454ef)

**Comment by KevinDavilaDotCMS** [comment]
``### Implement Experiments in Dev mode
First, reproduce this steps to load experiments in dev mode

1. You need to have dotcms running (docker-file with dotcms, elasticsearch and postgresql)
2. Go to `core/docker/docker-compose-examples/analytics/docker-compose.yml` and run that docker-compose.
3. After the docker-compose loads, In dotCMS, go to Settings => Apps => Analytics Integration
4. Fill the fields with this information
`clientId: 	analytics-customer-customer1
Secret:	 testsecret
Analytics Config URL: 	http://host.docker.internal:8088/c/customer1/cluster1/keys
Analytics Write URL use: 	http://host.docker.internal:8081/api/v1/event
Analytics Read URL use:	http://host.docker.internal:4001/`
ans save it
5. If all is ok, when you reopen Analytics Integration, you must to see a value like `js.cluster1.customer.1.j6...` in Analytics key field.

Then you can go to any page and can create a experiment of that page.

For the next integration with EditEMA, probably we only need to redirect to `experiments/$identifier}`, like the current EditPage

![Screenshot 2024-02-15 at 13 31 18](https://github.com/dotCMS/core/assets/144152756/1c07209e-1e90-4368-aa64-7d9b0c330131)
