### ISSUE TITLE
Edit Page V2: Add Preview of Social Media Cards for dotCMS Rendered Pages

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27562]
### Task Description
As a developer working on the dotCMS platform, I need to add the functionality to preview social media cards for dotCMS rendered pages in the new editor.

Currently, this feature is not available because we do not have access to the HTML code of the headless pages to parse and retrieve the necessary information. However, with the new editor using dotCMS rendered pages, we now have the opportunity to bring back this feature.

https://github.com/dotCMS/core/assets/751424/f7161e7a-ec6e-44bf-b155-21f3ba38a47f

```[tasklist]
### Acceptance Criteria
- [ ] The preview of social media cards should be available when editing pages rendered with the dotCMS engine.
- [ ] Should be remian hidden for headless pages.
- [ ] The preview should be responsive and display correctly on different devices and screen sizes.
```

### External Links
- None.

### Assumptions & Initiation Needs
- The new editor is already implemented and being used for dotCMS rendered pages.
- We retrieve social media card information by parsing the HTML string from the page API to extract the meta information.

**Comment by zJaaal** [comment]
Closed in favor of https://github.com/dotCMS/core/issues/27699
