### ISSUE TITLE
Edit Page V2: Moving Data from Client to Editor

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27592]
### Parent
#27546 

### Task Description
Now that we are merging the new edit mode with the old one, we need to transfer some data from the client to the editor. 

Currently, in the VTL version page, we are missing the following properties:

- `payload.container.contentletsId`
- `payload.pageContainers`
- `payload.pageId`
- `payload.personaTag`
- `payload.language_id`

However, all of these properties are available in the editor's store. Therefore, we need to retrieve them from the editor's store instead of waiting for the client to send them.

And this is because in the HTML of the page API we will not have any of these properties. Here is more info #27518

```[tasklist]
### Acceptance Criteria
- [x] Clean up the react component SDK to no longer send the data mentioned above.
- [x] Update the editor to retrieve the data from the store or the page API.
- [x] Thoroughly test the changes to ensure that nothing is broken.
```

### External Links
- #27518
- https://demo.dotcms.com/api/v1/page/render/index?language_id=1

### Assumptions & Initiation Needs
- The editor's store contains the necessary data properties.
- The react component SDK is responsible for sending the data to the editor.
- The page API can be used as an alternative source for retrieving the data.

### Quality Assurance Notes & Workarounds
None
