### ISSUE TITLE
Edit Page V2: Move Communication Events To Proper Library

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27598]
### Parent
#27546 

### Task description
As a developer, I need to reuse the communication code in the headless app (from the libraries) in the VTL rendered pages.

We need to move the communication code outside the React and Nextjs libraries.

Currently, the communication is tightly coupled with these libraries, which makes it impossible to integrate with the VTL rendered pages. 

By moving the communication to a separate JavaScript library, what we are looking to that we can easily call it from the VTL pages using `<script src="" />`

```[tasklist]
### Acceptance Criteria
- [ ] The existing communication code is refactored to be independent of the react and nextjs libraries.
- [ ] The new JavaScript library is created and implemented in the system.
- [ ] The new library allows us to seamlessly integrate the communication functionality with the VTL pages.
- [ ] All existing functionality related to communication remains intact after the update.
- [ ] The new library documentation needs to be on point
```

### External Links
We have an enum `CUSTOMER_ACTIONS` that has all the events that we send from the client to the editor

https://github.com/dotCMS/core/blob/a4e3a77083a57ce2289138dfaf427c585f9adbcc/core-web/libs/sdk/client/src/lib/postMessageToEditor.ts#L7-L33

We have to send a payload, which could be obtained from the client HTML, along with certain tasks. We have utilities available to fetch or find this payload, and we need to make these utilities accessible from the new libraries.

For example: 

https://github.com/dotCMS/core/blob/master/core-web/libs/sdk/react/src/lib/hooks/usePageEditor.tsx#L124-L133

Where we get all the positions for the rows, columns, containers and contentlets in the page. Likewise, this one, we might have some others, we need to move them as well.

And we have another one `NOTIFY_CUSTOMER` that is the one we use to do communication from the editor to the client:

https://github.com/dotCMS/core/blob/a4e3a77083a57ce2289138dfaf427c585f9adbcc/core-web/libs/portlets/edit-ema/portlet/src/lib/shared/enums.ts#L1-L6

### Assumptions & Initiation Needs
- The existing communication code is well-documented and can be easily understood for refactoring.
- The development team has the necessary knowledge and skills to create and implement the new JavaScript library.
- The VTL pages are already set up and can be accessed for integration.

**Comment by fmontes** [comment]
1. Update the HTML in the React components to match the HTML in the VTL pages
2. Move this SET_BOUNDS, SET_CONTENTLET, IFRAME_SCROLL, PING_EDITOR and CONTENT_CHANGE to a global event handler document or window level.
