### ISSUE TITLE
Implement the preview image generation in the Dialog

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#27632]
### Parent Issue
#27456

### User Story
Develop an updated AI with improved image generation logic. Centralize the logic within a dedicated popup interface for user interaction.

### Acceptance Criteria

- A new AI model with updated image generation logic is implemented.
- The logic is accessible through a dedicated popup window within the existing interface.
- Users can configure parameters and settings within the popup to influence image generation.
- The popup displays generated images based on user selections.
- Performance is optimized to ensure smooth image generation within the popup.

### dotCMS Version
master

### Proposed Objective
Enhance user experience with more advanced image generation capabilities and centralized control through a dedicated popup.

### Proposed Priority
Enhance user experience with more advanced image generation capabilities and centralized control through a dedicated popup.

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

**Figma**: https://www.figma.com/file/JF3P9JQVJHQOujhdpCRmJG/Block-Editor?mode=dev

### Assumptions & Initiation Needs

- Access to existing AI model and image generation codebase.
- Understanding of UI development principles and popup implementation for DotCMS.

### Quality Assurance Notes & Workarounds
_to_define_

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/27634
- [ ] https://github.com/dotCMS/core/issues/27635
- [ ] https://github.com/dotCMS/core/issues/27636
- [ ] https://github.com/dotCMS/core/issues/27955
- [ ] https://github.com/dotCMS/core/issues/27956
- [ ] https://github.com/dotCMS/core/issues/28062
- [ ] https://github.com/dotCMS/core/issues/28172
```

**Comment by hmoreras** [comment]
Comment to QA: 

This video show the scenarios we cover with the new updates of the AI image generation: 

https://github.com/dotCMS/core/assets/31667212/6e1cdb7e-2865-4365-92ed-3e91cb1c2895

Used plugin version: `com.dotcms.ai-24.2.9.jar`

fix of the error label: https://github.com/dotCMS/core/pull/28058

**Comment by oidacra** [comment]
When you try
- Generate using a prompt first
- Change of opinion and generate using the content instead, still using the prompt of the user.

![Image](https://github.com/dotCMS/core/assets/1909643/fc33804e-2541-4838-a027-4f0f3a35ab8b)

**Comment by hmoreras** [comment]
PR to Fix for Arcadio feedback: https://github.com/dotCMS/core/pull/28124

**Comment by oidacra** [comment]
IQA Passed.

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_5953f39**, Docker, macOS 13.0, FF v121.0.1

Add a ' copy to clipboard ' message when you click
<img width="620" alt="Screenshot 2024-04-08 at 3 01 50 PM" src="https://github.com/dotCMS/core/assets/129882031/168bb25f-903f-4ed6-9c4e-6dc55447f8f1">

Cutting words to a second line
<img width="620" alt="Screenshot 2024-04-08 at 3 04 21 PM" src="https://github.com/dotCMS/core/assets/129882031/a27eea74-46ac-4345-94e3-33ce1d904dbb">

**Comment by hmoreras** [comment]
> **Failed**: Tested on **master_5953f39**, Docker, macOS 13.0, FF v121.0.1
> 
> Cutting words to a second line <img alt="Screenshot 2024-04-08 at 3 04 21 PM" width="620" src="https://private-user-images.githubusercontent.com/129882031/320648063-a27eea74-46ac-4345-94e3-33ce1d904dbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3OTAwMDAsIm5iZiI6MTcxMjc4OTcwMCwicGF0aCI6Ii8xMjk4ODIwMzEvMzIwNjQ4MDYzLWEyN2VlYTc0LTQ2YWMtNDM0NS05NGUzLTMzY2UxZDkwNGRiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQyMjU1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDRlYWVkYzllM2NhMThlODg5N2ZjMGJkNDEzNjljNDBjYjY2YzFkOWI1MGIzMDdiMjdhZGRjMGZhODNlYTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VK7oZBTbhCaj-IgqO6R18-qY0EA0nMZtmdTsvIyPeR4">

this feedback will go under this PR: https://github.com/dotCMS/core/pull/28191

**Comment by hmoreras** [comment]
feedback provided merged on this PR: https://github.com/dotCMS/core/pull/28191

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_a5c816a**, Docker, macOS 13.0, FF v124.0.2
