### ISSUE TITLE
Content Type per Site: Upgrade Content Type Factory including Feature Flag

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27729]
### Parent
#27727

### Task Description
As a developer, I need to upgrade the content type factory to include a feature flag so that the new code will only be executed if the feature flag is set to true. This allows us to control the behavior of the factory based on the feature flag settings.

```[tasklist]
### Acceptance Criteria
- [ ] The content type factory must be upgraded to include a feature flag check before executing the new code.
- [ ] The new code in the factory should only be executed if the feature flag is set to true.
- [ ] The upgrade should not affect the existing functionality of the content type factory.
```

### External Links
N/A

### Assumptions & Initiation Needs
- The feature flag will be set up and managed per dotCMS instance.

### Quality Assurance Notes & Workarounds
- QA team should test the functionality of the feature flag and ensure that the new code is only executed when the flag is set to true.
