### ISSUE TITLE
Content Type per Site: Upgrade Content Types REST Endpoints

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27731]
### Parent
#27727

### Task Description
As a dotCMS developer, I need to be able to get the content types per site from the rest endpoints.

```[tasklist]
### Acceptance Criteria
- [x] `/api/v1/contenttype?sites={siteKey1|siteId1, siteKe2|siteId2}` should only return content types for the specified sites. Such a list of site IDs can include both the current site, and SYSTEM_HOST
- [x] The endpoints should be tested for correct data retrieval and response format.
- [x] The upgrade should not affect existing functionality and should be backward compatible.
- [x] Requesting data from a non-existing site must return zero results
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Acceptance Criteria
Please refer to the [core/dotCMS/src/curl-test/ContentTypeResourceTests.json](https://github.com/dotCMS/core/pull/27818/files#diff-5d9c8eafd1895f4bf02ac4cbaa61ebea35741e73c27297ce22c564cda0f26eb0) Postman test, specifically under the `Get Types from one or more Sites` folder. You'll see several **GET** requests that'll show you how this new filtering parameter works.

Beyond that, we need to make sure that all parts of dotCMS that allow users to list Content Types, paginate them and filter them are working as expected, as this change must be backwards-compatible.

**Comment by wezell** [comment]
Adding a new param to an api does not require a feature flag, as long as the old behavior still works.

**Comment by josemejias11** [comment]
**Failed**: Tested on **master_439c2a4**, Docker, macOS 13.0, FF v121.0.1

Query should pull results from any ohter site added to the request.
<img width="1621" alt="Screenshot 2024-03-08 at 5 04 54 PM" src="https://github.com/dotCMS/core/assets/129882031/44915097-a765-4e28-b589-fe689149cdde">

**Comment by jcastro-dotcms** [comment]
@josemejias11 you need to run the whole test suite before running the specific Postman test you highlighted. Such a test is meant for you to know how to use it and create your own custom test.

**Comment by bryanboza** [comment]
We need some work here: 

We always are returning the content from the default sire, even if this is not in the list of the desired sites in the parameters. 

- In case you send an invalid siteId, we need to return an empty array
- In case you send multiple parameters we need to return the site from all the sites 
- We need to respect the "per_page=" parameter 
- We should support to send siteId && site name too

**Comment by bryanboza** [comment]
Ok after a discussion about wildcards using on this API, we are ok with this, then we can pass it. 

Tested on master // Docker // FF
