### ISSUE TITLE
Edit Page V2: API Design for Editor JavaScript Library

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27786]
### Parent
#27546 

### Task description
As a dotCMS developer, I need to research and design the API for the editor JavaScript library to ensure it is intuitive and easy to use for content editors and developers.

> [!WARNING]  
> Timeboxed to 2h

```[tasklist]
### Acceptance Criteria
- [x] Provide code examples demonstrating how the editor JavaScript library API should work in different frameworks (e.g., Angular, React, Vue) or vanilla JavaScript.
- [x] Ensure the API design allows for easy integration with dotCMS content management system.
- [x] Document the API endpoints, methods, and parameters clearly for future reference.
```

### External Links
N/A

### Assumptions & Initiation Needs
- Assume basic knowledge of JavaScript and front-end development.
- Collaborate with other developers to gather feedback and refine the API design.

**Comment by fmontes** [comment]
[dotcms-sdk-2024.zip](https://github.com/dotCMS/core/files/14484719/dotcms-sdk-2024.zip)

![image](https://github.com/dotCMS/core/assets/751424/4163cf9d-7002-4cf9-893e-58610d3cb085)
