### ISSUE TITLE
dotCLI: Content Type Push Improvements

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#27829]
### Task

There are a few improvements we should take care of when pushing content types:

- [ ] when specifying a detail page for a url mapped page, a user should be able to specify a path and not rely on an id, e.g. `//demo.dotcms.com/blogs/detail-page`
- [ ]  `Updating` a type should not require the contentType.id.  It should be able to use the varName
- [ ] `Updating` fields, we should not require the contentType.id in the fields properties - it is known because the fields are a property of the content type
- [ ] `Updating` a field should not require the field.id - it should be enough to use the varName.
- [ ] when specifying workflows, the user should be able to pass just an array of workflow names OR ids e.g.
- [ ] Also I am wondering if the `-dau` switch should be our default.  This is the `dotcli push --disable-auto-update` We can talk about it. 
```
  "workflows" : [ 
     "System Workflow", 
     "d61a59e1-a49c-46f2-a929-db2b4bfa88b2"
  ]
```
See the content Type Def below that I used to test:
```
{
  "clazz" : "SimpleContentType",
  "name" : "Testing CLI Type",
  "variable" : "testingCLIType",
  "folder" : "SYSTEM_FOLDER",
  "siteName" : "demo.dotcms.com",
  "folderPath" : "/",
  "icon" : "blender",
  "baseType" : "CONTENT",
  "fields" : [ {
    "clazz" : "TextField",
    "indexed" : true,
    "listed" : true,
    "name" : "Title",
    "variable" : "title",
    "fieldType" : "Text",
    "contentTypeId" : "c676e84ad83b82c12e3d264a2200408d",
    "dataType" : "TEXT"
  }, {
    "clazz" : "TagField",
    "indexed" : true,
    "name" : "Keywords",
    "variable" : "keywords",
    "fieldType" : "Tag",
    "contentTypeId" : "c676e84ad83b82c12e3d264a2200408d",
    "dataType" : "SYSTEM"
  }, {
    "clazz" : "TextField",
    "searchable" : true,
    "indexed" : true,
    "listed" : true,
    "name" : "Url Slug",
    "variable" : "urlSlug",
    "fieldType" : "Text",
    "contentTypeId" : "c676e84ad83b82c12e3d264a2200408d",
    "dataType" : "TEXT"
  }, {
    "clazz" : "BinaryField",
    "name" : "Image",
    "variable" : "image",
    "fieldType" : "Binary",
    "contentTypeId" : "c676e84ad83b82c12e3d264a2200408d",
    "dataType" : "SYSTEM"
  }, {
    "clazz" : "StoryBlockField",
    "name" : "Blog",
    "variable" : "blog",
    "fieldType" : "Story-Block",
    "contentTypeId" : "c676e84ad83b82c12e3d264a2200408d",
    "dataType" : "LONG_TEXT"
  } ],
  "detailPage" : "f0ffaa29bf4a5ae46f127fd4d6acb55f",
  "urlMapPattern" : "/ai-blog/{urlSlug}/",
  "workflows" : [ {
    "archived" : false,
    "creationDate" : "2024-03-05T16:18:34.738+00:00",
    "defaultScheme" : false,
    "description" : "",
    "entryActionId" : null,
    "id" : "d61a59e1-a49c-46f2-a929-db2b4bfa88b2",
    "mandatory" : false,
    "modDate" : "2024-03-05T12:02:58.553+00:00",
    "name" : "System Workflow",
    "system" : true
  } ]
}
```

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 2 - Important

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/28262
- [ ] https://github.com/dotCMS/core/issues/28263
- [ ] https://github.com/dotCMS/core/issues/28264
- [ ] https://github.com/dotCMS/core/issues/28265
```
