### ISSUE TITLE
Migrate AI plugin into core 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27835]
### Task

Move the AI features implemented as part of https://github.com/dotCMS/com.dotcms.ai to core. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

* Test coverage 
* All the functionality properly migrated and working as expected/documented. 

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/27972
- [ ] https://github.com/dotCMS/core/issues/27959
- [ ] https://github.com/dotCMS/core/issues/27960
- [ ] https://github.com/dotCMS/core/issues/27973
- [ ] https://github.com/dotCMS/core/issues/28121
- [x] https://github.com/dotCMS/core/issues/28209
```

**Comment by john-thomas-dotcms** [comment]
Can we break this one up into a few smaller issues?

We'd like to bring some portion of this into this sprint, but we should break it up to do it.

**Comment by john-thomas-dotcms** [comment]
We're going to hold off on the ITs until after a refactor of the workflow subactions.  So, this card is now done.
