### ISSUE TITLE
Edit Page V2: Improve SDK client-editor

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#27887]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### Task description
Some issues raised after these [pull requests](https://github.com/dotCMS/core/pull/27866) for timing purposes, we decided to move those issues to a new task.

```[tasklist]
### Acceptance Criteria
- [ ] Change the exports in index. Probably not everything should be exported [context here](https://github.com/dotCMS/core/pull/27866#discussion_r1516131311)
- [ ] Call only the listeners necessary for VTLs [context here](https://github.com/dotCMS/core/pull/27866#discussion_r1516139187)
- [ ] Double check on updateNavigation behavior on Headless/VTL [Context here](https://github.com/dotCMS/core/pull/27866#discussion_r1516181502)
- [ ] Delete .d files on VTL javascript file [https://github.com/dotCMS/core/pull/27866#discussion_r1516185630](Context here)
- [ ] Maybe move some interfaces to Angular side [Context here](https://github.com/dotCMS/core/pull/27866#discussion_r1516168747)
- [ ] Doc index.ts config and relevant functions
- [ ] Rename options to configutarion (or other appropiate name) on DotcmsLayout props
- [ ] Type functions on  [/src/lib/editor/utils/editor.utils.ts](https://github.com/dotCMS/core/pull/27866/files#diff-da04cd87e74588e77b6e00569a6866250a4a3be3076ac9cc2b62851ab19cb00a)
- [ ] Next.js server is showing an error for the client library, [see error](https://github.com/dotCMS/core/assets/751424/b14836c5-f80c-4335-b82a-6bb2c14fd80c)
```

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average
