### ISSUE TITLE
Experiments Improvements and Cleanup

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#27892]
Epic to capture a number of small improvements and fixes which aren't currently a priority, but which we'll want to tackle as a whole after Experiments is in wider use, and we have additional feedback from customers actually using it.

## Bugs
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/27450
- [ ] https://github.com/dotCMS/core/issues/25353
- [ ] https://github.com/dotCMS/core/issues/25329
- [ ] https://github.com/dotCMS/core/issues/25594
- [ ] https://github.com/dotCMS/core/issues/26090
- [ ] https://github.com/dotCMS/core/issues/25337
- [ ] https://github.com/dotCMS/core/issues/24633
- [ ] https://github.com/dotCMS/core/issues/26859
- [ ] https://github.com/dotCMS/core/issues/24656
- [ ] https://github.com/dotCMS/core/issues/25340
- [ ] https://github.com/dotCMS/core/issues/28092
- [ ] https://github.com/dotCMS/core/issues/24920
```

## Front-End Enhancements
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/23323
- [ ] https://github.com/dotCMS/core/issues/25460
- [ ] https://github.com/dotCMS/core/issues/27121
- [ ] https://github.com/dotCMS/core/issues/27122
- [ ] https://github.com/dotCMS/core/issues/27123
- [ ] https://github.com/dotCMS/core/issues/24328
- [ ] https://github.com/dotCMS/core/issues/28153
- [ ] https://github.com/dotCMS/core/issues/23824
- [ ] https://github.com/dotCMS/core/issues/25324
```

## Back-End Enhancements/Refactoring
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/26571
- [ ] https://github.com/dotCMS/core/issues/23542
- [ ] https://github.com/dotCMS/core/issues/26589
- [ ] https://github.com/dotCMS/core/issues/27631
```
