### ISSUE TITLE
Investigate @ngrx/component-store usage in dotCMS

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#27937]
### Task description
As a developer working on dotCMS projects, I need to investigate the usage of @ngrx/component-store to manage the state of Angular components to understand if there are any issues affecting our application.

```[tasklist]
### Acceptance Criteria
- [x] Research and document the current implementation of @ngrx/component-store in dotCMS projects.
- [x] Identify any potential issues or limitations with the current usage of @ngrx/component-store.
- [x] Provide recommendations on how to improve the implementation of @ngrx/component-store if necessary.
- [x] Create a proof of concept (POC) to demonstrate any identified issues and proposed solutions.
- [x] Meet with the @dotCMS/frontend  team to explain the results
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A
