### ISSUE TITLE
Integration tests for AI Viewtools

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27959]
### Parent Issue

https://github.com/dotCMS/core/issues/27835

### Task

- Write automated tests for all viewtools
    - $ai 
        - [x] $ai.generateText
        - [x] $ai.generateImage
    - $ai.search
        - [x] $ai.search.query
        - [x] $ai.search.related
    - $ai.embeddings
        - [x] $ai.embeddings.countTokens
        - [x] $ai.embeddings.generateEmbeddings
        - [x] $ai.embeddings.getIndexCount
        - [x] $ai.embeddings.indexCount
    - $ai.completions
        - [x] $ai.completions.getConfig
        - [x] $ai.completions.config
        - [x] $ai.completions.summarize
        - [x] $ai.completions.raw

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- [ ] All the viewtools working according to the documentation https://www.dotcms.com/docs/latest/dotai-plugin#Viewtool
- [ ] Test coverage for all viewtools
