### ISSUE TITLE
Write design documentation for Experiments 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#27983]
### Task

We need an internal doc that includes the following: 

- [x] Diagram of the flow when a user requests a page with a running experiment. What actions take place both in the browser and in the server. [Diagram](https://docs.google.com/drawings/d/1FEikYl8MxLIQ1AsQfgUVBdZYDkJ8eHPLQ2dr7K-sgoE/edit?usp=sharing) [Explanation](https://docs.google.com/document/d/1U14NouQQy90h8P50UeZZLYGGDddVe1wCSnOGTesbtcA/edit?usp=sharing)
- [x] Diagram of the architecture, including the different layers and components (endpoints, services) that participate in capturing and persisting an event and getting results. [Diagram](https://docs.google.com/drawings/d/1EPhtGemkOm5ggkKdu1XMgiIECih4x1vuF2MdMmOT7N8/edit?usp=sharing) [Explanation](https://docs.google.com/document/d/1gjGj9uQ6nf8qOjH8dtt7D3v5koPYz8D40OjsDjXvP-k/edit?usp=sharing)
- [x] Document to detail the main java classes handling the configuration, execution, calculations and results and of an Experiment [Document](https://docs.google.com/document/d/1-dxLs5FSTKmK-dy1HfIZhv_dp2miksbVRFEZePuibbM/edit?usp=sharing)

### Proposed Objective

Documentation

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Having a document available that can help devs, POs, Support to see the general flow and components of Experiments and understand the justification of the approaches that were followed.
