### ISSUE TITLE
Java 21 Switchover Epic

### ISSUE THREAD

**Issue by spbolton** [dotCMS/core#27993]
This epic outlines the list of identified major tasks and epics required to migrate to the use of Java 21

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/27995
- [ ] https://github.com/dotCMS/core/issues/28596
- [ ] https://github.com/dotCMS/core/issues/28622
- [ ] https://github.com/dotCMS/core/issues/28744
- [ ] https://github.com/dotCMS/core/issues/27998
- [ ] https://github.com/dotCMS/core/issues/27997
- [ ] https://github.com/dotCMS/core/issues/29685
- [ ] https://github.com/dotCMS/core/issues/29756
- [ ] https://github.com/dotCMS/core/issues/29759
```

**Comment by spbolton** [comment]
Reopened to include switchover and post switchover tasks
