### ISSUE TITLE
Include AI portlet by default

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28121]
### Parent Issue

https://github.com/dotCMS/core/issues/27835

### Task

After the migration of the AI plugin into core now the AI portlet needs to be added manually. This task is for including it by default. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

No need to manually add the AI portlet. It comes by default regardless of the starter used or if upgrading. 

- [x] Full starter
- [x] Empty starter 
- [x] Upgrading

**Comment by dsilvam** [comment]
Full starter: https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240531/starter-20240531.zip

**Comment by dsilvam** [comment]
Note to QA. 

To test make sure that the following is happening: 

- [ ] 1. Start with empty db + empty starter -> The dotAI portlet is under the Developers menu
- [ ] 2. Start with empty db + full [starter](https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240531/starter-20240531.zip)  -> The dotAI portlet is under the Developers menu
- [ ] 3. Upgrade from an old version of dotCMS ->  The dotAI portlet is under the Developers menu

**Comment by oidacra** [comment]
- [x] 1. Start with empty db + empty starter -> The dotAI portlet is under the Developers menu
<img width="2201" alt="Screenshot 2024-06-03 at 6 30 03 PM" src="https://github.com/dotCMS/core/assets/1909643/508435d1-bf95-4cb9-9778-9e17df24dd1a">

- [x] 2. Start with empty db + full [starter](https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20240531/starter-20240531.zip)  -> The dotAI portlet is under the Developers menu
<img width="1933" alt="Screenshot 2024-06-03 at 6 33 21 PM" src="https://github.com/dotCMS/core/assets/1909643/599aa166-25c6-4085-9f93-99581f17a92b">

- [ ] 3. Upgrade from an old version of dotCMS ->  The dotAI portlet is under the Developers menu

Test with `trunk_f70bf4a` or newer.

**Comment by erickgonzalez** [comment]
Only for 24.04 LTS

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_7bc05d3**, Docker, macOS 13.0, FF v124.0.2
