### ISSUE TITLE
Edit Page V2: Fix Live Page Link

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28220]
### Parent
#27546 

### Task description
As a page editor, I want a link to preview the page in live mode.

<img width="1136" alt="image" src="https://github.com/dotCMS/core/assets/751424/86f28310-4954-4e3a-b564-22dee1176d8d">

```[tasklist]
### Acceptance Criteria
- [x] The preview link should open a new tab with the current page in live mode when clicked.
- [x] The preview link should accurately reflect the changes made in the editor.
- [x] Change the link text to "Live Preview"
- [ ] ~The page needs to append `?mode=EDIT_MODE` (I think, double check)~
- [x] The page needs to append `mode=LIVE`
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_c1fbb01**, Docker, macOS 13.0, FF v124.0.2
