### ISSUE TITLE
Write design documentation for the Telemetry plugin

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28335]
### Task

We need an internal doc that includes the following: 

- [ ] Actions executed on plugin startup/shutdown. 
- [ ] Telemetry data extraction/capturing: Main java interfaces and classes that capture the different metrics 
- [ ] Telemetry data persistence: Main java interfaces and classes that handle the persistence of the telemetry to the database service. 
- [ ] DB endpoint. Where's the code and what does it do. What are the different URLs available for the different environments (i.e., dev, test, prod) 
- [ ] DB. How to connect to the db, datasource info, etc, for the different environments (i.e., dev, test, prod) 

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

Having a document available that can help devs, POs, Support to understand the general flow and main components of the Telemetry plugin and also understand the justification of the approaches that were followed.

**Comment by john-thomas-dotcms** [comment]
We need to add another item to this doc:
* High-level description of how different metrics are retrieved

For example, we need to describe the difference between live and working metrics, we need to be clear about what time frame "recently edited" covers, etc.

We'll ultimately need a separate doc which describes what each metric means.  But that's a separate thing, and it may end up being done in a BI tool; so, we don't need to describe each metric in the design doc.

**Comment by dsilvam** [comment]
Sequesncial diagram explain how the Metric are collected
- https://docs.google.com/drawings/d/1H2rJBcoKO8VDYhEG5ieQ5Yldt8J16-O1bo47XG2ER_M/view
- https://docs.google.com/document/d/1mAaQA2tawHtTl-wdpkJ78mqaVCHSO1OdZ2uDezyKuds/view

Class Diagram explains what is need to do to create a new Metric
- https://docs.google.com/drawings/d/1xOmgJ8xsNsexB8wRMebUoX0TyNeVMbZd5LIax7tA2E8/view
- https://docs.google.com/document/d/1dvaXfX67MXXu2z7KBwKMrKrqD1dzR2XnoHMrBKQmL-0/view

Diagram of the architecture
- https://docs.google.com/drawings/d/1sryhac7VgsZts7j-BUCTdjyJ0U78n4tRmTWysUlavqk/view
- https://docs.google.com/document/d/1vufYSGT8Phwq1DOhIlfC3V2gcSa4-wXjk04Ddpend4g/view
