### ISSUE TITLE
Edit Page V2: Page properties doesnt refresh before changes

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#28398]
### Parent Issue

https://github.com/dotCMS/core/issues/27546

### Task

When changing properties or bringing back to a previous version on a page (Headless or VTL), the information displayed in the dialog is not updated.

The toolbar header and the dialog header are not updated either.

https://github.com/dotCMS/core/assets/63567962/475fa578-50bb-4a6c-b68d-2fa1a0c3174e

### Proposed Objective

Please Select

### Proposed Priority

Please Select

### Acceptance Criteria

- [ ] Update toolbar name
- [ ] Update dialog name
- [ ] Update info when re-open the dialog

**Comment by rjvelazco** [comment]
@KevinDavilaDotCMS The properties are getting updated on `master`. Should we open a separate issue from the `breadcrumbs`?  That's not `Edit Page` specify


https://github.com/dotCMS/core/assets/72418962/16f79817-b74f-417a-a3d3-841bcadc380e

**Comment by rjvelazco** [comment]
The properties are getting updated. We need to open a new ticket for the `Breadcrumbs` since it is a bigger refactor.

**Comment by bryanboza** [comment]
Fxied, tested on the latest trunk and now we are refreshing the properties.

**Comment by melissarojas-dotcms** [comment]
[Link to the GitHub issue for breadcrumbs implementation](https://github.com/dotCMS/core/issues/29125)
