### ISSUE TITLE
[EPIC] Angular SDK and Examples

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28404]
### Task description

As a developer, I want to create a library and example to render dotCMS pages using the Angular framework. This allows us to seamlessly integrate dotCMS content into Angular applications and provide a better user experience.

\`\``[tasklist]
### Acceptance Criteria
- [ ] #28405
- [ ] https://github.com/dotCMS/core/issues/28407
- [ ] https://github.com/dotCMS/core/issues/28497
- [ ] https://github.com/dotCMS/core/issues/28498
- [ ] https://github.com/dotCMS/core/issues/28729
- [ ] https://github.com/dotCMS/core/issues/28087
- [ ] https://github.com/dotCMS/core/issues/28728
- [ ] https://github.com/dotCMS/core/issues/28788
- [ ] https://github.com/dotCMS/core/issues/28737
- [ ] https://github.com/dotCMS/core/issues/28816
- [ ] https://github.com/dotCMS/core/issues/28817
- [ ] https://github.com/dotCMS/core/issues/28858
- [ ] https://github.com/dotCMS/core/issues/28887
- [ ] https://github.com/dotCMS/core/issues/28888
- [ ] https://github.com/dotCMS/core/issues/28928
- [ ] https://github.com/dotCMS/core/issues/28818
- [ ] https://github.com/dotCMS/core/issues/28949
- [ ] https://github.com/dotCMS/core/issues/28860
`\`\`
