### ISSUE TITLE
[EPIC]: Implement Content API in `@dotcms/client`

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28415]
### Task description

This task will involve identifying and documenting all the necessary changes and enhancements required to integrate the content API into the `@dotcms/client` library.

### Endpoint

**We are going to use `api/content/_search`**

```javascript
fetch('http://localhost:8080/api/content/_search', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    query:
      '+contentType:Blog +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST) +languageId:1 +deleted:false +working:true +variant:default',
    sort: 'modDate desc',
    limit: 20,
    offset: 0,
  }),
})
  .then((response) => response.json())
  .then((data) => console.log(data))
  .catch((error) => console.error('Error:', error));
```

The response looks like this:

```json
{
  "entity": {
    "contentTook": 24,
    "jsonObjectView": {
      "contentlets": []
    },
    "queryTook": 31,
    "resultsSize": 6
  },
  "errors": [],
  "i18nMessagesMap": {},
  "messages": [],
  "pagination": null,
  "permissions": []
}
```

The `resultSize` is the total number of records for this query.

### The library response

We want to simplify the REST endpoint response to a more friendly object.

```json
{
  "contentlets": [],
  "page": 1,
  "size": 10,
  "total": 100,
  "sortedBy": [
    {
      "field": "title",
      "order": "asc"
    }
  ]
}
```

This is a proposal that should not be considered final.

### Library API

For easy use, let's go with the approach of functional programming for query and pass params, for example:

```javascript
// title:((hello OR hi) AND (world OR universe))
queryBuilder()
    .field('title')
    .group(queryBuilder().eq('hello').or().eq('hi'))
    .and()
    .group(queryBuilder().eq('world').or().eq('universe'));

// publish_date:[20220101 TO 20221231]
queryBuilder().field('publish_date').dateRange('20220101', '20221231').build()
```

And to pass parameters:

```javascript
.sortBy('xxx').page(1).limit(10)
```

> \[!WARNING\]
This is not the final design, we can do the necessary adjustments.
>

### Error Managements

TBD

### Acceptance Criteria

This user story does not have specific acceptance criteria, as it is an epic to track all the issues related to implementing the content API in the dotCMS client library.

\`\``[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/28416
- [ ] https://github.com/dotCMS/core/issues/28537
- [ ] https://github.com/dotCMS/core/issues/28634
- [ ] https://github.com/dotCMS/core/issues/28711
- [ ] https://github.com/dotCMS/core/issues/28733
- [ ] https://github.com/dotCMS/core/issues/28807
- [ ] https://github.com/dotCMS/core/issues/28830
- [ ] https://github.com/dotCMS/core/issues/28854
- [ ] https://github.com/dotCMS/core/issues/28737
`\`\`
