### ISSUE TITLE
SDK: Spec Sheet for Content API Support in @dotcms/client Library

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28416]
### Parent
#28415

### Task description
As a developer, I need to create a spec sheet document outlining the API methods for adding support to the Content API in the `@dotcms/client` library. 

This document will serve as a reference for implementing the necessary methods and parameters for interacting with the Content API.

> [!WARNING]  
> There is an existing document you just need to fill it, check the external links section.

### The spec sheet document should include

```[tasklist]
- [x] List of all API methods for interacting with the Content API
- [x] Detailed description of each method including purpose, arguments, parameters, and return values
- [x] Any additional notes or considerations for implementing the methods
```

### External Links
1. [Content API Documentation](https://www.dotcms.com/docs/latest/content-api-retrieval-and-querying)
2. [Starter document](https://docs.google.com/spreadsheets/d/1o1gDEOgtyS-4JqXw2Wv_IgfZUMoms8PiYoIFCvybi74/edit#gid=0)

### Assumptions & Initiation Needs
- Assumes familiarity with the `@dotcms/client` library and Content API
- Initiation requires access to the current implementation of the library and Content API documentation
