### ISSUE TITLE
Resolve JS dependancy vulnerabilities

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28435]
### Task

This task covers solving the following 14 JS vulnerabilities: 

### Proposed Objective

Security & Privacy

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The 14 JS vulnerabilities solved. 

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/28436
- [ ] https://github.com/dotCMS/core/issues/28437
- [ ] https://github.com/dotCMS/core/issues/28438
- [ ] https://github.com/dotCMS/core/issues/28439
- [ ] https://github.com/dotCMS/core/issues/28440
- [ ] https://github.com/dotCMS/core/issues/28441
- [ ] https://github.com/dotCMS/core/issues/28442
- [ ] https://github.com/dotCMS/core/issues/28605
- [ ] https://github.com/dotCMS/core/issues/28621
```
