### ISSUE TITLE
Create doc "How we do Engineering at dotCMS"

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#28479]
### Task

Create a document called "How we do Engineering at dotCMS" that summarizes how we code, test, release and deploy our solution at dotCMS.

The document must contain the most relevant information taken from our onboarding document. Besides, using data gathered from surveys and interviews, it should provide details about the best practices we use to code and test, describing how we release and deploy a version.

This document will lay the foundations for a standardized onboarding process and an improved developer experience.

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [ ] A google doc named "How we do Engineering at dotCMS" should be delivered 
- [ ] The document should contain a Happy Path for development at dotCMS
- [ ] Deadline: July 1st, 2024

### Sub-Tasks & Estimates

- [x] #28480
- [x] #28481
- [x] #28482
- [x] #28483
- [x] #28484
