### ISSUE TITLE
List Languages in the new design of the table.

### ISSUE THREAD

**Issue by hmoreras** [dotCMS/core#28475]
### Parent Issue

#28474

### User Story

As a developer, I need to implement the list view of p-table from PrimeNG, adhering to the new design system, and apply a class differentiator so that styles only apply to migrated tables.

### Acceptance Criteria

- [ ] The list view of p-table must be implemented according to the specifications provided by PrimeNG.
- [ ] The new design system guidelines must be followed for styling and layout.
- [ ] A class differentiator must be applied to ensure that styles only affect migrated tables.
- [ ] The user will be able to filter and sort by column

### Proposed Objective

User Experience

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://www.figma.com/file/tTWRVYunjnzTAWaj8Ctvra/Locales-%2F-Languages?node-id=472-21986&mode=dev

### Sub-Tasks & Estimates
