### ISSUE TITLE
Edit Content: Add Site/Folder Field

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28494]
### Parent Issue

https://github.com/dotCMS/core/issues/25445

### User Story

As a Content Architect in dotCMS, I want to add a Site/Folder field to the Edit Content Form so I can easily create and edit content.

### Acceptance Criteria

TBD

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

PrimeNG: [TreeSelect](https://www.primefaces.org/primeng-v15-lts/treeselect) 

Figma: [LINK](https://www.figma.com/design/7CzbMcGSbTIJjerWtcapAm/Design-System-2023?node-id=896-21686&t=Tz8ZmnjBFv7ud8f4-4)

### Quality Assurance Notes & Workarounds

The tag field should be tested to ensure that it is working as expected.

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/28638
- [ ] https://github.com/dotCMS/core/issues/28645
- [ ] https://github.com/dotCMS/core/issues/28843
- [ ] https://github.com/dotCMS/core/issues/28924
- [ ] https://github.com/dotCMS/core/issues/28925
```

**Comment by wezell** [comment]
- [ ] Need a attribute to show or hide System Host
- [ ] Need to be able to select host OR folder
- [ ] If no value, we should default to current selected host
- [ ] Need to show the full path of the field value (even though we only store the id of the parent)
- [ ] filterable needs to wildcard on both sides using the logic we use on the host selector, e.g. just like #27447

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_2181d4a**, Docker, macOS 14.5, FF v126.0.1
