### ISSUE TITLE
Angular SDK: 👷🏽‍♂️ Create `@dotcms/angular` library

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28498]
### Parent
#28404

### Task description
As a developer, I need to create a new Angular library that will assist in rendering dotCMS pages that can be edited in the UVE (Universal Velocity Editor).

> [!WARNING]  
> This issue depends heavily of the code written in #28497

```[tasklist]
### Acceptance Criteria
- [ ] Use `Nx` Angular generator to generate the library
- [ ] A new Angular library is created and located in the `/libs/sdk/angular` folder.
- [ ] The library exposes a `DotcmsLayout` component for rendering dotCMS pages.
- [ ] The library also exposes a `PageResponse` service to access the "current" page content
- [ ] [Document the steps by step process of creating this library](https://docs.google.com/document/d/1efVdE07g7Fou7PpPY6rT2CHGF6V21E2ypd6g18wRkTE/edit)
```

### External Links
- N/A

### Assumptions & Initiation Needs
- The developer has access to the dotCMS instance to test the rendering of pages.
- Angular CLI is installed on the developer's machine to create the new library.
- Knowledge of Angular and dotCMS APIs is required to implement the library successfully.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A
