### ISSUE TITLE
Angular SDK: 👷🏽‍♂️ Render dotCMS pages using `@dotcms/client`

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28497]
### Parent
#28404 

### Task description
As a developer, I need to create an Angular example project that demonstrates how to render dotCMS pages using the page API. This example should showcase how to fetch content from dotCMS and display it on a web page using Angular components.

### Acceptance Criteria

- [x] Use `@angular/cli` and the latest stable Angular version
- [x] The example should be located in `core/examples/angular`
- [x] Use a catch-all strategy for the routes
- [x] Render a dotCMS page using the `@angular/client`
- [x] Use Tailwind for the styles (don’t use the same colors as Next.js example)
- [x] Use raw css for the layout
- [x] Use `ngComponentOutlet` to render the components for each content type
- [x] Use `InjectionTokens` to pass the `@dotcms/client` to the "content types" components
- [ ] [Document the steps by step process of creating this example](https://docs.google.com/document/d/1efVdE07g7Fou7PpPY6rT2CHGF6V21E2ypd6g18wRkTE/edit)

### Assumptions & Initiation Needs
- This example is to be consumed by our customers' developers, keep it as clear and simple as possible
- Future forward a lot of this code will end up in the `@dotcms/angular` library we have to create, for example:
   - The `DotcmsLayout` component
   - All the layout related components like `Row`, `Columns` etc.
- The `@dotcms/angular` library will have a service that acts as a `React.Context` to allow a nested component to access the current page response
- We might want to create another example for Angular SSR

### Quality Assurance Notes & Workarounds
N/A

**Comment by zJaaal** [comment]
# IQA Passed

We can run the angular project in the browser and in the Visual Editor

## Screenshot

https://github.com/dotCMS/core/assets/63567962/ee8fab7c-3b56-47ef-bf0e-da13dcb0f3bc

**Comment by bryanboza** [comment]
Fixed, now it is working as expected... 

![Image](https://github.com/dotCMS/core/assets/2641437/f15563a5-8a98-4701-8f2e-8d21031f8241)
Tested in the last trunk version // Docker // FF
