### ISSUE TITLE
Deploy redis infrastructure per AWS region

### ISSUE THREAD

**Issue by sfreudenthaler** [dotCMS/core#28534]
### Parent Issue

Relates to #28532 because completion of this helps unblock the ability to move session state storage into redis and off of the dotcms-core pods.

### Task

```[tasklist]
### Tasks
- [ ] Pick the right redis cloud tier: [pricing link](https://redis.io/pricing/#pro) 
- [ ] Deploy redis cluster in each AWS region we operate 
- [ ] Update and deploy customer configurations
``` 

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

1. any new infrastructure should be codified, deployed, and managed by terraform
2. we should have one redis cluster per AWS region we operate
3. redis connections should be authenticated
4. redis traffic should be encrypted in transit 
5. data in redis should be encrypted at rest
6. there should be data segmentation between customers... Customer A should not be able to access Customer B keys (aka data)  

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- redislabs [cloud pricing ](https://redis.io/pricing/#pro)link
- redis cloud [terraform provider & documentation](https://registry.terraform.io/providers/RedisLabs/rediscloud/latest/docs)
