### ISSUE TITLE
CICD: Develop GitHub Action to Deploy dotCLI Artifacts Using Artifactory CLI

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#28598]
### User Story
As a developer, I need to create a task to develop a GitHub Action that exclusively deploys dotCLI artifacts using the Artifactory CLI to streamline and automate our deployment process.

### Acceptance Criteria
- A GitHub Action is developed to deploy dotCLI artifacts using the Artifactory CLI.
- The Action should be able to authenticate with Artifactory and handle the deployment of artifacts.
- Documentation is provided for setting up and using the Action.

### Proposed Objective
Integrations

### Proposed Priority
Priority 2 - Important

### dotCMS Version
N/A

### External Links
N/A

### Assumptions & Initiation Needs
- Access to the Artifactory CLI and authentication credentials.
- Knowledge of GitHub Actions and the deployment process for dotCLI artifacts.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
```[tasklist]
### Tasks
- [ ] Develop GitHub Action to deploy dotCLI artifacts using Artifactory CLI
- [ ] Test the Action to ensure it correctly deploys artifacts
- [ ] Document the setup and usage of the Action

**Comment by nollymar** [comment]
**Internal QA:** Passed

https://github.com/dotCMS/core/actions/runs/9508140657
