### ISSUE TITLE
Rename and re-include "Count of Sites" metric

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28590]
### Task

Currently we have two issues related to the "Count of Sites" metric:

- [x] 1. Is not named properly. It needs to be renamed from "ACTIVE_SITES_COUNT" to "COUNT_OF_SITES"
- [x] 2. The java class needs to be renamed from "TotalActiveSitesDatabaseMetricType" to "TotalSitesDatabaseMetricType"
- [x] 3. Needs to be re-including in the MetricStatsCollector

### Proposed Objective

Customer Success

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [x] 1. Metric properly named as "COUNT_OF_SITES"
- [x] 2. Metric included in the telemetry endpoint: https://localhost:8080/api/v1/telemetry/stats

**Comment by dsilvam** [comment]
PR: https://github.com/dotCMS/com.dotcms.telemetry/pull/52

**Comment by dsilvam** [comment]
Passed Internal QA: 
Metric properly named. 
Appearing in the results of the endpoint. 


![Image](https://github.com/dotCMS/core/assets/1576794/45a1ad91-83df-4697-b7b3-297d6df68e91)




![Image](https://github.com/dotCMS/core/assets/1576794/2c14afce-a9b1-4fe7-b6ce-5dcdbafa929e)
