### ISSUE TITLE
Spike: Hunt down where resources are still dangling 

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#28624]
### Task

We have a number of places in code where we are writing to disk or creating resources - either files are uploaded or generated by dotCMS that are not being cleaned up .  This also includes external resources such as Elasticsearch indexes.  Here is a non exhaustive list of some of the these 

- [ ] webdav uploads
- [ ] file uploads
- [ ] bundle uploads
- [ ] bundle created/tmp files
- [ ] Indexes created / site search indexes
- [ ] H22 disk cache / when flush cache
- [ ] Saas auto-compilation
- [ ] 

### Proposed Objective

Cloud Engineering

### Proposed Priority

Priority 2 - Important

**Comment by prestonso** [comment]
Assigned to @cobbg per request from @wezell.

**Comment by prestonso** [comment]
Closing per @wezell
