### ISSUE TITLE
UI: Update Base Font Size to 14px

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28724]
### Task description
As a dotCMS user, I want the base font size to be reduced to 14px while keeping the spacings based on 16px to improve readability and design consistency across the website.

```[tasklist]
### Acceptance Criteria
- [ ] The base font size in the UI should be 14px.
- [ ] Spacings between elements should remain consistent at 16px.
- [ ] All text should be legible and easily readable at the new font size.
- [ ] This change should NOT affect native a11y of the browser
``` 

### External Links
N/A

### Assumptions & Initiation Needs
- Assumption: The current font size is set at 16px.
- Initiation: Access to the dotCMS backend to make the necessary CSS changes.
- We need to check ALL pages to make sure nothing breaks

### Quality Assurance Notes & Workarounds
- QA should check all pages to ensure the new font size is consistent and does not cause any readability issues.
- In case of any spacing issues, the QA team should provide feedback for adjustments.

**Comment by dcolina** [comment]
Internal QA: Failed

There are some fonts with the old size, specifically in the block editor. You could notice it in the following video:

https://github.com/user-attachments/assets/70eeb852-b0db-465b-ae6d-1305a0d28c1a

The test was run on:
**Browser**: `Chrome` [Version 127.0.6533.120 (Official Build) (arm64)]
**Docker image**:  `dotcms/dotcms:trunk_600b4f3`

**Comment by valentinogiardino** [comment]
### Note to QA

The text inside the block editor (ProseMirror) remains at 16px. If changes are needed, they will be handled in separate tickets. The same applies to text inside GraphQL query tool (CodeMirror) that remains at 13px.

**Comment by dcolina** [comment]
Internal QA: Needs work

There are a few sections that do not meet with the defined size. Specifically sections PERMISSIONS and RULES in general.

![Image](https://github.com/user-attachments/assets/f0f38b73-3f1f-4c62-aa52-b156c37da7d1)
![Image](https://github.com/user-attachments/assets/693bd29b-df38-4fd5-9577-7dfb0ad6cebb)

Below we can find another sections where the font size must be fixed.

![Image](https://github.com/user-attachments/assets/28555c67-afd7-46b9-9c7a-ecd2b9ebc7af)
![Image](https://github.com/user-attachments/assets/13cdecbc-330c-4aad-83e9-b57ee08a87fb)
![Image](https://github.com/user-attachments/assets/a81fb02d-0419-4c18-b56e-a44727cc39e2)

**Comment by dcolina** [comment]
## Internal QA: Passed.

It was tested on all the supported browsers (Chrome, Firefox, Edge) using the docker image `dotcms/dotcms:trunk_dea1913`.

**Comment by bryanboza** [comment]
Fixed the font-size now is 14px 
![Image](https://github.com/user-attachments/assets/08ee3108-0c36-490d-9462-94ec1a0b5799)
