### ISSUE TITLE
SDK: Support for 404 Pages in Next.JS and Angular

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28817]
### Parent
[28404](https://github.com/dotCMS/core/issues/28404)

### Task description
As a developer, I want to add support for 404 error pages in the example Next.JS and Angular projects so that when a user navigates to a non-existing page, a visually appealing error page is displayed.

```[tasklist]
### Acceptance Criteria
- [ ] The Next.JS example project should display a custom 404 error page when a user navigates to a non-existing route.
- [ ] The Angular example project should show a user-friendly error page when a non-existing route is accessed.
- [ ] Both error pages should provide clear messaging and a link to redirect users back to a valid page.
```

### External Links
N/A

### Assumptions & Initiation Needs
- The Next.JS and Angular example projects are already set up and running.
- The error pages will be designed and implemented following the existing project styling guidelines.

### Quality Assurance Notes & Workarounds
N/A

**Comment by bryanboza** [comment]
Fixed, tested on the last trunk // Docker 

## Next JS
![Image](https://github.com/dotCMS/core/assets/2641437/230240b0-53d3-4491-af62-bef287922ba0)

## Angular
![Image](https://github.com/dotCMS/core/assets/2641437/e7df0162-2e79-4b04-a60f-6cb5ee06330b)
