### ISSUE TITLE
SDK: Update SDK Library and UVE search bar to Use "personaId" Key

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28819]
### Parent
https://github.com/dotCMS/core/issues/30943

### Task description
As a developer working on the dotCMS SDK, I need to update the key used to request a page as a specific persona from `com.dotmarketing.persona.id` to `personaId` for better clarity and consistency.

```[tasklist]
### Acceptance Criteria
- [x] We need to update the UVE query params to be `personaId` as well.
- [x] The SDK library has been updated to use the key `personaId` instead of `com.dotmarketing.persona.id` for requesting pages as a specific persona
- [ ] A notification has been sent to James informing him about the key update in the library.
- [ ] Update all our documentation, including blog posts if possible, we need to speak with Makayla
```

### NOTE

We both in the SDK and in the UVE have to handle the query param as `personaId`, when making the call to the backend we make the change to `com.dotmarketing.persona.id` which is the property that the backend expects

**Comment by rjvelazco** [comment]
### **NOTE IQA**  

1. The SDK has been using `personaId` instead of `com.dotmarketing.persona.id` for over a year now.  
   - **Interface:** SDK Client Interface:
  https://github.com/dotCMS/core/blob/2e5c32d47793da8e7dc34ca0c9a23f1499fea14b/core-web/libs/sdk/client/src/lib/client/sdk-js-client.ts#L82-L87
   - **Implementation Change:** SDK Update
   https://github.com/dotCMS/core/blob/2e5c32d47793da8e7dc34ca0c9a23f1499fea14b/core-web/libs/sdk/client/src/lib/client/sdk-js-client.ts#L258-L259

2. Ensure that `personaId` appears in the search bar.  
3. If `personaId` corresponds to the default persona, it should not be displayed.  
4. In **HEADLESS mode**, the iframe should receive `personaId` instead of `com.dotmarketing.persona.id`.

**Comment by zJaaal** [comment]
Found this issue while testing Traditional Rendering, we are not able to edit traditional rendered pages due to wrong mode sent to the Page API 


## Screenshot
https://github.com/user-attachments/assets/bcbce156-80c9-4648-9af3-fb6ac222b607
## Request 

<img width="683" alt="Image" src="https://github.com/user-attachments/assets/5fd35043-791b-4079-8a23-8ccc59c56e5c" />
