### ISSUE TITLE
UVE: Research of how to use DefinitelyTyped for dotCMS apps and libs

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#28820]
### Parent
[28404](https://github.com/dotCMS/core/issues/28404)

### Task description
As a frontend developer at dotCMS, I need to research and understand how we can utilize for our dotCMS SDK. To add a library that we can share across all our internal and external libraries and provide proper typing for our users.

```[tasklist]
### Acceptance Criteria
- [ ] Presentation created explaining what `DefinitelyTyped` is and how it can be used for dotCMS SDK
- [ ] Clear explanation on the benefits of using `DefinitelyTyped` for our frontend team
- [ ] Step-by-step guide on how to start creating our own library using `DefinitelyTyped`
- [ ] All team members should have a good understanding of how to integrate `DefinitelyTyped` into our workflow
```

### External Links
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master?tab=readme-ov-file

### Assumptions & Initiation Needs
- Collaboration with the frontend team for feedback and implementation

### Quality Assurance Notes & Workarounds
- Ensure that the presentation is clear and informative for all team members
- Provide additional resources or training if needed for team members to fully grasp the concept of `DefinitelyTyped`

### Sub-Tasks & Estimates
Timebox to 1 day.
