### ISSUE TITLE
Updating endpoint to search categories throughout the entire tree of children of a given parent

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#28896]
### Parent Issue

https://github.com/dotCMS/core/issues/28493

### Task

Update the 'categories/children' endpoint to allow searching through the entire category tree starting from a specified inode. This means the search will begin from the specified inode category and then proceed recursively through its children.

It needs to accept partial searches, ala *search_term*. 

Each returned categories need to include an array of its parents. 

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- [ ] * Ability to search by partial words
- [ ] * Array of parents included for each returned/matched category. 
- [ ] * Postman test included

**Comment by freddyDOTCMS** [comment]
PR https://github.com/dotCMS/core/pull/29116

**Comment by oidacra** [comment]
Passed IQA, I can now get all the parents of a searched item and search all the children.

**Comment by josemejias11** [comment]
**Approved**: Tested on **master_d501a60**, Docker, macOS 14.5, FF v126.0.1
