### ISSUE TITLE
Spike: Identify which sensitive admin actions are and are not logged

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29009]
## Task

We need to identify which of the following actions, when performed by any user, are logged.  Specifically, for each of the actions, we need to identify:
* Which log file (if any) is it logged to?
* What information is in the log message:
    * Can the affected object (user, site, etc.) be identified from the log message?
    * Can the user who performed the action be identified from the log message?
* Is the action logged differently when performed from the BE vs. from the API?

## Actions

1. Users & Permissions:
- [x] Add a new user
- [x] Delete a user
- [x] Enable/Disable a user
- [x] Assign a new role to a user (specifically the CMS Admin role)
- [x] Remove a role from a user (specifically the CMS Admin role)
- [x] Impersonate a user (using the Login As functionality)
2. Plugins
- [x] Upload a plugin
- [x] Start a plugin
- [x] Stop a plugin
- [x] Restart OSGI
4. Sites
- [x] Add a site
- [x] Edit a site
- [x] Start a site
- [x] Stop a site
- [x] Delete a site
5. Maintenance portlet
- [x] Re-index
- [x] Deactivate an index
- [x] Activate an index
- [x] Clear an index
- [x] Delete an index
6. Configuration portlet
- [x] Upload license pack
- [x] Reset license

### Proposed Objective

Customer Success

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

Provide a document with a table listing each of the actions on one row, with the name of the action in the first column, and answers to each of the questions in subsequent columns, something like the following:

| Action | Logged (Y/N) | Log file | Object Logged (Y/N) | User Logged (Y/N) | API Calls Logged (Y/N) |
|:-------|:------------:|:--------:|:-------------------:|:-----------------:|:----------------------:|
| Add a user | Y | dotcms.log | Y | Y | Y |
| Delete a user | Y | access.log | N | Y | Y |

Time-box the effort to 1 day's worth of work.

**Comment by jcastro-dotcms** [comment]
Here's the document with the results of this investigation: https://docs.google.com/spreadsheets/d/1n-jDGTuZAmErUlVT549CYMENnj5oemLRTTmgrkJjwG8/edit?usp=sharing
