### ISSUE TITLE
Improvements in the dotcms/ui package

### ISSUE THREAD

**Issue by nicobytes** [dotCMS/core#29056]
### Task

- [ ] Use the new Angular syntax
- [ ] Use Jest for unit testing
- [ ] Organize folders

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 4 - Trivial

```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/29050
- [ ] https://github.com/dotCMS/core/issues/29013
- [ ] https://github.com/dotCMS/core/issues/29015
```
