### ISSUE TITLE
UVE: Update the Config for devURLWhitelist

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#29069]
### Task description
As a dotCMS developer, I need to update the UVE config to change the `devURLWhitelist` for `allowedDevURLs`.

```[tasklist]
### Acceptance Criteria
- [x] The devURLWhitelist in the UVE config should be updated with the new allowedDevURLs.
- [x] The changes should be reflected in the app after the update.
- [x] The documentation should be updated to reflect the changes made to the devURLWhitelist.
```

### External Links
N/A

### Assumptions & Initiation Needs
N/A

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
N/A

**Comment by zJaaal** [comment]
## Internal QA Passed

It works as expected with new name in the properties

## Screenshots


https://github.com/dotCMS/core/assets/63567962/d7318834-09b0-4b39-bec5-538662ff11c0

**Comment by bryanboza** [comment]
Fixed, tested on the latest trunk // Docker //  FF
