### ISSUE TITLE
Document PageResource endpoint using Swagger

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#29089]
### Parent Issue

#28600

### Task

Create missing Swagger documentation for the [PageResource](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java) endpoint. Endpoint path: `v1/page`

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

We have to make sure that: 
- [ ] It has a general description of what each endpoint does
- [ ] All the input parameters on each method are documented
- [ ] We provide a clear example of how to use them
- [ ] Describe all the possible responses

If possible, provide examples that work on demo site.

### Sub-Tasks & Estimates

- [ ] /v1/page/_check-permission
- [ ] /v1/page/{pageId}/_deepcopy
- [ ] [/v1/page/{pageId}/content](https://github.com/dotCMS/core/issues/29362)
- [ ] [/v1/page/{pageId}/content/tree](https://github.com/dotCMS/core/issues/29362)
- [ ] /v1/page/{pageId}/languages
- [x] [/v1/page/{pageId}/layout](https://github.com/dotCMS/core/issues/29143)
- [ ] /v1/page/{pageId}/personas
- [ ] /v1/page/{pageId}/render/versions
- [ ] /v1/page/actions
- [ ] /v1/page/copyContent
- [ ] /v1/page/json/{uri}
- [x] [/v1/page/layout](https://github.com/dotCMS/core/issues/29143)
- [ ] /v1/page/renderHTML/{uri}
- [ ] /v1/page/search
- [ ] /v1/page/types
