### ISSUE TITLE
Documentation for v1/page/layout

### ISSUE THREAD

**Issue by gavriella-dotcms** [dotCMS/core#29143]
### Parent Issue

[29089](https://github.com/dotCMS/core/issues/29089)

### Task

Create Swagger documentation for the v1/page/layout and v1/page/{pageId}/layout paths in the [PageResource](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java) endpoint.

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [ ] Description of page layout endpoint
- [ ] Input method parameters
- [ ] Insure required fields are laid out

**Comment by jdcmsd** [comment]
After some review, this one needs a bit more work.

1. We can just say "page" instead of "HTML page"
2. It would be helpful to have some indication of what properties the body payload is looking for, and how it expects to receive them in specific
3. Seems the `title` field inside the layout property doesn't do anything, but I guess that's fine if it's already got one at the top level.
4. The default schematized body includes `siteId` but will not accept that property; instead is looking for `hostId`
    - This is an interesting issue; the PageForm class itself has a `siteId` property, so it's correctly ascertaining that from reflection. However, something must have changed elsewhere. 
5. Also preloads the request body with an `anonymousLayout` property that it says it does not recognize, and will not accept; we shouldn't include properties that will only cause errors.
    - The PageForm class seems to contain an `isAnonymousLayout` method but it is flagged by IntelliJ as unused, so there may be some deeper issues with this endpoint!
6. Contrary to the description -- including of the docstrings of the code itself -- this endpoint doesn't seem to actually link a page to an existing template, as far as I can see. Nothing I tried resulted in this.
    - If multiple pages are associated with the template, it instead creates a new template with the name specified in `entity.title`, which appears grayed out like a system template. This does not appear to be the standard way we handle per-page layouts, so the behavior here is very confusing to me.

Even more confusingly, in my early tests, using this endpoint resulted in **direct editing** of the template connected to the page, ultimately leaving that template in an unpublished/working state. However, now that I've tried other things, such as having multiple pages refer to one template, I seem to be unable to reproduce this outcome. Now it just does the "new gray system template with different name" thing every time.

All in all, this may not have been a very good choice on my part for a first endpoint to assign — it's got some puzzles baked in.

**Comment by jdcmsd** [comment]
Forgot to specify: The above comment is referring to `POST /v1/page/{pageId}/layout`. The other one, `POST /v1/page/layout` is a different challenge; it seems to object to some of the same issues (wants `hostId` instead of `siteId`, doesn't like `anonymousLayout`, etc). However, unlike `{pageId}/layout`, I haven't successfully gotten this one to return 200 at all, yet; some other unknown factor is causing NPE 500s. More testing is needed.

@gavriella-dotcms, were you able to get that one to successfully return?
