### ISSUE TITLE
Swagger Documentation for v1/page Content Endpoints

### ISSUE THREAD

**Issue by gavriella-dotcms** [dotCMS/core#29362]
### Parent Issue

https://github.com/dotCMS/core/issues/29089

### Task

Create Swagger documentation for the `v1/page/{pageId}/content` and `v1/page/{pageId}/content/tree` paths in the [PageResource](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/page/PageResource.java) endpoint.

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [ ] Description of page content endpoints
- [ ] Input method parameters for both /content and /content/tree
- [ ] Insure required fields are laid out
