### ISSUE TITLE
CICD: Automate Deployment of Empty Starter via GitHub Actions

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#29376]
### User Story
As a developer, I need to automate the deployment of empty starters using GitHub Actions. This task will include asking for a summary of changes, manually preparing the empty starter, publishing it on Artifactory, and sending a notification on Slack.

### Acceptance Criteria
- The process to deploy an empty starter is automated, except for its manual preparation.
- GitHub Actions prompts for a summary of changes included in the starter.
- The prepared empty starter is automatically published to Artifactory.
- A Slack notification is sent upon successful publication.

### Proposed Objective
Integrations

### Proposed Priority
Priority 2 - Important

### dotCMS Version
N/A

### External Links
N/A

### Assumptions & Initiation Needs
- Access to Artifactory for publishing and Slack for notifications.
- Familiarity with the manual preparation process for empty starters.
- Familiarity with GitHub Actions setup and configuration.

### Quality Assurance Notes & Workarounds
N/A

### Sub-Tasks & Estimates
```[tasklist]
### Tasks
- [ ] Define the manual preparation process for empty starter
- [ ] Create a GitHub Action to automate publishing to Artifactory
- [ ] Set up Slack notifications for the publication event

**Comment by dcolina** [comment]
An Empty Starter Server has been deployed as: [https://corpsites-empty-starter.dotcms.cloud/](https://corpsites-empty-starter.dotcms.cloud/dotAdmin/#/public/login?r=1723143274425)
