### ISSUE TITLE
Duplicate IDs in a Content Type Despite Unique Field Constraint

### ISSUE THREAD

**Issue by Neehakethi** [dotCMS/core#29459]
### Problem Statement

We are experiencing duplicate IDs for a content type in dotCMS, even though the field is marked as unique. Simultaneous double inserts from different pods do not explain this issue, and it occurs even with the indexPolicy=WAIT_FOR setting.

An example scenario :

Occurrence:
A contentlet with ID XXXX has existed since YYYY.
In June, two new contentlets were created with the same ID.
In July, another contentlet with the same ID was created.

Suspected initial cause: 
Index policy timing issues.
findings: The issue persists even with the WAIT_FOR policy.
Ideas proposed: Use database-level constraints or a custom script for unique values.

We need to identify why the unique constraint is not working as expected and how we can address this issue. Potential solutions include:

Adding a unique key constraint at the database level.
Implementing a custom script to generate unique values based on configurable fields.

### Steps to Reproduce

https://dotcms.zendesk.com/agent/tickets/117183

This was happening specifically with a customer

### Acceptance Criteria

We should avoid creating duplicate id's for unique fields in every possible scenario

### dotCMS Version

23.10.24 LTS

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

https://dotcms.zendesk.com/agent/tickets/117183

### Sub-Tasks & Estimates
```[tasklist]
### Tasks
- [ ] https://github.com/dotCMS/core/issues/30275
- [ ] https://github.com/dotCMS/core/issues/30277
- [ ] https://github.com/dotCMS/core/issues/30279
- [ ] https://github.com/dotCMS/core/issues/30281
- [ ] https://github.com/dotCMS/core/issues/30285
- [ ] https://github.com/dotCMS/core/issues/30306
- [ ] https://github.com/dotCMS/core/issues/30815
- [ ] https://github.com/dotCMS/core/issues/30894
```

**Comment by john-thomas-dotcms** [comment]
The proposed "full" solution to this still hasn't been fully agreed on, since proposed solutions may not address all use cases.

So, for a first pass, we're going to just change the existing Elasticsearch query to a DB query.

We will need to verify that this change doesn't cause a performance hit or bottlenecks waiting for the DB query to return.  To verify this, we may need to make a copy of the customer system that we can test against.

**Comment by john-thomas-dotcms** [comment]
Good poin from J. Sanchez: We should enable/disable the DB/ES query functionality via a config param.

**Comment by freddyDOTCMS** [comment]
Here the POC done to detect what is the best solution #29707

**Comment by crak-mess** [comment]
Hello, is there any ETA on this fix ?
Thank you very much.

**Comment by m27iu4** [comment]
https://dotcms.freshdesk.com/a/tickets/28936

**Comment by dsilvam** [comment]
Passed IQA: This is working and got released in `25.01.17`. Tested on Auth.

**Comment by dsilvam** [comment]
Feature Flag to active this:
```
FEATURE_FLAG_DB_UNIQUE_FIELD_VALIDATION = true|false (default false in Java code)
```

**Comment by yolabingo** [comment]
Note that the initial DB modification after changing enabling this feature can take some time for large data sets - on the order of 40 minutes in one test case. 
You must ensure that no new content is added during the time this database change is under way.
