### ISSUE TITLE
[Logging] : Log more details on sensitive admin actions

### ISSUE THREAD

**Issue by jcastro-dotcms** [dotCMS/core#29486]
### Parent Issue

https://github.com/dotCMS/core/issues/29009

### Task

The outcome of this spike: https://github.com/dotCMS/core/issues/29009 yielded a list of sensitive action in the dotCMS back-end that are not logging important details. This ticket is aimed to solve that. The result of the investigation can be found here: https://docs.google.com/spreadsheets/d/1n-jDGTuZAmErUlVT549CYMENnj5oemLRTTmgrkJjwG8/edit?gid=0#gid=0

```[tasklist]
### Users & Permissions:
- [ ] Add a new user
- [ ] Enable/Disable a user
- [ ] Remove a role from a user (specifically the CMS Admin role)
```

```[tasklist]
### Plugins:
- [ ] Upload a plugin
- [ ] Start a plugin
- [ ] Stop a plugin
- [ ] Restart OSGI
```

```[tasklist]
### Maintenance portlet:
- [ ] Re-index
- [ ] Deactivate an index
- [ ] Activate an index
- [ ] Clear an index
```

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

The updated logging must be clear on what user is triggering a specific action, as well as any other detail deemed necessary to provide Users/Support Engineers with as much information as possible.
