### ISSUE TITLE
Starter Site Localization Improvements

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29494]
### User Story

Now that phase 1 of the Localization improvements has been completed, we need to update the starter site to utilize some of the new features, highlight our Localization features, and provide better examples of best practices for implementing Localization in dotCMS.

### Acceptance Criteria

Complete all issues in the task list (see below)

### Proposed Objective

Technical User Experience

### Proposed Priority

Priority 3 - Average

### Sub-Tasks & Estimates

- [ ] https://github.com/dotCMS/core/issues/25610
- [ ] Update Starter to Have Sitemap for Each Locale
- [ ] https://github.com/dotCMS/core/issues/23995
