### ISSUE TITLE
Localization Improvements: Future

### ISSUE THREAD

**Issue by john-thomas-dotcms** [dotCMS/core#29493]
### User Story

There are a number of minor bug fixes and enhancements which weren't required to deliver the first phase of Localization improvements.  This epic collects all of these smaller improvements into one place so we can implement them as a group when the next phase of Localization improvement is done.

### Acceptance Criteria

Complete all cards in the task list (above).

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Sub-Tasks & Estimates

- [ ] https://github.com/dotCMS/core/issues/28682
- [ ] https://github.com/dotCMS/core/issues/25612
- [ ] https://github.com/dotCMS/core/issues/25611
- [ ] https://github.com/dotCMS/core/issues/25609
- [ ] Re-Translate Admin Tools
