### ISSUE TITLE
Authentication API Swagger Documentation

### ISSUE THREAD

**Issue by gavriella-dotcms** [dotCMS/core#29616]
### Parent Issue

#28600

### Task

Create missing Swagger documentation for the [Authentication](https://www.dotcms.com/docs/latest/rest-api-authentication) endpoint. Endpoint path is `v1/authentication`

### Proposed Objective

Documentation

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [ ] General description for endpoints
- [ ] Document all input parameters
- [ ] Describe all the possible responses
- [ ] Test with secure authentication methods

Provide examples that work on demo site if possible.

### Sub-Tasks & Estimates

Authentication Endpoints:
- [ ] `/v1/authentication`
- [ ] `/v1/authentication/api-token`
- [ ] `/v1/authentication/logInUser`

**Comment by bryanboza** [comment]
Fixed.
