### ISSUE TITLE
Centralize the logic to read feature flag values

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#29900]
### Task

As a developer, I'd like to have a centralized logic to check if a feature flag is on/off. An utility method was implemented [here](https://github.com/dotCMS/core/pull/29897). It works for BE, however, we have to make sure that the endpoint invoked in FE to get feature flags works in a similar way. It might require changes in FE.

FE developers use the ConfigurationResource to get a FF value, specifically, [this line](https://github.com/dotCMS/core/blob/master/dotCMS/src/main/java/com/dotcms/rest/api/v1/system/ConfigurationResource.java#L144) does the magic . When the value is received in FE, we evaluate if that flag is [found](https://github.com/dotCMS/core/blob/faa8718b0b63752e697cd86cb8f997e4b6820479/core-web/libs/data-access/src/lib/dot-properties/dot-properties.service.ts#L64-L68) . 

We should have all the logic related to FF verifications in one place, testable and available to everyone to be used with just one call.

### Proposed Objective

Code Maintenance

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

The logic to be implemented should have test coverage

**Comment by spbolton** [comment]
@nollymar I have a good idea of how we should structure the feature flags and provide to the ui but we should have some more discussions on this,  there maybe something we can do that helps quickly but I don't want us to quickly implement something on gardening day that does not fit into larger goals with this.   The scope of this just needs to be clarified and reviewed before we start coding,  not sure if it is defined enough to be ready for a gardening day task. 

Logically a feature flag is just a regular configuration that is handled as a boolean,  it should be the main switch for the logical grouping of configurations for a "feature" we can encode this using hierarchical naming.  It can be encoded as "enabled" at the end of the feature key.  

Before going into the actual naming it is key to distinguish between the different strategies for specifying a configuration key as there is continuing confusion we should work towards fixing the standardization so we can easily map between different implementations of configuration keys.

A configuration key can be namespaced using a heirarchical structure.  A dot "." can be used to separate the parts of the key e.g.

myfeature1.mysubfeature1.mysubsubfeature1.enabled = true
myfeature1.mysubfeature1.mysubsubfeature1.max = 100

This flat structure can logically map to yaml also e.g.

```
myfeature1:
  mysubfeature1:
     mysubsubfeature1:
         enabled: true
         max: 100
```

the elements can contain multiple words by using a "-" e.g.

my-feature1.my-subfeature1.my-subsubfeature1.enabled = true

This format can also be converted to and from Camel case e.g.
myFeature1.mySubFeature1.mySubSubfeature1.enabled = true

Environment variables on linux do not allow the - and must be upper case.  The other forms can be easily converted to and from each other.  Each of these existing formats can be converted to an equivalent environment variable format, but cannot be converted the other way.  The mapping is to convert all special characters e.g. the dot and dashes to underscore and make the text uppercase e.g. 

my-feature1.my-subfeature1.my-subsubfeature1.enabled
can be represented by the environment variable
MY_FEATURE1_MY_SUBFEATURE1_MY_SUBSUBFEATURE1_ENABLED=true

If we used this format for the internal representation though we loose the information on the structure.  e.g. this could represent the following, we have lost the distinction between the dots and dashes or Uppercase 

my.feature1.my.subfeature1.my.subsubfeature1.enabled

In our existing Config class any core property can be any combination of case and include dots and dashes.  e.g.

Config.getStringProperty("analytics.accesstoken.renewjob.cron")
this is configured in our src/main/resources/dotmarketing-config.properties as
analytics.accesstoken.renewjob.cron=0 0/1 * * * ?

We already have code in our ConfigClass that will check to see if this has been overriden in the environment variables where it uses a "DOT_" prefix and handles the mapping to uppercase and underscores therefore without a change to Config.getStringProperty("analytics.accesstoken.renewjob.cron"). we can update this by setting the environment variable key
DOT_ANALYTICS_ACCESSTOKEN_RENEWJOB_CRON

Where we have confusion and inconsistency in the code is where we have something like 
Config.getStringProperty("DOTGENERATED_DEFAULT_PATH", LOCAL)
We do not need to use uppercase here to support environment variables.  When set like this any change in the value in the config files would not be able to tell if default and path are separate subfeatures e.g. it could represent dotgenerated.default.path or dotgenerated.default-path
This key is further badly structured as only env vars prefixed with DOT_ are passed and available to override, so to set this as an environment variable we would have to use "DOT_DOTGENERATED_DEFAULT_PATH". the extra DOT is not really needed here.
To note that when an environemnt variable is set it does match and override property requests with or without the DOT_ prefix e.g.

e.g. when DOT_ANALYTICS_ACCESSTOKEN_RENEWJOB_CRON is passed on the environment it would override the values for both
Config.getStringProperty("DOT_ANALYTICS_ACCESSTOKEN_RENEWJOB_CRON", LOCAL)
Config.getStringProperty("ANALYTICS_ACCESSTOKEN_RENEWJOB_CRON", LOCAL)
The same does not go for any value set in the properties file which would have to be exactly as defined with the same case.

We can progressively update the code and change "DOTGENERATED_DEFAULT_PATH" for example to "dotgenerated.default-path" ensuring this is used in properties files without effecting the environment variable updates for this.

## Rules for keys
For all new properties we should follow the module.submodule.configkey structure where configkey can be "enabled". which makes it into a feature flag.  each element should use a dash to represent spaces in the elements (kebab case) and be lower case and this format would be used in property files.   We may also be able to support camel case e.g. defaultPath instead of default-path.  with conversion between the two but should be consistent where we use each and not mix and match in the same contexts. e.g. always use kebab in properties files. 

# How this relates to front end feature flags access.
If the config keys are grouped hierarchically as discussed we are now able to make use of this structure to allow the ConfigResource to not only return individual keys but to return a set of keys 

currently we either get all whitelisted config properties or have to specify individual keys with the format

/v1/configuration/config?keys=analytics.accesstoken.renewjob.cron,DEFAULT_STORAGE_TYPE

The current endpoint also requires the caller to add a prefix to each of list:,boolean:, number: if they want the value to not be a string value.

We can alter the endpoint to allow config to be selected using a prefix or other filter when they are structured as described.

In the case of the following keys

myfeature1.mysubfeature1.mysubsubfeature1.enabled = true
myfeature1.mysubfeature1.mysubsubfeature1.max = 100
myfeature1.mysubfeature2.mysubsubfeature1.enabled = true
myfeature1.mysubfeature2.mysubsubfeature1.max = 100

we could get all these keys (4) with
/v1/configuration/config?prefix=myfeature1
or get just subfeature 1 keys 
/v1/configuration/config?prefix=myfeature1.mysubfeature1
If we want to we could also use other pattern matching to filter e.g. to return all enabled features
/v1/configuration/config?filter=*.enabled

We can add a level backward compatibility for the env var formatted properties stored internally e.g. something like
MYFEATURE1_MYFEATURE2_ENABLED 
could be returned by the myfeature1.mysubfeature2 pattern or the *.enabled by assuming the _ is a . and convert to lowercase it would just be confusing in some cases.  We can try to match the format and case to the request, but we should try to not use the env var format for the query for consistency going forward unless we have to in the short term.

With a consistent key structure we could add more info and metadata to feature flag e.g.

```
myfeature1.mysubfeature1.enabled = true
myfeature1.mysubfeature1.ui-feature = true
myfeature1.mysubfeature1.description = true
myfeature1.mysubfeature1.flag1 = 1
myfeature1.mysubfeature1.flag2 = true
myfeature1.mysubfeature1.ui-flags.flag1.type = number
myfeature1.mysubfeature1.ui-flags.flag1.description = How many Items
myfeature1.mysubfeature1.ui-flags.flag2.type = boolean
myfeature1.mysubfeature1.ui-flags.flag2.type = "Turn on something"
```

This is a valid structure but the nice thing about this is it can also be represented directly in yaml and can be converted either way.

```
myfeature1:
  mysubfeature1:
    enabled: true
    ui-feature: true
    description: true
    flag1: 1
    flag2: true
    ui-flags:
      flag1:
        type: number
        description: "How many Items"
      flag2:
        type: boolean
        description: "Turn on something"
```

By providing the ability to filter on keys and using a proper structure we can provide a lot of flexibility to how feature flags we want to expose to the ui can be handled and returned.

We can follow up with optimizations for the filtering if needed 

Note: the use of the prefix e.g. number:, boolean: should not be necessary as long as we always pass back a string format the client can convert the string types to whatever it needs rather than requesting the server to do it.

**Comment by spbolton** [comment]
Additional considerations from prototype
There can be config properties that are only defined in the code the keys for these would only be added to the list when it is first accessed.   Properties are loaded from the environment and the config properties files up front so adding here would be a simple fix if this is an issue.

**Comment by spbolton** [comment]
We have a resource for pulling all localized properties currently that relies on a whitelist that is hardcoded in the source. on top of the hard coupling issues there are with this we can see the inconsistencies we currently have with some FEATURE_FLAG._*and other CONTENT_EDITOR2_ENABLED.   The new code will enable us to search/filter on both of these different formats but inconsistencies will be confusing until we standardise.

Also to note that in the current internals we may end up with combinations of properties that effectively map to the same thing e.g. DOT_MYPROP and MYPROP.   We can still filter on these and the code will return the original value but we need to be aware of this.    This filtering resource may help us to identify these.

I have removed the whitelist to allow for the filtering and maintined the blackist,  but we should still be aware that this does list all properties not in the blacklist and any security considerations of this whether we need a more complex whitelist structure of other ways to prevent a developer adding a new config that should be a secret and ends up exposed.  



private static final Set<String> WHITE_LIST = ImmutableSet.copyOf(
			Config.getStringArrayProperty("CONFIGURATION_WHITE_LIST",
					new String[] {"EMAIL_SYSTEM_ADDRESS", "WYSIWYG_IMAGE_URL_PATTERN", "CHARSET","CONTENT_PALETTE_HIDDEN_CONTENT_TYPES",
					"FEATURE_FLAG_EXPERIMENTS", "DOTFAVORITEPAGE_FEATURE_ENABLE", "FEATURE_FLAG_TEMPLATE_BUILDER_2",
					"SHOW_VIDEO_THUMBNAIL", "EXPERIMENTS_MIN_DURATION", "EXPERIMENTS_MAX_DURATION", "EXPERIMENTS_DEFAULT_DURATION", "FEATURE_FLAG_SEO_IMPROVEMENTS",
					"FEATURE_FLAG_SEO_PAGE_TOOLS", "FEATURE_FLAG_EDIT_URL_CONTENT_MAP", "CONTENT_EDITOR2_ENABLED", "CONTENT_EDITOR2_CONTENT_TYPE", "FEATURE_FLAG_NEW_BINARY_FIELD", "FEATURE_FLAG_ANNOUNCEMENTS", "FEATURE_FLAG_NEW_EDIT_PAGE"  }));

**Comment by spbolton** [comment]
Futher we will need to decide if we need to limit the number of results returned or provide paging if the filter is not specific enough

**Comment by spbolton** [comment]
Example queries

```
http://localhost:58546/api/v1/configuration/config?endsWith=.enabled

{"entity":{"CONTENT_EDITOR2_ENABLED":"false","ES_TLS_ENABLED":"false","LOCALIZATION_ENHANCEMENTS_ENABLED":"false"},"errors":[],"i18nMessagesMap":{},"messages":[],"pagination":null,"permissions":[]}

http://localhost:58546/api/v1/configuration/config?contains=enable
{"entity":{"CONTENT_EDITOR2_ENABLED":"false","ENABLE_CLICKSTREAM_TRACKING":"false","ENABLE_CONTENT_REINDEXATION_THREAD":"false","ENABLE_CONTENT_REVIEW_THREAD":"false","ENABLE_DELETE_OLDER_CLICKSTREAMS":"false","ENABLE_NAV_PERMISSION_CHECK":"false","ENABLE_PUBLISHER_QUEUE_THREAD":"true","ENABLE_SCRIPTING":"false","ENABLE_USERS_TO_DELETE_THREAD":"false","ESCALATION_ENABLE":"true","ES_TLS_ENABLED":"false","LOCALIZATION_ENHANCEMENTS_ENABLED":"false","linkchecker.enable_email_notification":"false","linkchecker.enablejob":"false"},"errors":[],"i18nMessagesMap":{},"messages":[],"pagination":null,"permissions":[]}

http://localhost:58546/api/v1/configuration/config?contains=FEATURE
{"entity":{"FEATURE_FLAG_TELEMETRY":"false"},"errors":[],"i18nMessagesMap":{},"messages":[],"pagination":null,"permissions":[]}

http://localhost:58546/api/v1/configuration/config?contains=enable&caseSensitive=true
{"entity":{"linkchecker.enable_email_notification":"false","linkchecker.enablejob":"false"},"errors":[],"i18nMessagesMap":{},"messages":[],"pagination":null,"permissions":[]}

http://localhost:58546/api/v1/configuration/config?contains=ENABLE&caseSensitive=true
{"entity":{"CONTENT_EDITOR2_ENABLED":"false","ENABLE_CLICKSTREAM_TRACKING":"false","ENABLE_CONTENT_REINDEXATION_THREAD":"false","ENABLE_CONTENT_REVIEW_THREAD":"false","ENABLE_DELETE_OLDER_CLICKSTREAMS":"false","ENABLE_NAV_PERMISSION_CHECK":"false","ENABLE_PUBLISHER_QUEUE_THREAD":"true","ENABLE_SCRIPTING":"false","ENABLE_USERS_TO_DELETE_THREAD":"false","ESCALATION_ENABLE":"true","ES_TLS_ENABLED":"false","LOCALIZATION_ENHANCEMENTS_ENABLED":"false"},"errors":[],"i18nMessagesMap":{},"messages":[],"pagination":null,"permissions":[]}

```

**Comment by spbolton** [comment]
# Possible Follow up work
- [] UI Work to make use of this changed endpoint
- [] Work on consistency and fixed guidelines on naming for feature flags and other feature config values
- [] Possible Alias mapping configuration allowing us to change config keys system wide but still support the old key names as deprecated
- [] Refactor to use Smalrye Config as a wrapper for all our configuration
