### ISSUE TITLE
Update docker-compose examples with Redis and cluster mode

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#29909]
### Parent Issue

No parent issue identified.

### User Story

As a developer, I want the `docker-compose` examples using Redis and cluster mode to be updated with the latest database image, `pgvector/pgvector:pg16`, to ensure compatibility and optimal performance with the latest features.

### Acceptance Criteria

1. The `docker-compose` examples should:
   - Be updated to use the `pgvector/pgvector:pg16` image for the database.
   - Include necessary configuration changes to support the new image.
2. The examples should be tested to ensure they execute correctly with the updated image.
3. Any issues or failures encountered during testing should be documented and fixed.

### dotCMS Version

Applicable to all versions using `docker-compose` examples with Redis.

### Proposed Objective

Integrations

### Proposed Priority

Priority 2 - Important

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

No external links provided.

### Assumptions & Initiation Needs

1. Confirm that the `pgvector/pgvector:pg16` image is compatible with the current application and examples.
2. Ensure access to the `docker-compose` files and Redis configuration.

### Quality Assurance Notes & Workarounds

Test the updated examples across different environments to confirm they work as expected with the new database image.

### Sub-Tasks & Estimates

- [ ] Update the `docker-compose` examples to use the `pgvector/pgvector:pg16` image.
- [ ] Validate the execution of the examples and identify any compatibility issues.
- [ ] Implement fixes for any issues found during testing.
- [ ] Document the changes and update any relevant documentation or README files.

**Comment by valentinogiardino** [comment]
### IQA PASSED
Docker compose examples are working as expected using `pgvector/pgvector:pg16`

#### Cluster mode
<img width="1414" alt="image" src="https://github.com/user-attachments/assets/f3473947-f89d-4c13-837c-9fcef0eee79e">

#### With Redis Session
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/1665afc4-747e-4b4d-8798-b6f147a8dea7">

#### With Redis
<img width="1414" alt="image" src="https://github.com/user-attachments/assets/afad8e6b-50a3-4f37-8c82-5a3f7452bbb6">
