### ISSUE TITLE
GitHub Actions workflow failing due to API rate limit exceeded

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#30073]
### Parent Issue

No parent issue identified.

### Problem Statement

The GitHub Actions workflow is encountering an error due to API rate limits being exceeded for the site ID installation. This issue is critical as it directly affects the execution of the developer workflow, causing delays and interruptions. The specific error message received is:

```
API rate limit exceeded for site ID installation. If you reach out to GitHub Support for help, please include the request ID E7C3:39F39A:911EBA8:117896EF:66E40ED1 and timestamp 2024-09-13 10:07:13 UTC. - https://docs.github.com/rest/overview/rate-limits-for-the-rest-api
```

### Steps to Reproduce

1. Trigger a GitHub Actions workflow that interacts with the GitHub API.
2. Observe the error message when the API rate limit is reached.

### Acceptance Criteria

1. The GitHub Actions workflow should:
   - Be able to execute without interruption due to API rate limits.
   - Handle API rate limits gracefully to avoid disruptions to the developer workflow.
   - Include monitoring or alerts if the rate limit threshold is approached.

### dotCMS Version

Not applicable.

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

- Refer to GitHub documentation: [Rate limits for the REST API](https://docs.github.com/rest/overview/rate-limits-for-the-rest-api)

### Assumptions & Initiation Needs

1. Identify if the rate limits are being reached due to increased activity or other underlying issues.
2. Explore options such as caching, optimizing API calls, or using authenticated requests to increase rate limits.

### Quality Assurance Notes & Workarounds

Currently, there is no workaround; the issue needs immediate resolution to restore the normal execution of workflows.

### Sub-Tasks & Estimates

- [ ] Investigate the cause of the API rate limit being exceeded.
- [ ] Identify possible solutions to prevent rate limit issues, such as API call optimization or authenticated requests.
- [ ] Implement the necessary changes and validate the fix.
- [ ] Test the GitHub Actions workflow to ensure it runs smoothly without hitting rate limits.

**Comment by sfreudenthaler** [comment]
looks like this was introduced when working on https://github.com/dotCMS/core/issues/28259
