### ISSUE TITLE
SDK: Improve HTML structure in dotCMS React SDK

### ISSUE THREAD

**Issue by fmontes** [dotCMS/core#30137]
### Task description
As a developer working with the dotCMS React SDK, I want to update the `@dotcms/react` package to include an extra container div in the rows and improve the HTML structure within the `<DotcmsLayout />` component. This will give developers more control over the layout and styling of the components.

```[tasklist]
### Acceptance Criteria
- [ ] The `@dotcms/react` package is updated to include an additional container div within the rows.
- [ ] The HTML structure within the `<DotcmsLayout />` component is improved for better developer control.
- [ ] Developers can easily customize the layout and styling of components using the updated SDK.
```

**Comment by fmontes** [comment]
### Note to QA

Before this change, the row HTML looked like this:

```
<div class="row-module custom-row-classes">
    <div class="column-module custom-column-classes">
        <!-- HERE GOES THE CONTENT -->
    </div>
</div>
```

After these changes, it should look like this:

```
<div class="custom-rows-classes">
    <div class="container">
        <div class="row-module">
            <div class="column-module">
                <div class="custom-column-classes">
                    <!-- HERE GOES THE CONTENT -->
                </div>
            </div>
        </div>
    </div>
</div>
```

The `custom-rows-classes` and `custom-column-classes` are the classes users can add from the template editor:

![CleanShot 2024-10-01 at 09 31 57@2x](https://github.com/user-attachments/assets/6479a6b7-67b8-4cbd-8e2d-f3034f24ac97)

**Comment by valentinogiardino** [comment]
### IQA PASSED

Tested on:
```
dotcms/dotcms:trunk_a93b537
"@dotcms/client": "0.0.1-alpha.38",
"@dotcms/react": "0.0.1-alpha.38",
```
![image](https://github.com/user-attachments/assets/7fcdcafe-072b-4e31-95bb-dc07bf9f917b)

#### Applying custom classes

![image](https://github.com/user-attachments/assets/739963d2-b705-4108-9af6-1c7c6e2ab4eb)

**Comment by bryanboza** [comment]
Fixed now it have a better structure and still working as expected! 


Tested on the latest trunk // Docker // FF
