### ISSUE TITLE
Fix runner configuration in LTS Release: Update CLI native build runners to specific versions

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#30166]
### Parent Issue

No parent issue identified.

### Problem Statement

The CLI native build is now failing in the Release LTS due to the following issue:

```
RUNNERS='[{ "os": "ubuntu-latest", "label": "Linux" }, { "os": "macos-latest", "label": "macOS-Intel" }, { "os": "macos-13-xlarge", "label": "macOS-Silicon" }]'
```

The `macos-13-xlarge` tag no longer exists, and `macos-latest` needs to be replaced with the correct runner. Additionally, we need to specify nominal versions for Ubuntu and the other runners instead of using "latest" to avoid non-repeatable builds that are susceptible to remote changes.

### Steps to Reproduce

1. Run the CLI native build on the Release LTS pipeline.
2. Observe the failure due to incorrect runner tags and reliance on "latest" versions.

### Acceptance Criteria

1. The build configuration should:
   - Use specific nominal versions for all runners instead of "latest" to ensure repeatable and stable builds.
   - Replace the `macos-13-xlarge` and `macos-latest` with the correct runner versions that are supported and reliable.
   - Ensure all changes maintain the integrity of the LTS release, minimizing disruptions caused by environment changes.

### dotCMS Version

Applicable to the LTS Release.

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

No external links provided.

### Assumptions & Initiation Needs

1. Review and identify the correct nominal versions for Ubuntu, macOS-Intel, and macOS-Silicon runners.
2. Ensure that the build configuration is updated across all relevant areas to avoid similar issues.

### Quality Assurance Notes & Workarounds

Currently, no workaround is available; the build configuration must be updated to proceed.

### Sub-Tasks & Estimates

- [ ] Identify and replace "latest" versions with specific nominal versions for all runners.
- [ ] Test the updated build configuration to ensure compatibility and stability.
- [ ] Validate the updated configuration across all relevant environments and workflows.

**Comment by nollymar** [comment]
The LTS was published successfully
