### ISSUE TITLE
Runtime error in CICD PR Checks due to incompatible logical expression in PR verification phase

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#30164]
### Parent Issue

No parent issue identified.

### Problem Statement

An error has been identified in the CICD workflow, specifically during the PR verification phase (- 1 PR Checks). A logical expression introduced in the workflow, although syntactically correct, causes runtime failures due to the resolved value potentially being incompatible with the expected data type. The issue arises with the following expression:

```
e2e: ${{ needs.initialize.outputs.build }} 
```

It must be replaced by 

```
e2e: ${{ needs.initialize.outputs.build }}  == 'true'
```

Note: The first string fails unless the value is an actual Boolean true. This will also not work for an empty string as false or a null/no value. The second expression explicitly converts and compares the string version of the value to 'true', handling all cases.

### Steps to Reproduce

1. Trigger the CICD workflow with a PR that includes the current expression `e2e: ${{ needs.initialize.outputs.build }}`.
2. Observe the runtime behavior and any potential failures due to incompatible data types.

Error: 

```
[-1 PR Check](https://github.com/dotCMS/core/actions/runs/11059788229/workflow)
The template is not valid. .github/workflows/cicd_1-pr.yml (Line: 72, Col: 12): Unexpected value 'true'
```

### Acceptance Criteria

1. The logical expression in the PR verification phase should:
   - Be updated to ensure compatibility with all potential resolved values at runtime.
   - Explicitly compare the value to 'true' to prevent type-related failures.
   - Be thoroughly tested to handle all possible cases, including boolean values, empty strings, and null/no values.

### dotCMS Version

Not applicable.

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

No external links provided.

### Assumptions & Initiation Needs

1. Ensure that the updated logical expression is compatible with the expected data types at runtime.
2. Review and validate any changes through comprehensive testing in the PR checks.

### Quality Assurance Notes & Workarounds

Testing should include various scenarios to confirm that the expression handles boolean, empty, and null values correctly.

### Sub-Tasks & Estimates

- [ ] Update the logical expression to explicitly compare the value to 'true'.
- [ ] Test the updated expression across different scenarios to validate the fix.
- [ ] Prepare and merge a PR with the corrected expression.
- [ ] Monitor the PR checks to ensure the issue is resolved.
