### ISSUE TITLE
CallToAction: Improves on components

### ISSUE THREAD

**Issue by KevinDavilaDotCMS** [dotCMS/core#30194]
### Task

- [ ] Homologate component, now we have 2 components for the same ContentType, we must to use only one
- [ ] Create a variants to CallToAction and make it editable from UVE
![image](https://github.com/user-attachments/assets/eae9be22-d9c6-4d0c-afea-c975358b6863)

- [ ] Fix url issues on CallToAction
- [ ] Add `a11y` props on CallToAction

### Proposed Objective

Marketing

### Proposed Priority

Priority 2 - Important
