### ISSUE TITLE
SDK publishing failure due to missing or incorrect authentication token

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#30246]
### Parent Issue

No parent issue identified.

### Problem Statement

The SDK publishing process is currently failing due to an issue with authentication. The required token is not being correctly provided, resulting in an authentication error. The error output includes the following message:

```
npm ERR! code ENEEDAUTH 
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/ 
npm ERR! need auth You need to authorize this machine using npm adduser

npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2024-09-25T21_45_46_112Z-debug-0.log
```

### Steps to Reproduce

1. Trigger the SDK publishing process in the CI/CD pipeline.
2. Observe the failure in the logs, indicating a need for authentication due to a missing or incorrect token.

### Acceptance Criteria

1. The SDK publishing process should:
   - Properly use the authentication token to ensure a successful login to the npm registry.
   - Complete without errors, ensuring that the SDK is published as expected.
   - Include validation to confirm the token is set and correct before attempting to publish.

### dotCMS Version

Not applicable.

### Proposed Objective

Quality Assurance

### Proposed Priority

Priority 1 - Show Stopper

### External Links... Slack Conversations, Support Tickets, Figma Designs, etc.

No external links provided.

### Assumptions & Initiation Needs

1. Verify that the correct authentication token is available and correctly configured in the environment.
2. Ensure access to npm registry credentials and validate them before initiating the publishing process.

### Quality Assurance Notes & Workarounds

Currently, no workaround is available; the token needs to be correctly set for successful publishing.

### Sub-Tasks & Estimates

- [ ] Investigate the missing or incorrect token issue and correct the configuration.
- [ ] Test the publishing process to ensure authentication is successful and no errors occur.
- [ ] Monitor the process post-deployment to confirm stability.

**Comment by valentinogiardino** [comment]
### IQA PASSED
The GitHub Action for publishing SDK updates is functioning correctly, and the updates have been successfully published as expected.

#### Video
https://github.com/user-attachments/assets/50f9ad30-f921-4d88-ba89-27b49d024d05
