### ISSUE TITLE
Generate new full and empty starters with the Locales portlet 

### ISSUE THREAD

**Issue by dsilvam** [dotCMS/core#30297]
### Task

After we run the upgrade task implemented in https://github.com/dotCMS/core/issues/30296 on both https://starter.dotcms.com/ and a local dotCMS with the latest empty starter, we need to generate the correspondent starters via download data/assets feature and upload them on jFrog (Artifactory). 

After the UT runs make sure the Locales portlet is available in the tool groups where Languages used to be available and also that the Languages portlet is not installed on any tool group.

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [x] New full starter version generated and available on jFrog. 
- [x] New empty starter version generated and available on jFrog. 
- [x] References to both starters updated in core

**Comment by hmoreras** [comment]
iQA: Locales are not show in the empty and full starter with urls: 

- https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/20241105/starter-20241105.zip
- https://repo.dotcms.com/artifactory/libs-release-local/com/dotcms/starter/empty_20241105/starter-empty_20241105.zip

<img width="1225" alt="image" src="https://github.com/user-attachments/assets/171c2f4e-d973-4371-987d-81a0f3ca4f39">

**Comment by josemejias11** [comment]
**Approved**: Tested on **trunk_4271248**, Docker, macOS 14.5, FF v126.0.1
