### ISSUE TITLE
FTM: Add Support for dotCMS Containers to Display Future Content Based on Publish Date

### ISSUE THREAD

**Issue by fabrizzio-dotCMS** [dotCMS/core#30552]
### Parent Issue

https://github.com/dotCMS/core/issues/30551

### Task

Following the initial investigation into container rendering logic, the goal of this issue is to extend support for dotCMS containers to allow them to display future content based on the publish date. This will enable containers to hold content that can be viewed in a future state, supporting dynamic content updates in dotCMS environments.

- Leverage the insights and expertise from the previous investigation to implement this feature safely.
- Modify relevant classes (e.g., PageLoader, PopulateContainer, and potentially ContainerLoader) to handle publish dates for future content.
- Ensure that existing functionality remains unaffected, and confirm that any new changes allow containers to render both current and scheduled content as expected.

### Proposed Objective

Same as Parent Issue

### Proposed Priority

Same as Parent Issue

```[tasklist]
### Acceptance Criteria
- [ ] dotCMS containers correctly interpret publish date values to conditionally display future content.
- [ ] Content updates scheduled with a future publish date are displayed as expected without impacting other container functionalities.
- [ ] Documentation on modifications and any notable code dependencies is provided.
```

**Comment by fmontes** [comment]
The new Future Time Machine feature in the Page API of dotCMS allows developers to request the “live” version of a page for a future date. If any content has a “working” version with a publish date set in the future, the API will return that “working” version instead of the current “live” version. Below are examples that illustrate how this works:

**Comment by fmontes** [comment]
We need to enable the `expiredDate`

**Comment by fabrizzio-dotCMS** [comment]
here's an example of the url 
http://localhost:8080/api/v1/page/render/test?mode=LIVE&publishDate=2024-11-15T06:00:00.000Z&language_id=1
The time machine param has been renamed to `publishDate`

**Comment by fmontes** [comment]
### IQ V1

1. Things are working as expected:
https://github.com/user-attachments/assets/c0b60cab-5374-443b-8207-4d799a1d1064

2. We need to add `publishDate` param to GraphQL. Is fine if you want to create another ticket, but is important that any change we do in the PageAPI needs to be suppoted in GQL as well. (Same applies for other APIs that are part of GQL)
3. Is not working in `curl` @fabrizzio-dotCMS already know that.

**Comment by fabrizzio-dotCMS** [comment]
The publishDate param (former tm-date) does not work using a curl request like this: 

curl -X GET 'http://localhost:8080/api/v1/page/render/testing-publish-date?language_id=1&com.dotmarketing.persona.id=modes.persona.no.persona&variantName=DEFAULT&mode=LIVE&publishDate=2024-11-26T10:00:00.000Z' \
-H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGci...' 
Because the time-machine functionality has always been tied to the session, we do it through the session when we pass around the tm_date param to the underlying layers. Therefore we need to pass some additional context on the request so the serverside has enough info to restore or construct a session.

**Comment by KevinDavilaDotCMS** [comment]
# IQA Passed
Tested on `910d7e2`


https://github.com/user-attachments/assets/a494ddf0-ca41-45ce-920b-6b26144621be



# Notes to QA
This documentation helps me to create a contentlets with a posting/expiration Dates: https://www2.dotcms.com/docs/latest/setting-publish-and-expire-dates-for-content

And i use [this](https://chromewebstore.google.com/detail/virtual-json-viewer/cipnpfcceoapeahdgomheoecidglopld?hl=es-ar) extension to visualize better the content.
It will probably help you test more easily

**Comment by fmontes** [comment]
@KevinDavilaDotCMS sorry but I forgot to add here that the param should take different date formats like theses: https://github.com/dotCMS/core/blob/main/dotCMS/src/main/java/com/dotmarketing/portlets/contentlet/business/ContentletAPI.java#L56

Please make sure it worked.

**Comment by KevinDavilaDotCMS** [comment]
### IQA Passed

Testing other date formats than ISO8601

https://github.com/user-attachments/assets/99a8d0f9-df89-4bbf-9ff9-8a1f5f0547fe
