### ISSUE TITLE
Refactor exception handling in ContentletAPITest to address SonarQube code smell

### ISSUE THREAD

**Issue by dcolina** [dotCMS/core#30572]
### Problem Statement

SonarQube has identified a code smell in the `ContentletAPITest.java` file related to the way checked exceptions are being handled within a `try/catch` block. The current implementation contains multiple method invocations that may throw the same checked exception. Best practice suggests refactoring to have only one method invocation within the `try` block when testing for checked exceptions.

**File:** `dotcms-integration/src/test/java/com/dotmarketing/portlets/contentlet/business/ContentletAPITest.java`

**Code Snippet:**

```java
try {
    newsContent = TestDataUtils
        .getNewsContent(false, languageAPI.getDefaultLanguage().getId(),
                        newsContentType.id());
    newsContent.setIdentifier(UUIDGenerator.generateUuid());
    final List<Category> categories = getACoupleOfCategories();
    newsContent = contentletAPI
        .checkin(newsContent, (ContentletRelationships) null,
                 categories,
                 null, user, false);
    fail("Should throw a constrain exception for an unexisting id");
} catch (Exception e) {
    if (e instanceof DotDataException || ExceptionUtil.causedBy(e, DotDataException.class)) {
        throw new DotDataException(e.getMessage());
    }
    fail("The exception catch should: DotHibernateException and is: " + e.getClass());
}
```

## Steps to Reproduce
1. Run a SonarQube analysis on the codebase.
2. Observe the code smell warning related to multiple method invocations within the `try` block that may throw the same checked exception.

## Acceptance Criteria
1. Refactor the `try/catch` block to ensure only one method invocation is present when testing for checked exceptions.
2. Ensure that the refactored code maintains the intended behavior and passes all existing tests.
3. Run SonarQube analysis again to confirm that the code smell is resolved.

## dotCMS Version
Not applicable.

## Proposed Objective
Quality Assurance

## Proposed Priority
Priority 2 - Important

## External Links... Slack Conversations, Support Tickets, Figma Designs, etc.
No external links provided.

## Assumptions & Initiation Needs
1. Refactor the code without changing the underlying logic or test objectives.
2. Validate the refactor by running the full test suite to ensure no regressions are introduced.

## Quality Assurance Notes & Workarounds
The goal is to refactor the `try/catch` block to improve code quality and readability while adhering to best practices for exception handling.

## Sub-Tasks & Estimates
- [ ] Refactor the `try/catch` block in `ContentletAPITest.java` as recommended by SonarQube.
- [ ] Run the test suite to ensure the refactor does not introduce new issues.
- [ ] Perform a SonarQube analysis to verify that the code smell is resolved.
