### ISSUE TITLE
[Content Import Job Management] Implement the Create Import Job REST endpoint

### ISSUE THREAD

**Issue by valentinogiardino** [dotCMS/core#30669]
### Parent Issue

#30550

### Task

Implement the POST /content/import endpoint to allow the creation and enqueuing of new content import jobs. This endpoint will initiate the content import process and return a unique job identifier.

`POST /content/import`

#### Parameters:

- **Content Type**: Specify the content type for the import (e.g., page, asset).
- **CSV File Reference**: Reference to the CSV file containing the content to be imported.
- **Language Code(s)**: Define the language(s) for the imported content.
- **Workflow Action Id**: Define the workflow action to apply to the imported content (e.g., publish, review).
- **Key Fields**: Specify the fields used to match and update existing content (e.g., `contentId`, `title`).

#### Description:

This endpoint creates a new content import job, enqueues it into the job queue, and returns a unique job identifier. The content import will proceed based on the provided parameters and failure handling options.

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- [x] The POST /content/import endpoint is implemented and returns a unique job identifier.
- [x] Basic validation is performed on input parameters (e.g., file type, content type).
- [x] Appropriate HTTP status codes are returned based on the request outcome.
- [x] Error messages are clear and actionable
- [x] The import job is successfully enqueued in the job queue system.
- [x] Postman tests are implemented

**Comment by fmontes** [comment]
## Internal QA

I did this internal in two runtimes, browser and nodejs.

### Browser
I build a little form with a input file and a button, see attached `index.html`

- If the file is a non-csv the endpoint doesn't error out and it should

https://github.com/user-attachments/assets/a67cbfff-c680-417b-bf24-e2e025fd6d22

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me

**Comment by fabrizzio-dotCMS** [comment]
we need to be able to support field ids like this:

```
{
    "cmd":"preview",
    "contentType":"webPageContent",
    "workflowActionId":"b9d89c80-3d88-4311-8365-187323c96436",
    "language":"en-us",
    "fields":["49c5bd96-d70c-441c-9c5f-7ccaa8e7ff9a","9f5a97dc-703c-4721-9cce-29478671558b"]
}
```
we're only supporting variable names

**Comment by fmontes** [comment]
Requiring field IDs creates unnecessary complexity and friction in the developer experience. We should modify the API to accept field variables name.

**Comment by fmontes** [comment]
> we need to be able to support field ids like this:
> 
> ```
> {
>     "cmd":"preview",
>     "contentType":"webPageContent",
>     "workflowActionId":"b9d89c80-3d88-4311-8365-187323c96436",
>     "language":"en-us",
>     "fields":["418e887e2af64f780ea8e9e736533e22"]
> }
> ```
> 
> we're only supporting variable names
> 
> { "message": "Field [418e887e2af64f780ea8e9e736533e22] not found in Content Type [TestImportJob]." }

We need to create a ticket for this, is a blocker for the release to pass the field var.
