### ISSUE TITLE
[Content Import Job Management] Implement the getJobStatus REST endpoint

### ISSUE THREAD

**Issue by valentinogiardino** [dotCMS/core#30791]
### Parent Issue

https://github.com/dotCMS/core/issues/30550

### Task

Implement the GET /content/_import/{jobId} endpoint to allow retrieving the status of a particual content import job.

GET /content/_import/{jobId}

Parameters:
jobId: The content import job id to search from
Description:
This endpoint retrieves the Job state, progress percentage, executing node, etc
```
      {
          "completedAt": "2024-11-26T20:25:33.042",
          "createdAt": "2024-11-26T20:25:32.105",
          "executionNode": "339aa0f7-ad27-48de-b912-a26a8381d2f4",
          "id": "af5a0f38-823c-4039-a4bc-810d812dcc69",
          "parameters": {
              "cmd": "publish",
              "contentType": "activity",
              "fields": [
                  "title"
              ],
              "language": "en-US",
              "requestFingerPrint": "LNre2vTjfQNwtpEwOgoEUOdSyJYrUwFqwMSvT9rBLls=",
              "siteIdentifier": "48190c8c-42c4-46af-8d1a-0cd5db894797",
              "siteName": "demo.dotcms.com",
              "tempFileId": "temp_93a3a436a6",
              "userId": "dotcms.org.1",
              "workflowActionId": "1234"
          },
          "progress": 1.0,
          "queueName": "importContentlets",
          "result": {
              "errorDetail": null,
              "metadata": null,
          },
          "retryCount": 0,
          "startedAt": "2024-11-26T20:25:32.992",
          "state": "COMPLETED",
          "updatedAt": "2024-11-26T20:25:33.042"
      },
 ```

### Proposed Objective

Core Features

### Proposed Priority

Priority 2 - Important

### Acceptance Criteria

- [ ] The GET /content/_import/{jobId} endpoint is implemented and returns a the job status information.
- [ ] Appropriate HTTP status codes are returned based on the request outcome.
- [ ] Error messages are clear and actionable
- [ ] Postman tests are implemented

**Comment by fabrizzio-dotCMS** [comment]
Looks good to me

**Comment by fmontes** [comment]
When we pass a bad `jobId` we show an error but also a stack trace and we should not, the error should come back in the correct structure and no stack trace, this is a security concert.

![Image](https://github.com/user-attachments/assets/72bea9f7-7e99-4290-bad1-e14559d687e7)

**Comment by nollymar** [comment]
I'm closing this issue after figuring out that the reason why @fmontes was getting the full stack trace was that he had this flag on `DOT_DOTCMS_DEV_MODE `
