### ISSUE TITLE
Import Job: Update API endpoints to return Job Status URL

### ISSUE THREAD

**Issue by nollymar** [dotCMS/core#30938]
### Task

Update the responses of following three existing REST API endpoints to include a URL link alongside the job ID in the response payload. 

1. POST /api/v1/jobs/{queueName}
2. POST api/v1/content/_import
3. POST /api/v1/content/_import/_validate

The URL should allow clients to access the job status for the given job ID by linking to the job status endpoint GET `/api/v1/jobs/{jobId}/status`

### Proposed Objective

Core Features

### Proposed Priority

Priority 3 - Average

### Acceptance Criteria

- [ ] Updated Response Structure including 

```
"jobId": "<job-id>",
"statusUrl": "<base-url>/job-status/<job-id>"
```
- [ ] API Playground documentation updated

- [ ] Postman or Karate tests implemented

**Comment by rjvelazco** [comment]
### Passed Internal QA

- Docker Image: [`dotcms/dotcms:trunk_ 3ae0421`]

### Video

https://github.com/user-attachments/assets/00e1f55a-0eac-4620-acf2-2b7c3a948d33
