### ISSUE TITLE
Provide RESTful Methods to manage Content Types

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9272]
We need to create restful APIs to perform crud applications on Content types.  Users looking for a 100% headless cms will want to create new custom content types via rest.  We need proper APIs and interfaces in order to do this.

## todo
- [ ] Allow custom fields to be defined in java/osgi
- [ ] Create renders (edit/listing/rest?/search/velocity/raw) that render the field's content values in different formats based on where the field is being used
- [ ] The rest endpoints :P

**Comment by dsilvam** [comment]
This branch became master-3.8
