### ISSUE TITLE
Allow dotCMS to be tested without needing servlets

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#9671]
We need to be able to test dotCMS without having to set up a J2EE environment.  Currently, this is impossible to do for a number of reasons.  
- [x] Allow Datasource to be injected
- [x] Allow Hibernate to startup
- [x] Allow Caching layer to init.
- [x] Allow Config.CONTEXT to be mocked
- [x] Figure out how to init/mock elasticsearch ( Will be worked here: https://github.com/dotCMS/core/issues/9750)

**Comment by dsilvam** [comment]
PR and notes on the usage: https://github.com/dotCMS/core/pull/9672
